// Package drm provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package drm

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

const (
	NcpAccessKeyScopes = "ncpAccessKey.Scopes"
	NcpHmacV2Scopes    = "ncpHmacV2.Scopes"
	NcpTimestampScopes = "ncpTimestamp.Scopes"
)

// NcloudErrorEnvelope Naver Cloud Platform standard error envelope. Most products return this shape; some (Object Storage, CLOVA) wrap differently — `additionalProperties: true` keeps clients tolerant.
type NcloudErrorEnvelope struct {
	// Error Alternative error field. Type varies: object (CLOVA, NCP standard), string (cert-manager Spring Boot 404), or null.
	Error interface{} `json:"error,omitempty"`

	// ResponseError Error detail (present on most NCP product errors). Field shape varies; `additionalProperties: true` keeps clients tolerant.
	ResponseError        *NcloudErrorEnvelope_ResponseError `json:"responseError,omitempty"`
	AdditionalProperties map[string]interface{}             `json:"-"`
}

// NcloudErrorEnvelope_ResponseError Error detail (present on most NCP product errors). Field shape varies; `additionalProperties: true` keeps clients tolerant.
type NcloudErrorEnvelope_ResponseError struct {
	// ReturnCode NCP error code.
	ReturnCode *string `json:"returnCode,omitempty"`

	// ReturnMessage Human-readable error message.
	ReturnMessage        *string                `json:"returnMessage,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// NcloudClientError Naver Cloud Platform standard error envelope. Most products return this shape; some (Object Storage, CLOVA) wrap differently — `additionalProperties: true` keeps clients tolerant.
type NcloudClientError = NcloudErrorEnvelope

// NcloudServerError Naver Cloud Platform standard error envelope. Most products return this shape; some (Object Storage, CLOVA) wrap differently — `additionalProperties: true` keeps clients tolerant.
type NcloudServerError = NcloudErrorEnvelope

// LicenseStatisticsParams defines parameters for LicenseStatistics.
type LicenseStatisticsParams struct {
	// SiteId 사이트 아이디 사이트 목록 조회 참조
	SiteId string `form:"siteId" json:"siteId"`

	// SearchCondition 검색 조건 contentId | drmType | userId | deviceId | deviceModel contentId : 콘텐츠 아이디 drmType : DRM 타입 userId : 사용자 아이디 deviceId : 기기 아이디 deviceModel : 기기 모델
	SearchCondition *string `form:"searchCondition,omitempty" json:"searchCondition,omitempty"`

	// SearchKeyword 검색 키워드
	SearchKeyword *string `form:"searchKeyword,omitempty" json:"searchKeyword,omitempty"`

	// StartTime 조회 시작 일시(밀리초) Unix Timestamp 형식
	StartTime *int `form:"startTime,omitempty" json:"startTime,omitempty"`

	// EndTime 조회 종료 일시(밀리초) Unix Timestamp 형식
	EndTime *int `form:"endTime,omitempty" json:"endTime,omitempty"`

	// PageNo 페이지 번호 1~N (기본값: 1)
	PageNo *int `form:"pageNo,omitempty" json:"pageNo,omitempty"`

	// PageSize 페이지당 항목 수 1~100
	PageSize *int `form:"pageSize,omitempty" json:"pageSize,omitempty"`

	// Status 라이선스 발급 성공 여부로 필터링 success | fail success : 성공 fail : 실패
	Status *string `form:"status,omitempty" json:"status,omitempty"`
}

// PolicyListParams defines parameters for PolicyList.
type PolicyListParams struct {
	// PageNo 페이지 번호 1~N (기본값: 1)
	PageNo *int `form:"pageNo,omitempty" json:"pageNo,omitempty"`

	// PageSize 페이지당 항목 수 1~100
	PageSize *int `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// PolicyCreateJSONBody defines parameters for PolicyCreate.
type PolicyCreateJSONBody struct {
	// DrmPolicyConfig DRM 타입별 정책 설정
	DrmPolicyConfig map[string]interface{} `json:"drmPolicyConfig"`

	// Persistent 오프라인용 라이선스 저장 여부 true | false (기본값) true : 라이선스 유지 false : 재생 후 라이선스 제거(스트리밍) rentalDuration (오프라인 렌탈 시나리오)을 사용하는 경우, true 로 필수 입력
	Persistent bool `json:"persistent"`

	// PlaybackDuration 콘텐츠 최초 재생 시작 시점부터의 라이선스 유효 기간(초) 0~2,147,483,647 (기본값: 0)
	PlaybackDuration int `json:"playbackDuration"`

	// PolicyName 정책 이름 영문자, 숫자, 특수 문자 '_'를 조합하여 3~20자 이내로 입력
	PolicyName string `json:"policyName"`

	// RentalDuration 오프라인 라이선스 획득 후 콘텐츠를 최초 재생해야 하는 유효 기간(초) 0~2,147,483,647 (기본값: 0) 오프라인 렌탈 시나리오 사용 시 설정
	RentalDuration int `json:"rentalDuration"`
}

// PolicyUpdateJSONBody defines parameters for PolicyUpdate.
type PolicyUpdateJSONBody struct {
	// DrmPolicyConfig DRM 타입별 정책 설정
	DrmPolicyConfig map[string]interface{} `json:"drmPolicyConfig"`

	// Persistent 오프라인용 라이선스 저장 여부 true | false (기본값) true : 라이선스 유지 false : 재생 후 라이선스 제거(스트리밍) rentalDuration (오프라인 렌탈 시나리오)을 사용하는 경우, true 로 필수 입력
	Persistent bool `json:"persistent"`

	// PlaybackDuration 콘텐츠 최초 재생 시작 시점부터의 라이선스 유효 기간(초) 0~2,147,483,647 (기본값: 0)
	PlaybackDuration int `json:"playbackDuration"`

	// PolicyName 정책 이름 영문자, 숫자, 특수 문자 '_'를 조합하여 3~20자 이내로 입력
	PolicyName string `json:"policyName"`

	// RentalDuration 오프라인 라이선스 획득 후, 콘텐츠를 최초 재생해야 하는 유효 기간(초) 0~2,147,483,647 (기본값: 0) 오프라인 렌탈 시나리오 사용 시 설정
	RentalDuration int `json:"rentalDuration"`
}

// ContentsEncryptionParams defines parameters for ContentsEncryption.
type ContentsEncryptionParams struct {
	// CpixCPIX 콘텐츠 키와 DRM 시스템 정보를 포함하는 CPIX 문서의 루트 요소
	CpixCPIX map[string]interface{} `form:"cpix:CPIX" json:"cpix:CPIX"`

	// CpixContentKeyList 콘텐츠 키 목록을 정의하는 컨테이너 요소
	CpixContentKeyList map[string]interface{} `form:"└ cpix:ContentKeyList" json:"└ cpix:ContentKeyList"`

	// CpixContentKey kid (Key ID) 속성을 가진 개별 콘텐츠 키 정보
	CpixContentKey map[string]interface{} `form:"└ cpix:ContentKey" json:"└ cpix:ContentKey"`

	// CpixDRMSystemList DRM 시스템 목록을 정의하는 컨테이너 요소
	CpixDRMSystemList map[string]interface{} `form:"└ cpix:DRMSystemList" json:"└ cpix:DRMSystemList"`

	// CpixDRMSystem kid (Key ID)와 systemId (DRM 시스템 식별자) 속성을 가진 각 DRM 시스템 정보
	CpixDRMSystem map[string]interface{} `form:"└ cpix:DRMSystem" json:"└ cpix:DRMSystem"`
}

// PolicyCreateJSONRequestBody defines body for PolicyCreate for application/json ContentType.
type PolicyCreateJSONRequestBody PolicyCreateJSONBody

// PolicyUpdateJSONRequestBody defines body for PolicyUpdate for application/json ContentType.
type PolicyUpdateJSONRequestBody PolicyUpdateJSONBody

// Getter for additional properties for NcloudErrorEnvelope. Returns the specified
// element and whether it was found
func (a NcloudErrorEnvelope) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for NcloudErrorEnvelope
func (a *NcloudErrorEnvelope) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for NcloudErrorEnvelope to handle AdditionalProperties
func (a *NcloudErrorEnvelope) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["error"]; found {
		err = json.Unmarshal(raw, &a.Error)
		if err != nil {
			return fmt.Errorf("error reading 'error': %w", err)
		}
		delete(object, "error")
	}

	if raw, found := object["responseError"]; found {
		err = json.Unmarshal(raw, &a.ResponseError)
		if err != nil {
			return fmt.Errorf("error reading 'responseError': %w", err)
		}
		delete(object, "responseError")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for NcloudErrorEnvelope to handle AdditionalProperties
func (a NcloudErrorEnvelope) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["error"], err = json.Marshal(a.Error)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'error': %w", err)
	}

	if a.ResponseError != nil {
		object["responseError"], err = json.Marshal(a.ResponseError)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'responseError': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for NcloudErrorEnvelope_ResponseError. Returns the specified
// element and whether it was found
func (a NcloudErrorEnvelope_ResponseError) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for NcloudErrorEnvelope_ResponseError
func (a *NcloudErrorEnvelope_ResponseError) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for NcloudErrorEnvelope_ResponseError to handle AdditionalProperties
func (a *NcloudErrorEnvelope_ResponseError) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["returnCode"]; found {
		err = json.Unmarshal(raw, &a.ReturnCode)
		if err != nil {
			return fmt.Errorf("error reading 'returnCode': %w", err)
		}
		delete(object, "returnCode")
	}

	if raw, found := object["returnMessage"]; found {
		err = json.Unmarshal(raw, &a.ReturnMessage)
		if err != nil {
			return fmt.Errorf("error reading 'returnMessage': %w", err)
		}
		delete(object, "returnMessage")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for NcloudErrorEnvelope_ResponseError to handle AdditionalProperties
func (a NcloudErrorEnvelope_ResponseError) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.ReturnCode != nil {
		object["returnCode"], err = json.Marshal(a.ReturnCode)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'returnCode': %w", err)
		}
	}

	if a.ReturnMessage != nil {
		object["returnMessage"], err = json.Marshal(a.ReturnMessage)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'returnMessage': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// LicenseStatistics request
	LicenseStatistics(ctx context.Context, params *LicenseStatisticsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PolicyList request
	PolicyList(ctx context.Context, params *PolicyListParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PolicyCreateWithBody request with any body
	PolicyCreateWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PolicyCreate(ctx context.Context, body PolicyCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PolicyDelete request
	PolicyDelete(ctx context.Context, policyId int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PolicyDetail request
	PolicyDetail(ctx context.Context, policyId int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PolicyUpdateWithBody request with any body
	PolicyUpdateWithBody(ctx context.Context, policyId int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PolicyUpdate(ctx context.Context, policyId int, body PolicyUpdateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PolicyCopy request
	PolicyCopy(ctx context.Context, policyId int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ContentsEncryption request
	ContentsEncryption(ctx context.Context, kmsToken string, params *ContentsEncryptionParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) LicenseStatistics(ctx context.Context, params *LicenseStatisticsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewLicenseStatisticsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PolicyList(ctx context.Context, params *PolicyListParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPolicyListRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PolicyCreateWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPolicyCreateRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PolicyCreate(ctx context.Context, body PolicyCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPolicyCreateRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PolicyDelete(ctx context.Context, policyId int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPolicyDeleteRequest(c.Server, policyId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PolicyDetail(ctx context.Context, policyId int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPolicyDetailRequest(c.Server, policyId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PolicyUpdateWithBody(ctx context.Context, policyId int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPolicyUpdateRequestWithBody(c.Server, policyId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PolicyUpdate(ctx context.Context, policyId int, body PolicyUpdateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPolicyUpdateRequest(c.Server, policyId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PolicyCopy(ctx context.Context, policyId int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPolicyCopyRequest(c.Server, policyId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ContentsEncryption(ctx context.Context, kmsToken string, params *ContentsEncryptionParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewContentsEncryptionRequest(c.Server, kmsToken, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewLicenseStatisticsRequest generates requests for LicenseStatistics
func NewLicenseStatisticsRequest(server string, params *LicenseStatisticsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/license/statistics")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "siteId", params.SiteId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if params.SearchCondition != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "searchCondition", *params.SearchCondition, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.SearchKeyword != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "searchKeyword", *params.SearchKeyword, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.StartTime != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "startTime", *params.StartTime, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.EndTime != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "endTime", *params.EndTime, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.PageNo != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "pageNo", *params.PageNo, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.PageSize != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "pageSize", *params.PageSize, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Status != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "status", *params.Status, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPolicyListRequest generates requests for PolicyList
func NewPolicyListRequest(server string, params *PolicyListParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/policy")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.PageNo != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "pageNo", *params.PageNo, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.PageSize != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "pageSize", *params.PageSize, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPolicyCreateRequest calls the generic PolicyCreate builder with application/json body
func NewPolicyCreateRequest(server string, body PolicyCreateJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPolicyCreateRequestWithBody(server, "application/json", bodyReader)
}

// NewPolicyCreateRequestWithBody generates requests for PolicyCreate with any type of body
func NewPolicyCreateRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/policy")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPolicyDeleteRequest generates requests for PolicyDelete
func NewPolicyDeleteRequest(server string, policyId int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "policyId", policyId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/policy/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPolicyDetailRequest generates requests for PolicyDetail
func NewPolicyDetailRequest(server string, policyId int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "policyId", policyId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/policy/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPolicyUpdateRequest calls the generic PolicyUpdate builder with application/json body
func NewPolicyUpdateRequest(server string, policyId int, body PolicyUpdateJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPolicyUpdateRequestWithBody(server, policyId, "application/json", bodyReader)
}

// NewPolicyUpdateRequestWithBody generates requests for PolicyUpdate with any type of body
func NewPolicyUpdateRequestWithBody(server string, policyId int, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "policyId", policyId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/policy/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPolicyCopyRequest generates requests for PolicyCopy
func NewPolicyCopyRequest(server string, policyId int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "policyId", policyId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/policy/%s/copy", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewContentsEncryptionRequest generates requests for ContentsEncryption
func NewContentsEncryptionRequest(server string, kmsToken string, params *ContentsEncryptionParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "kmsToken", kmsToken, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/cpix/pallycon/getKey/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "cpix:CPIX", params.CpixCPIX, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "object", Format: ""}); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "└ cpix:ContentKeyList", params.CpixContentKeyList, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "object", Format: ""}); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "└ cpix:ContentKey", params.CpixContentKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "object", Format: ""}); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "└ cpix:DRMSystemList", params.CpixDRMSystemList, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "object", Format: ""}); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "└ cpix:DRMSystem", params.CpixDRMSystem, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "object", Format: ""}); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// LicenseStatisticsWithResponse request
	LicenseStatisticsWithResponse(ctx context.Context, params *LicenseStatisticsParams, reqEditors ...RequestEditorFn) (*LicenseStatisticsHTTPResp, error)

	// PolicyListWithResponse request
	PolicyListWithResponse(ctx context.Context, params *PolicyListParams, reqEditors ...RequestEditorFn) (*PolicyListHTTPResp, error)

	// PolicyCreateWithBodyWithResponse request with any body
	PolicyCreateWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PolicyCreateHTTPResp, error)

	PolicyCreateWithResponse(ctx context.Context, body PolicyCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*PolicyCreateHTTPResp, error)

	// PolicyDeleteWithResponse request
	PolicyDeleteWithResponse(ctx context.Context, policyId int, reqEditors ...RequestEditorFn) (*PolicyDeleteHTTPResp, error)

	// PolicyDetailWithResponse request
	PolicyDetailWithResponse(ctx context.Context, policyId int, reqEditors ...RequestEditorFn) (*PolicyDetailHTTPResp, error)

	// PolicyUpdateWithBodyWithResponse request with any body
	PolicyUpdateWithBodyWithResponse(ctx context.Context, policyId int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PolicyUpdateHTTPResp, error)

	PolicyUpdateWithResponse(ctx context.Context, policyId int, body PolicyUpdateJSONRequestBody, reqEditors ...RequestEditorFn) (*PolicyUpdateHTTPResp, error)

	// PolicyCopyWithResponse request
	PolicyCopyWithResponse(ctx context.Context, policyId int, reqEditors ...RequestEditorFn) (*PolicyCopyHTTPResp, error)

	// ContentsEncryptionWithResponse request
	ContentsEncryptionWithResponse(ctx context.Context, kmsToken string, params *ContentsEncryptionParams, reqEditors ...RequestEditorFn) (*ContentsEncryptionHTTPResp, error)
}

type LicenseStatisticsHTTPResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		// Content 라이선스 발급 이력 목록: content
		Content *[]map[string]interface{} `json:"content,omitempty"`

		// Success API 처리 결과 true | false true : 성공 false : 실패
		Success *bool `json:"success,omitempty"`

		// Total 전체 응답 수
		Total *int `json:"total,omitempty"`
	}
	JSON4XX *NcloudClientError
	JSON5XX *NcloudServerError
}

// Status returns HTTPResponse.Status
func (r LicenseStatisticsHTTPResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r LicenseStatisticsHTTPResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PolicyListHTTPResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		// Content 정책 목록: content
		Content *[]map[string]interface{} `json:"content,omitempty"`

		// Success API 처리 결과 true | false true : 성공 false : 실패
		Success *bool `json:"success,omitempty"`

		// Total 전체 응답 수
		Total *int `json:"total,omitempty"`
	}
	JSON4XX *NcloudClientError
	JSON5XX *NcloudServerError
}

// Status returns HTTPResponse.Status
func (r PolicyListHTTPResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PolicyListHTTPResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PolicyCreateHTTPResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		// Content 정책 정보
		Content *map[string]interface{} `json:"content,omitempty"`

		// Success API 처리 결과 true | false true : 성공 false : 실패
		Success *bool `json:"success,omitempty"`
	}
	JSON4XX *NcloudClientError
	JSON5XX *NcloudServerError
}

// Status returns HTTPResponse.Status
func (r PolicyCreateHTTPResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PolicyCreateHTTPResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PolicyDeleteHTTPResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		// Content 정책 정보
		Content *map[string]interface{} `json:"content,omitempty"`

		// Success API 처리 결과 true | false true : 성공 false : 실패
		Success *bool `json:"success,omitempty"`
	}
	JSON4XX *NcloudClientError
	JSON5XX *NcloudServerError
}

// Status returns HTTPResponse.Status
func (r PolicyDeleteHTTPResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PolicyDeleteHTTPResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PolicyDetailHTTPResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		// Content 정책 정보
		Content *map[string]interface{} `json:"content,omitempty"`

		// Success API 처리 결과 true | false true : 성공 false : 실패
		Success *bool `json:"success,omitempty"`
	}
	JSON4XX *NcloudClientError
	JSON5XX *NcloudServerError
}

// Status returns HTTPResponse.Status
func (r PolicyDetailHTTPResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PolicyDetailHTTPResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PolicyUpdateHTTPResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		// Content 정책 정보
		Content *map[string]interface{} `json:"content,omitempty"`

		// Success API 처리 결과 true | false true : 성공 false : 실패
		Success *bool `json:"success,omitempty"`
	}
	JSON4XX *NcloudClientError
	JSON5XX *NcloudServerError
}

// Status returns HTTPResponse.Status
func (r PolicyUpdateHTTPResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PolicyUpdateHTTPResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PolicyCopyHTTPResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		// Content 정책 정보
		Content *map[string]interface{} `json:"content,omitempty"`

		// Success API 처리 결과 true | false true : 성공 false : 실패
		Success *bool `json:"success,omitempty"`
	}
	JSON4XX *NcloudClientError
	JSON5XX *NcloudServerError
}

// Status returns HTTPResponse.Status
func (r PolicyCopyHTTPResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PolicyCopyHTTPResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ContentsEncryptionHTTPResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		// CpixCPIX 콘텐츠 아이디(CID) 키와 DRM 시스템 정보를 포함하는 CPIX 문서의 루트 요소
		CpixCPIX *map[string]interface{} `json:"cpix:CPIX,omitempty"`

		// CpixContentKey kid (Key ID)와 explicitIV (초기화 벡터) 속성을 가진 개별 콘텐츠 키 정보 kid 값은 요청 데이터에 입력된 값과 별개로 KMS 에서 새로 생성된 값이 적용되며, 키와 IV는 Base64 인코딩된 형태로 리턴됨
		CpixContentKey *map[string]interface{} `json:"└ cpix:ContentKey,omitempty"`

		// CpixContentKeyList 콘텐츠 키 목록을 정의하는 컨테이너 요소
		CpixContentKeyList *map[string]interface{} `json:"└ cpix:ContentKeyList,omitempty"`

		// CpixContentProtectionData Base64로 인코딩된 PSSH 데이터에서 헤더가 제거된 Payload 부분
		CpixContentProtectionData *string `json:"└ cpix:ContentProtectionData,omitempty"`

		// CpixDRMSystem kid (Key ID)와 systemId (DRM 시스템 식별자) 속성을 가진 각 DRM 시스템 정보
		CpixDRMSystem *map[string]interface{} `json:"└ cpix:DRMSystem,omitempty"`

		// CpixDRMSystemList DRM 시스템 목록을 정의하는 컨테이너 요소
		CpixDRMSystemList *map[string]interface{} `json:"└ cpix:DRMSystemList,omitempty"`

		// CpixData 콘텐츠 키 데이터를 포함하는 요소
		CpixData *map[string]interface{} `json:"└ cpix:Data,omitempty"`

		// CpixPSSH Base64로 인코딩된 PSSH 데이터(헤더 포함)
		CpixPSSH *string `json:"└ cpix:PSSH,omitempty"`

		// PskcPlainValue Base64로 인코딩된 콘텐츠 키 값
		PskcPlainValue *string `json:"└ pskc:PlainValue,omitempty"`

		// PskcSecret 콘텐츠 키의 비밀 데이터를 포함하는 요소
		PskcSecret *map[string]interface{} `json:"└ pskc:Secret,omitempty"`
	}
	JSON4XX *NcloudClientError
	JSON5XX *NcloudServerError
}

// Status returns HTTPResponse.Status
func (r ContentsEncryptionHTTPResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ContentsEncryptionHTTPResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// LicenseStatisticsWithResponse request returning *LicenseStatisticsHTTPResp
func (c *ClientWithResponses) LicenseStatisticsWithResponse(ctx context.Context, params *LicenseStatisticsParams, reqEditors ...RequestEditorFn) (*LicenseStatisticsHTTPResp, error) {
	rsp, err := c.LicenseStatistics(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseLicenseStatisticsHTTPResp(rsp)
}

// PolicyListWithResponse request returning *PolicyListHTTPResp
func (c *ClientWithResponses) PolicyListWithResponse(ctx context.Context, params *PolicyListParams, reqEditors ...RequestEditorFn) (*PolicyListHTTPResp, error) {
	rsp, err := c.PolicyList(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePolicyListHTTPResp(rsp)
}

// PolicyCreateWithBodyWithResponse request with arbitrary body returning *PolicyCreateHTTPResp
func (c *ClientWithResponses) PolicyCreateWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PolicyCreateHTTPResp, error) {
	rsp, err := c.PolicyCreateWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePolicyCreateHTTPResp(rsp)
}

func (c *ClientWithResponses) PolicyCreateWithResponse(ctx context.Context, body PolicyCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*PolicyCreateHTTPResp, error) {
	rsp, err := c.PolicyCreate(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePolicyCreateHTTPResp(rsp)
}

// PolicyDeleteWithResponse request returning *PolicyDeleteHTTPResp
func (c *ClientWithResponses) PolicyDeleteWithResponse(ctx context.Context, policyId int, reqEditors ...RequestEditorFn) (*PolicyDeleteHTTPResp, error) {
	rsp, err := c.PolicyDelete(ctx, policyId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePolicyDeleteHTTPResp(rsp)
}

// PolicyDetailWithResponse request returning *PolicyDetailHTTPResp
func (c *ClientWithResponses) PolicyDetailWithResponse(ctx context.Context, policyId int, reqEditors ...RequestEditorFn) (*PolicyDetailHTTPResp, error) {
	rsp, err := c.PolicyDetail(ctx, policyId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePolicyDetailHTTPResp(rsp)
}

// PolicyUpdateWithBodyWithResponse request with arbitrary body returning *PolicyUpdateHTTPResp
func (c *ClientWithResponses) PolicyUpdateWithBodyWithResponse(ctx context.Context, policyId int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PolicyUpdateHTTPResp, error) {
	rsp, err := c.PolicyUpdateWithBody(ctx, policyId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePolicyUpdateHTTPResp(rsp)
}

func (c *ClientWithResponses) PolicyUpdateWithResponse(ctx context.Context, policyId int, body PolicyUpdateJSONRequestBody, reqEditors ...RequestEditorFn) (*PolicyUpdateHTTPResp, error) {
	rsp, err := c.PolicyUpdate(ctx, policyId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePolicyUpdateHTTPResp(rsp)
}

// PolicyCopyWithResponse request returning *PolicyCopyHTTPResp
func (c *ClientWithResponses) PolicyCopyWithResponse(ctx context.Context, policyId int, reqEditors ...RequestEditorFn) (*PolicyCopyHTTPResp, error) {
	rsp, err := c.PolicyCopy(ctx, policyId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePolicyCopyHTTPResp(rsp)
}

// ContentsEncryptionWithResponse request returning *ContentsEncryptionHTTPResp
func (c *ClientWithResponses) ContentsEncryptionWithResponse(ctx context.Context, kmsToken string, params *ContentsEncryptionParams, reqEditors ...RequestEditorFn) (*ContentsEncryptionHTTPResp, error) {
	rsp, err := c.ContentsEncryption(ctx, kmsToken, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseContentsEncryptionHTTPResp(rsp)
}

// ParseLicenseStatisticsHTTPResp parses an HTTP response from a LicenseStatisticsWithResponse call
func ParseLicenseStatisticsHTTPResp(rsp *http.Response) (*LicenseStatisticsHTTPResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &LicenseStatisticsHTTPResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Content 라이선스 발급 이력 목록: content
			Content *[]map[string]interface{} `json:"content,omitempty"`

			// Success API 처리 결과 true | false true : 성공 false : 실패
			Success *bool `json:"success,omitempty"`

			// Total 전체 응답 수
			Total *int `json:"total,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest NcloudClientError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest NcloudServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParsePolicyListHTTPResp parses an HTTP response from a PolicyListWithResponse call
func ParsePolicyListHTTPResp(rsp *http.Response) (*PolicyListHTTPResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PolicyListHTTPResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Content 정책 목록: content
			Content *[]map[string]interface{} `json:"content,omitempty"`

			// Success API 처리 결과 true | false true : 성공 false : 실패
			Success *bool `json:"success,omitempty"`

			// Total 전체 응답 수
			Total *int `json:"total,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest NcloudClientError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest NcloudServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParsePolicyCreateHTTPResp parses an HTTP response from a PolicyCreateWithResponse call
func ParsePolicyCreateHTTPResp(rsp *http.Response) (*PolicyCreateHTTPResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PolicyCreateHTTPResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Content 정책 정보
			Content *map[string]interface{} `json:"content,omitempty"`

			// Success API 처리 결과 true | false true : 성공 false : 실패
			Success *bool `json:"success,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest NcloudClientError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest NcloudServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParsePolicyDeleteHTTPResp parses an HTTP response from a PolicyDeleteWithResponse call
func ParsePolicyDeleteHTTPResp(rsp *http.Response) (*PolicyDeleteHTTPResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PolicyDeleteHTTPResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Content 정책 정보
			Content *map[string]interface{} `json:"content,omitempty"`

			// Success API 처리 결과 true | false true : 성공 false : 실패
			Success *bool `json:"success,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest NcloudClientError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest NcloudServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParsePolicyDetailHTTPResp parses an HTTP response from a PolicyDetailWithResponse call
func ParsePolicyDetailHTTPResp(rsp *http.Response) (*PolicyDetailHTTPResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PolicyDetailHTTPResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Content 정책 정보
			Content *map[string]interface{} `json:"content,omitempty"`

			// Success API 처리 결과 true | false true : 성공 false : 실패
			Success *bool `json:"success,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest NcloudClientError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest NcloudServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParsePolicyUpdateHTTPResp parses an HTTP response from a PolicyUpdateWithResponse call
func ParsePolicyUpdateHTTPResp(rsp *http.Response) (*PolicyUpdateHTTPResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PolicyUpdateHTTPResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Content 정책 정보
			Content *map[string]interface{} `json:"content,omitempty"`

			// Success API 처리 결과 true | false true : 성공 false : 실패
			Success *bool `json:"success,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest NcloudClientError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest NcloudServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParsePolicyCopyHTTPResp parses an HTTP response from a PolicyCopyWithResponse call
func ParsePolicyCopyHTTPResp(rsp *http.Response) (*PolicyCopyHTTPResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PolicyCopyHTTPResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Content 정책 정보
			Content *map[string]interface{} `json:"content,omitempty"`

			// Success API 처리 결과 true | false true : 성공 false : 실패
			Success *bool `json:"success,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest NcloudClientError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest NcloudServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParseContentsEncryptionHTTPResp parses an HTTP response from a ContentsEncryptionWithResponse call
func ParseContentsEncryptionHTTPResp(rsp *http.Response) (*ContentsEncryptionHTTPResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ContentsEncryptionHTTPResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// CpixCPIX 콘텐츠 아이디(CID) 키와 DRM 시스템 정보를 포함하는 CPIX 문서의 루트 요소
			CpixCPIX *map[string]interface{} `json:"cpix:CPIX,omitempty"`

			// CpixContentKey kid (Key ID)와 explicitIV (초기화 벡터) 속성을 가진 개별 콘텐츠 키 정보 kid 값은 요청 데이터에 입력된 값과 별개로 KMS 에서 새로 생성된 값이 적용되며, 키와 IV는 Base64 인코딩된 형태로 리턴됨
			CpixContentKey *map[string]interface{} `json:"└ cpix:ContentKey,omitempty"`

			// CpixContentKeyList 콘텐츠 키 목록을 정의하는 컨테이너 요소
			CpixContentKeyList *map[string]interface{} `json:"└ cpix:ContentKeyList,omitempty"`

			// CpixContentProtectionData Base64로 인코딩된 PSSH 데이터에서 헤더가 제거된 Payload 부분
			CpixContentProtectionData *string `json:"└ cpix:ContentProtectionData,omitempty"`

			// CpixDRMSystem kid (Key ID)와 systemId (DRM 시스템 식별자) 속성을 가진 각 DRM 시스템 정보
			CpixDRMSystem *map[string]interface{} `json:"└ cpix:DRMSystem,omitempty"`

			// CpixDRMSystemList DRM 시스템 목록을 정의하는 컨테이너 요소
			CpixDRMSystemList *map[string]interface{} `json:"└ cpix:DRMSystemList,omitempty"`

			// CpixData 콘텐츠 키 데이터를 포함하는 요소
			CpixData *map[string]interface{} `json:"└ cpix:Data,omitempty"`

			// CpixPSSH Base64로 인코딩된 PSSH 데이터(헤더 포함)
			CpixPSSH *string `json:"└ cpix:PSSH,omitempty"`

			// PskcPlainValue Base64로 인코딩된 콘텐츠 키 값
			PskcPlainValue *string `json:"└ pskc:PlainValue,omitempty"`

			// PskcSecret 콘텐츠 키의 비밀 데이터를 포함하는 요소
			PskcSecret *map[string]interface{} `json:"└ pskc:Secret,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest NcloudClientError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest NcloudServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}
