// Code generated by gen/build_endpoints.py. DO NOT EDIT.

package webshell_behavior_detector

import (
	"github.com/greedylabs/ncloud-community-sdk/sdk"
)

// ServerEndpoints maps each NCP environment supported by
// the webshell-behavior-detector service to its base URL template. Templates may
// contain {regionCode} (substituted from cfg.Region at
// NewFromConfig time) and {basePath} (resolved by
// resolveBasePath when present).
var ServerEndpoints = map[ncloud.Environment]string{
	ncloud.EnvPublic: "https://wbd.apigw.ntruss.com",
	ncloud.EnvFinancial: "https://wbd.apigw.fin-ntruss.com",
	ncloud.EnvGov: "https://wbd.apigw.gov-ntruss.com",
}

// NewFromConfig builds a ClientWithResponses for the environment
// and credentials carried by cfg. The HTTP client is the signed
// transport from the root ncloudgo package — HMAC v2 for the
// general API surface, AWS SigV4 for Object Storage.
//
//	cfg, _ := ncloud.LoadDefaultConfig(ctx)
//	c, _   := webshell_behavior_detector.NewFromConfig(cfg)
func NewFromConfig(cfg ncloud.Config, opts ...ClientOption) (*ClientWithResponses, error) {
	server, ok := ServerEndpoints[cfg.Env]
	if !ok {
		return nil, &unsupportedEnvError{env: string(cfg.Env)}
	}
	hc, err := ncloud.NewHTTPClient(cfg)
	if err != nil {
		return nil, err
	}
	allOpts := append([]ClientOption{WithHTTPClient(hc)}, opts...)
	return NewClientWithResponses(server, allOpts...)
}

type unsupportedEnvError struct{ env string }

func (e *unsupportedEnvError) Error() string {
	return "webshell_behavior_detector: environment \"" + e.env + "\" not supported by webshell-behavior-detector"
}
