// Code generated by tools/build_cli_typed.py. DO NOT EDIT.

package services

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"

	clicmd "github.com/greedylabs/ncloud-community-sdk/cli/cmd"
	ncloud "github.com/greedylabs/ncloud-community-sdk/sdk"
	blockchain "github.com/greedylabs/ncloud-community-sdk/sdk/services/blockchain"
)

var _ = bytes.NewBuffer
var _ = json.Unmarshal
var _ = fmt.Sprintf
var _ io.Reader = nil
var _ = os.Open
var _ = ncloud.AsAPIError

func init() {
	parent := &cobra.Command{ Use: "blockchain", Short: "blockchain" }
	parent.AddCommand(buildBlockchainDownloadCaIdEntityCertKey())
	parent.AddCommand(buildBlockchainDownloadConnectionProfileOfmsp())
	parent.AddCommand(buildBlockchainDownloadOrdererConnectionProfile())
	parent.AddCommand(buildBlockchainViewCaDetailS())
	parent.AddCommand(buildBlockchainViewCaList())
	parent.AddCommand(buildBlockchainViewCaPodsLog())
	parent.AddCommand(buildBlockchainViewCaPodsUsage())
	parent.AddCommand(buildBlockchainViewNetworkDetailS())
	parent.AddCommand(buildBlockchainViewNetworkList())
	parent.AddCommand(buildBlockchainViewOrdererDetailS())
	parent.AddCommand(buildBlockchainViewOrdererList())
	parent.AddCommand(buildBlockchainViewOrdererPodsLog())
	parent.AddCommand(buildBlockchainViewOrdererPodsUsage())
	parent.AddCommand(buildBlockchainViewOrganizationDetailS())
	parent.AddCommand(buildBlockchainViewOrganizationList())
	parent.AddCommand(buildBlockchainViewPeerDetailS())
	parent.AddCommand(buildBlockchainViewPeerList())
	parent.AddCommand(buildBlockchainViewPeerPodsLog())
	parent.AddCommand(buildBlockchainViewPeerPodsUsage())
	clicmd.RegisterServiceCmd(parent)
}

func buildBlockchainDownloadCaIdEntityCertKey() *cobra.Command {
	var arg_networkId string
	var arg_caId string
	var arg_identityName string
	c := &cobra.Command{
		Use: "download-ca-id-entity-cert-key",
		Short: "CA Identity 다운로드",
		Long: "VPC 환경에서 이용 가능합니다.",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := blockchain.NewFromConfig(cfg)
			if err != nil { return err }
			pa_networkId := mustAtoi64(arg_networkId)
			resp, err := client.DownloadCaIdEntityCertKeyWithResponse(c.Context(), pa_networkId, arg_caId, arg_identityName)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&arg_networkId, "networkId", "", "[PATH] 네트워크 아이디 Network 목록 조회 참조")
	_ = c.MarkFlagRequired("networkId")
	c.Flags().StringVar(&arg_caId, "caId", "", "[PATH] CA 아이디 CA 목록 조회 참조")
	_ = c.MarkFlagRequired("caId")
	c.Flags().StringVar(&arg_identityName, "identityName", "", "[PATH] CA Identity 이름 CA Identity 목록/정보 조회 참조")
	_ = c.MarkFlagRequired("identityName")
	return c
}

func buildBlockchainDownloadConnectionProfileOfmsp() *cobra.Command {
	var arg_networkId string
	var arg_mspId string
	c := &cobra.Command{
		Use: "download-connection-profile-ofmsp",
		Short: "Organization 연결 정보 다운로드",
		Long: "VPC 환경에서 이용 가능합니다.",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := blockchain.NewFromConfig(cfg)
			if err != nil { return err }
			pa_networkId := mustAtoi64(arg_networkId)
			resp, err := client.DownloadConnectionProfileOfmspWithResponse(c.Context(), pa_networkId, arg_mspId)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&arg_networkId, "networkId", "", "[PATH] 네트워크 아이디 Network 목록 조회 참조")
	_ = c.MarkFlagRequired("networkId")
	c.Flags().StringVar(&arg_mspId, "mspId", "", "[PATH] Organization MSP 아이디 Organization 목록 조회 참조")
	_ = c.MarkFlagRequired("mspId")
	return c
}

func buildBlockchainDownloadOrdererConnectionProfile() *cobra.Command {
	var arg_networkId string
	var arg_ordererId string
	c := &cobra.Command{
		Use: "download-orderer-connection-profile",
		Short: "Orderer 연결 정보 다운로드",
		Long: "VPC 환경에서 이용 가능합니다.",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := blockchain.NewFromConfig(cfg)
			if err != nil { return err }
			pa_networkId := mustAtoi64(arg_networkId)
			resp, err := client.DownloadOrdererConnectionProfileWithResponse(c.Context(), pa_networkId, arg_ordererId)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&arg_networkId, "networkId", "", "[PATH] 네트워크 아이디 Network 목록 조회 참조")
	_ = c.MarkFlagRequired("networkId")
	c.Flags().StringVar(&arg_ordererId, "ordererId", "", "[PATH] Orderer 아이디 Orderer 목록 조회 참조")
	_ = c.MarkFlagRequired("ordererId")
	return c
}

func buildBlockchainViewCaDetailS() *cobra.Command {
	var arg_networkId string
	var arg_caId string
	c := &cobra.Command{
		Use: "view-ca-detail-s",
		Short: "CA 정보 조회",
		Long: "VPC 환경에서 이용 가능합니다.",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := blockchain.NewFromConfig(cfg)
			if err != nil { return err }
			pa_networkId := mustAtoi64(arg_networkId)
			resp, err := client.ViewCaDetailSWithResponse(c.Context(), pa_networkId, arg_caId)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&arg_networkId, "networkId", "", "[PATH] 네트워크 아이디 Network 목록 조회 참조")
	_ = c.MarkFlagRequired("networkId")
	c.Flags().StringVar(&arg_caId, "caId", "", "[PATH] CA 아이디 CA 목록 조회 참조")
	_ = c.MarkFlagRequired("caId")
	return c
}

func buildBlockchainViewCaList() *cobra.Command {
	var arg_networkId string
	var p_Page string
	var p_Size string
	c := &cobra.Command{
		Use: "view-ca-list",
		Short: "CA 목록 조회",
		Long: "VPC 환경에서 이용 가능합니다.",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := blockchain.NewFromConfig(cfg)
			if err != nil { return err }
			pa_networkId := mustAtoi64(arg_networkId)
			params := &blockchain.ViewCaListParams{}
			if c.Flags().Changed("page") {
				v := mustAtoi(p_Page)
				local := v
				params.Page = &local
			}
			if c.Flags().Changed("size") {
				v := mustAtoi(p_Size)
				local := v
				params.Size = &local
			}
			resp, err := client.ViewCaListWithResponse(c.Context(), pa_networkId, params)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&arg_networkId, "networkId", "", "[PATH] 네트워크 아이디 Network 목록 조회 참조")
	_ = c.MarkFlagRequired("networkId")
	c.Flags().StringVar(&p_Page, "page", "", "페이지 번호 0 (기본값)")
	c.Flags().StringVar(&p_Size, "size", "", "조회 결과 목록 크기 20 (기본값)")
	return c
}

func buildBlockchainViewCaPodsLog() *cobra.Command {
	var arg_networkId string
	var arg_caId string
	var p_TailLines string
	c := &cobra.Command{
		Use: "view-ca-pods-log",
		Short: "CA Pod 로그 조회",
		Long: "VPC 환경에서 이용 가능합니다.",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := blockchain.NewFromConfig(cfg)
			if err != nil { return err }
			pa_networkId := mustAtoi64(arg_networkId)
			params := &blockchain.ViewCaPodsLogParams{}
			if c.Flags().Changed("tailLines") {
				v := mustAtoi(p_TailLines)
				local := v
				params.TailLines = &local
			}
			resp, err := client.ViewCaPodsLogWithResponse(c.Context(), pa_networkId, arg_caId, params)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&arg_networkId, "networkId", "", "[PATH] 네트워크 아이디 Network 목록 조회 참조")
	_ = c.MarkFlagRequired("networkId")
	c.Flags().StringVar(&arg_caId, "caId", "", "[PATH] CA 아이디 CA 목록 조회 참조")
	_ = c.MarkFlagRequired("caId")
	c.Flags().StringVar(&p_TailLines, "tailLines", "", "로그의 라인 수 1,000 (기본값)")
	return c
}

func buildBlockchainViewCaPodsUsage() *cobra.Command {
	var arg_networkId string
	var arg_caId string
	var p_StartTime string
	var p_EndTime string
	c := &cobra.Command{
		Use: "view-ca-pods-usage",
		Short: "CA Pod 사용량 조회",
		Long: "VPC 환경에서 이용 가능합니다.",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := blockchain.NewFromConfig(cfg)
			if err != nil { return err }
			pa_networkId := mustAtoi64(arg_networkId)
			params := &blockchain.ViewCaPodsUsageParams{}
			if c.Flags().Changed("startTime") {
				v := mustAtoi(p_StartTime)
				params.StartTime = v
			}
			if c.Flags().Changed("endTime") {
				v := mustAtoi(p_EndTime)
				params.EndTime = v
			}
			resp, err := client.ViewCaPodsUsageWithResponse(c.Context(), pa_networkId, arg_caId, params)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&arg_networkId, "networkId", "", "[PATH] 네트워크 아이디 Network 목록 조회 참조")
	_ = c.MarkFlagRequired("networkId")
	c.Flags().StringVar(&arg_caId, "caId", "", "[PATH] CA 아이디 CA 목록 조회 참조")
	_ = c.MarkFlagRequired("caId")
	c.Flags().StringVar(&p_StartTime, "startTime", "", "사용량 조회 시작 시각 Unix Timestamp 형식 <예시> 2024년 07월 30일 09시 00분 00초인 경우 startTime=1722297600000")
	c.Flags().StringVar(&p_EndTime, "endTime", "", "사용량 조회 종료 시각 Unix Timestamp 형식 <예시> 2024년 07월 30일 15시 00분 00초인 경우 endTime=1722319200000")
	return c
}

func buildBlockchainViewNetworkDetailS() *cobra.Command {
	var arg_networkId string
	c := &cobra.Command{
		Use: "view-network-detail-s",
		Short: "Network 정보 조회",
		Long: "VPC 환경에서 이용 가능합니다.",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := blockchain.NewFromConfig(cfg)
			if err != nil { return err }
			pa_networkId := mustAtoi64(arg_networkId)
			resp, err := client.ViewNetworkDetailSWithResponse(c.Context(), pa_networkId)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&arg_networkId, "networkId", "", "[PATH] 네트워크 아이디 Network 목록 조회 참조")
	_ = c.MarkFlagRequired("networkId")
	return c
}

func buildBlockchainViewNetworkList() *cobra.Command {
	var p_Page string
	var p_Size string
	var p_Sort string
	c := &cobra.Command{
		Use: "view-network-list",
		Short: "Network 목록 조회",
		Long: "VPC 환경에서 이용 가능합니다.",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := blockchain.NewFromConfig(cfg)
			if err != nil { return err }
			params := &blockchain.ViewNetworkListParams{}
			if c.Flags().Changed("page") {
				v := mustAtoi(p_Page)
				local := v
				params.Page = &local
			}
			if c.Flags().Changed("size") {
				v := mustAtoi(p_Size)
				local := v
				params.Size = &local
			}
			if c.Flags().Changed("sort") {
				local := p_Sort
				params.Sort = &local
			}
			resp, err := client.ViewNetworkListWithResponse(c.Context(), params)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&p_Page, "page", "", "페이지 번호 0 (기본값)")
	c.Flags().StringVar(&p_Size, "size", "", "조회 결과 목록 크기 20 (기본값)")
	c.Flags().StringVar(&p_Sort, "sort", "", "정렬 기준 오름차순 (기본값) networkId | networkName | nksClusterName | networkStatus | createDt | updateDt networkId : 네트워크 아이디 networkName : 네트워크 이름 nksClusterName : Ncloud Kubernetes Service 클러스터 이름 networkStatus : 네트워크 상태 createDt : 네트워크 생성 일시 updateDt : 네트워크 수정 일시")
	return c
}

func buildBlockchainViewOrdererDetailS() *cobra.Command {
	var arg_networkId string
	var arg_ordererId string
	c := &cobra.Command{
		Use: "view-orderer-detail-s",
		Short: "Orderer 정보 조회",
		Long: "VPC 환경에서 이용 가능합니다.",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := blockchain.NewFromConfig(cfg)
			if err != nil { return err }
			pa_networkId := mustAtoi64(arg_networkId)
			resp, err := client.ViewOrdererDetailSWithResponse(c.Context(), pa_networkId, arg_ordererId)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&arg_networkId, "networkId", "", "[PATH] 네트워크 아이디 Network 목록 조회 참조")
	_ = c.MarkFlagRequired("networkId")
	c.Flags().StringVar(&arg_ordererId, "ordererId", "", "[PATH] Orderer 아이디 Orderer 목록 조회 참조")
	_ = c.MarkFlagRequired("ordererId")
	return c
}

func buildBlockchainViewOrdererList() *cobra.Command {
	var arg_networkId string
	var p_Page string
	var p_Size string
	c := &cobra.Command{
		Use: "view-orderer-list",
		Short: "Orderer 목록 조회",
		Long: "VPC 환경에서 이용 가능합니다.",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := blockchain.NewFromConfig(cfg)
			if err != nil { return err }
			pa_networkId := mustAtoi64(arg_networkId)
			params := &blockchain.ViewOrdererListParams{}
			if c.Flags().Changed("page") {
				v := mustAtoi(p_Page)
				local := v
				params.Page = &local
			}
			if c.Flags().Changed("size") {
				v := mustAtoi(p_Size)
				local := v
				params.Size = &local
			}
			resp, err := client.ViewOrdererListWithResponse(c.Context(), pa_networkId, params)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&arg_networkId, "networkId", "", "[PATH] 네트워크 아이디 Network 목록 조회 참조")
	_ = c.MarkFlagRequired("networkId")
	c.Flags().StringVar(&p_Page, "page", "", "페이지 번호 0 (기본값)")
	c.Flags().StringVar(&p_Size, "size", "", "조회 결과 목록 크기 20 (기본값)")
	return c
}

func buildBlockchainViewOrdererPodsLog() *cobra.Command {
	var arg_networkId string
	var arg_ordererId string
	var arg_containerNo string
	var p_TailLines string
	c := &cobra.Command{
		Use: "view-orderer-pods-log",
		Short: "Orderer Pod 로그 조회",
		Long: "VPC 환경에서 이용 가능합니다.",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := blockchain.NewFromConfig(cfg)
			if err != nil { return err }
			pa_networkId := mustAtoi64(arg_networkId)
			pa_containerNo := mustAtoi64(arg_containerNo)
			params := &blockchain.ViewOrdererPodsLogParams{}
			if c.Flags().Changed("tailLines") {
				v := mustAtoi(p_TailLines)
				local := v
				params.TailLines = &local
			}
			resp, err := client.ViewOrdererPodsLogWithResponse(c.Context(), pa_networkId, arg_ordererId, pa_containerNo, params)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&arg_networkId, "networkId", "", "[PATH] 네트워크 아이디 Network 목록 조회 참조")
	_ = c.MarkFlagRequired("networkId")
	c.Flags().StringVar(&arg_ordererId, "ordererId", "", "[PATH] Orderer 아이디 Orderer 목록 조회 를 통해 확인")
	_ = c.MarkFlagRequired("ordererId")
	c.Flags().StringVar(&arg_containerNo, "containerNo", "", "[PATH] Ncloud Kubernetes Service 컨테이너 번호 Orderer의 구성 타입에 따라 분류 1 ~ 5 1 : RAFT_1 (단일 노드) 1 ~ 5 : RAFT_5 (다중 노드)")
	_ = c.MarkFlagRequired("containerNo")
	c.Flags().StringVar(&p_TailLines, "tailLines", "", "로그의 라인 수 1,000~99,000 1,000 (기본값)")
	return c
}

func buildBlockchainViewOrdererPodsUsage() *cobra.Command {
	var arg_networkId string
	var arg_ordererId string
	var arg_containerNo string
	var p_StartTime string
	var p_EndTime string
	c := &cobra.Command{
		Use: "view-orderer-pods-usage",
		Short: "Orderer Pod 사용량 조회",
		Long: "VPC 환경에서 이용 가능합니다.",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := blockchain.NewFromConfig(cfg)
			if err != nil { return err }
			pa_networkId := mustAtoi64(arg_networkId)
			pa_containerNo := mustAtoi64(arg_containerNo)
			params := &blockchain.ViewOrdererPodsUsageParams{}
			if c.Flags().Changed("startTime") {
				v := mustAtoi(p_StartTime)
				params.StartTime = v
			}
			if c.Flags().Changed("endTime") {
				v := mustAtoi(p_EndTime)
				params.EndTime = v
			}
			resp, err := client.ViewOrdererPodsUsageWithResponse(c.Context(), pa_networkId, arg_ordererId, pa_containerNo, params)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&arg_networkId, "networkId", "", "[PATH] 네트워크 아이디 Network 목록 조회 참조")
	_ = c.MarkFlagRequired("networkId")
	c.Flags().StringVar(&arg_ordererId, "ordererId", "", "[PATH] Orderer 아이디 Orderer 목록 조회 참조")
	_ = c.MarkFlagRequired("ordererId")
	c.Flags().StringVar(&arg_containerNo, "containerNo", "", "[PATH] Ncloud Kubernetes Service 컨테이너 번호 Orderer의 구성 타입에 따라 분류 1 ~ 5 1 : RAFT_1 (단일 노드) 1 ~ 5 : RAFT_5 (다중 노드)")
	_ = c.MarkFlagRequired("containerNo")
	c.Flags().StringVar(&p_StartTime, "startTime", "", "사용량 조회 시작 시각 Unix Timestamp 형식 <예시> 2024년 07월 30일 09시 00분 00초인 경우 startTime=1722297600000")
	c.Flags().StringVar(&p_EndTime, "endTime", "", "사용량 조회 종료 시각 Unix Timestamp 형식 <예시> 2024년 07월 30일 15시 00분 00초인 경우 endTime=1722319200000")
	return c
}

func buildBlockchainViewOrganizationDetailS() *cobra.Command {
	var arg_networkId string
	var arg_mspId string
	c := &cobra.Command{
		Use: "view-organization-detail-s",
		Short: "Organization 정보 조회",
		Long: "VPC 환경에서 이용 가능합니다.",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := blockchain.NewFromConfig(cfg)
			if err != nil { return err }
			pa_networkId := mustAtoi64(arg_networkId)
			resp, err := client.ViewOrganizationDetailSWithResponse(c.Context(), pa_networkId, arg_mspId)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&arg_networkId, "networkId", "", "[PATH] 네트워크 아이디 Network 목록 조회 참조")
	_ = c.MarkFlagRequired("networkId")
	c.Flags().StringVar(&arg_mspId, "mspId", "", "[PATH] Organization MSP 아이디 Organization 목록 조회 참조")
	_ = c.MarkFlagRequired("mspId")
	return c
}

func buildBlockchainViewOrganizationList() *cobra.Command {
	var arg_networkId string
	var p_Page string
	var p_Size string
	c := &cobra.Command{
		Use: "view-organization-list",
		Short: "Organization 목록 조회",
		Long: "VPC 환경에서 이용 가능합니다.",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := blockchain.NewFromConfig(cfg)
			if err != nil { return err }
			pa_networkId := mustAtoi64(arg_networkId)
			params := &blockchain.ViewOrganizationListParams{}
			if c.Flags().Changed("page") {
				v := mustAtoi(p_Page)
				local := v
				params.Page = &local
			}
			if c.Flags().Changed("size") {
				v := mustAtoi(p_Size)
				local := v
				params.Size = &local
			}
			resp, err := client.ViewOrganizationListWithResponse(c.Context(), pa_networkId, params)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&arg_networkId, "networkId", "", "[PATH] 네트워크 아이디 Network 목록 조회 참조")
	_ = c.MarkFlagRequired("networkId")
	c.Flags().StringVar(&p_Page, "page", "", "페이지 번호 0 (기본값)")
	c.Flags().StringVar(&p_Size, "size", "", "조회 결과 목록 크기 20 (기본값)")
	return c
}

func buildBlockchainViewPeerDetailS() *cobra.Command {
	var arg_networkId string
	var arg_peerId string
	c := &cobra.Command{
		Use: "view-peer-detail-s",
		Short: "Peer 정보 조회",
		Long: "VPC 환경에서 이용 가능합니다.",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := blockchain.NewFromConfig(cfg)
			if err != nil { return err }
			pa_networkId := mustAtoi64(arg_networkId)
			pa_peerId := mustAtoi64(arg_peerId)
			resp, err := client.ViewPeerDetailSWithResponse(c.Context(), pa_networkId, pa_peerId)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&arg_networkId, "networkId", "", "[PATH] 네트워크 아이디 Network 목록 조회 참조")
	_ = c.MarkFlagRequired("networkId")
	c.Flags().StringVar(&arg_peerId, "peerId", "", "[PATH] Peer 아이디 Peer 목록 조회 참조")
	_ = c.MarkFlagRequired("peerId")
	return c
}

func buildBlockchainViewPeerList() *cobra.Command {
	var arg_networkId string
	var p_Page string
	var p_Size string
	c := &cobra.Command{
		Use: "view-peer-list",
		Short: "Peer 목록 조회",
		Long: "VPC 환경에서 이용 가능합니다.",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := blockchain.NewFromConfig(cfg)
			if err != nil { return err }
			pa_networkId := mustAtoi64(arg_networkId)
			params := &blockchain.ViewPeerListParams{}
			if c.Flags().Changed("page") {
				v := mustAtoi(p_Page)
				local := v
				params.Page = &local
			}
			if c.Flags().Changed("size") {
				v := mustAtoi(p_Size)
				local := v
				params.Size = &local
			}
			resp, err := client.ViewPeerListWithResponse(c.Context(), pa_networkId, params)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&arg_networkId, "networkId", "", "[PATH] 네트워크 아이디 Network 목록 조회 참고")
	_ = c.MarkFlagRequired("networkId")
	c.Flags().StringVar(&p_Page, "page", "", "페이지 번호 0 (기본값)")
	c.Flags().StringVar(&p_Size, "size", "", "조회 결과 목록 크기 20 (기본값)")
	return c
}

func buildBlockchainViewPeerPodsLog() *cobra.Command {
	var arg_networkId string
	var arg_peerId string
	var p_TailLines string
	c := &cobra.Command{
		Use: "view-peer-pods-log",
		Short: "Peer Pod 로그 조회",
		Long: "VPC 환경에서 이용 가능합니다.",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := blockchain.NewFromConfig(cfg)
			if err != nil { return err }
			pa_networkId := mustAtoi64(arg_networkId)
			pa_peerId := mustAtoi64(arg_peerId)
			params := &blockchain.ViewPeerPodsLogParams{}
			if c.Flags().Changed("tailLines") {
				v := mustAtoi(p_TailLines)
				local := v
				params.TailLines = &local
			}
			resp, err := client.ViewPeerPodsLogWithResponse(c.Context(), pa_networkId, pa_peerId, params)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&arg_networkId, "networkId", "", "[PATH] 네트워크 아이디 Network 목록 조회 참조")
	_ = c.MarkFlagRequired("networkId")
	c.Flags().StringVar(&arg_peerId, "peerId", "", "[PATH] Peer 아이디 Peer 목록 조회 참조")
	_ = c.MarkFlagRequired("peerId")
	c.Flags().StringVar(&p_TailLines, "tailLines", "", "로그의 라인 수 1,000~99,000 1,000 (기본값)")
	return c
}

func buildBlockchainViewPeerPodsUsage() *cobra.Command {
	var arg_networkId string
	var arg_peerId string
	var p_StartTime string
	var p_EndTime string
	var p_IsCouchDb string
	c := &cobra.Command{
		Use: "view-peer-pods-usage",
		Short: "Peer Pod 사용량 조회",
		Long: "VPC 환경에서 이용 가능합니다.",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := blockchain.NewFromConfig(cfg)
			if err != nil { return err }
			pa_networkId := mustAtoi64(arg_networkId)
			pa_peerId := mustAtoi64(arg_peerId)
			params := &blockchain.ViewPeerPodsUsageParams{}
			if c.Flags().Changed("startTime") {
				v := mustAtoi(p_StartTime)
				params.StartTime = v
			}
			if c.Flags().Changed("endTime") {
				v := mustAtoi(p_EndTime)
				params.EndTime = v
			}
			if c.Flags().Changed("isCouchDb") {
				v := mustParseBool(p_IsCouchDb)
				local := v
				params.IsCouchDb = &local
			}
			resp, err := client.ViewPeerPodsUsageWithResponse(c.Context(), pa_networkId, pa_peerId, params)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&arg_networkId, "networkId", "", "[PATH] 네트워크 아이디 Network 목록 조회 참조")
	_ = c.MarkFlagRequired("networkId")
	c.Flags().StringVar(&arg_peerId, "peerId", "", "[PATH] Peer 아이디 Peer 목록 조회 참조")
	_ = c.MarkFlagRequired("peerId")
	c.Flags().StringVar(&p_StartTime, "startTime", "", "사용량 조회 시작 시각 Unix Timestamp 형식 <예시> 2024년 07월 30일 09시 00분 00초인 경우 startTime=1722297600000")
	c.Flags().StringVar(&p_EndTime, "endTime", "", "사용량 조회 종료 시각 Unix Timestamp 형식 <예시> 2024년 07월 30일 15시 00분 00초인 경우 endTime=1722319200000")
	c.Flags().StringVar(&p_IsCouchDb, "isCouchDb", "", "CouchDB 여부 true | false true : CoucbDB일 경우 false : CouchDB가 아닐 경우(LevelDB)")
	return c
}
