// Code generated by tools/build_cli_typed.py. DO NOT EDIT.

package services

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"

	clicmd "github.com/greedylabs/ncloud-community-sdk/cli/cmd"
	ncloud "github.com/greedylabs/ncloud-community-sdk/sdk"
	cloud_activity_tracer "github.com/greedylabs/ncloud-community-sdk/sdk/services/cloud_activity_tracer"
)

var _ = bytes.NewBuffer
var _ = json.Unmarshal
var _ = fmt.Sprintf
var _ io.Reader = nil
var _ = os.Open
var _ = ncloud.AsAPIError

func init() {
	parent := &cobra.Command{ Use: "cloud-activity-tracer", Short: "cloud-activity-tracer" }
	parent.AddCommand(buildCloudActivityTracerGetActivityList())
	clicmd.RegisterServiceCmd(parent)
}

func buildCloudActivityTracerGetActivityList() *cobra.Command {
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "get-activity-list",
		Short: "활동 이력 조회",
		Long: "지정된 기간의 계정 활동 이력을 페이지 단위로 조회합니다.",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := cloud_activity_tracer.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.GetActivityListWithBodyWithResponse(c.Context(), "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}
