// Code generated by tools/build_cli_typed.py. DO NOT EDIT.

package services

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"

	clicmd "github.com/greedylabs/ncloud-community-sdk/cli/cmd"
	ncloud "github.com/greedylabs/ncloud-community-sdk/sdk"
	global_traffic_manager "github.com/greedylabs/ncloud-community-sdk/sdk/services/global_traffic_manager"
)

var _ = bytes.NewBuffer
var _ = json.Unmarshal
var _ = fmt.Sprintf
var _ io.Reader = nil
var _ = os.Open
var _ = ncloud.AsAPIError

func init() {
	parent := &cobra.Command{ Use: "global-traffic-manager", Short: "global-traffic-manager" }
	parent.AddCommand(buildGlobalTrafficManagerCreat())
	parent.AddCommand(buildGlobalTrafficManagerDelete())
	parent.AddCommand(buildGlobalTrafficManagerDetailView())
	parent.AddCommand(buildGlobalTrafficManagerEdit())
	parent.AddCommand(buildGlobalTrafficManagerView())
	clicmd.RegisterServiceCmd(parent)
}

func buildGlobalTrafficManagerCreat() *cobra.Command {
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "creat",
		Short: "Traffic Profile 생성",
		Long: "Classic/VPC 환경에서 이용 가능합니다.",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := global_traffic_manager.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.CreatWithBodyWithResponse(c.Context(), "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}

func buildGlobalTrafficManagerDelete() *cobra.Command {
	var arg_domainId string
	c := &cobra.Command{
		Use: "delete",
		Short: "Traffic Profile 삭제",
		Long: "Classic/VPC 환경에서 이용 가능합니다.",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := global_traffic_manager.NewFromConfig(cfg)
			if err != nil { return err }
			pa_domainId := mustAtoi(arg_domainId)
			resp, err := client.DeleteWithResponse(c.Context(), pa_domainId)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&arg_domainId, "domainId", "", "[PATH] Profile ID Profile 조회 참조")
	_ = c.MarkFlagRequired("domainId")
	return c
}

func buildGlobalTrafficManagerDetailView() *cobra.Command {
	var arg_domainId string
	c := &cobra.Command{
		Use: "detail-view",
		Short: "Traffic Profile 상세 조회",
		Long: "Classic/VPC 환경에서 이용 가능합니다.",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := global_traffic_manager.NewFromConfig(cfg)
			if err != nil { return err }
			pa_domainId := mustAtoi(arg_domainId)
			resp, err := client.DetailViewWithResponse(c.Context(), pa_domainId)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&arg_domainId, "domainId", "", "[PATH] Profile ID Profile 조회 참조")
	_ = c.MarkFlagRequired("domainId")
	return c
}

func buildGlobalTrafficManagerEdit() *cobra.Command {
	var arg_domainId string
	c := &cobra.Command{
		Use: "edit",
		Short: "Traffic Profile 수정",
		Long: "Classic/VPC 환경에서 이용 가능합니다.",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := global_traffic_manager.NewFromConfig(cfg)
			if err != nil { return err }
			pa_domainId := mustAtoi(arg_domainId)
			resp, err := client.EditWithResponse(c.Context(), pa_domainId)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&arg_domainId, "domainId", "", "[PATH] Profile ID Profile 조회 참조")
	_ = c.MarkFlagRequired("domainId")
	return c
}

func buildGlobalTrafficManagerView() *cobra.Command {
	var p_Page string
	var p_Size string
	var p_Name string
	c := &cobra.Command{
		Use: "view",
		Short: "Traffic Profile 조회",
		Long: "Classic/VPC 환경에서 이용 가능합니다.",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := global_traffic_manager.NewFromConfig(cfg)
			if err != nil { return err }
			params := &global_traffic_manager.ViewParams{}
			if c.Flags().Changed("page") {
				v := mustAtoi(p_Page)
				local := v
				params.Page = &local
			}
			if c.Flags().Changed("size") {
				v := mustAtoi(p_Size)
				local := v
				params.Size = &local
			}
			if c.Flags().Changed("name") {
				local := p_Name
				params.Name = &local
			}
			resp, err := client.ViewWithResponse(c.Context(), params)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&p_Page, "page", "", "페이징된 결과의 페이지 번호 0 (기본값)")
	c.Flags().StringVar(&p_Size, "size", "", "한 페이지에 보여줄 결과 개수 20 (기본값)")
	c.Flags().StringVar(&p_Name, "name", "", "Profile 이름")
	return c
}
