// Code generated by tools/build_cli_typed.py. DO NOT EDIT.

package services

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"

	clicmd "github.com/greedylabs/ncloud-community-sdk/cli/cmd"
	ncloud "github.com/greedylabs/ncloud-community-sdk/sdk"
	load_balancer "github.com/greedylabs/ncloud-community-sdk/sdk/services/load_balancer"
)

var _ = bytes.NewBuffer
var _ = json.Unmarshal
var _ = fmt.Sprintf
var _ io.Reader = nil
var _ = os.Open
var _ = ncloud.AsAPIError

func init() {
	parent := &cobra.Command{ Use: "load-balancer", Short: "load-balancer" }
	parent.AddCommand(buildLoadBalancerAddLoadBalancerListenerCertificate())
	parent.AddCommand(buildLoadBalancerAddTarget())
	parent.AddCommand(buildLoadBalancerChangeLoadBalancerInstanceConfiguration())
	parent.AddCommand(buildLoadBalancerChangeLoadBalancerListenerConfiguration())
	parent.AddCommand(buildLoadBalancerChangeTargetGroupConfiguration())
	parent.AddCommand(buildLoadBalancerChangeTargetGroupHealthCheckConfiguration())
	parent.AddCommand(buildLoadBalancerCreateLoadBalancerInstance())
	parent.AddCommand(buildLoadBalancerCreateLoadBalancerListener())
	parent.AddCommand(buildLoadBalancerCreateTargetGroup())
	parent.AddCommand(buildLoadBalancerDeleteLoadBalancerInstances())
	parent.AddCommand(buildLoadBalancerDeleteLoadBalancerListeners())
	parent.AddCommand(buildLoadBalancerDeleteTargetGroups())
	parent.AddCommand(buildLoadBalancerGetLoadBalancerInstanceDetail())
	parent.AddCommand(buildLoadBalancerGetLoadBalancerInstanceList())
	parent.AddCommand(buildLoadBalancerGetLoadBalancerListenerCertificateList())
	parent.AddCommand(buildLoadBalancerGetLoadBalancerListenerList())
	parent.AddCommand(buildLoadBalancerGetLoadBalancerRuleList())
	parent.AddCommand(buildLoadBalancerGetTargetGroupDetail())
	parent.AddCommand(buildLoadBalancerGetTargetGroupList())
	parent.AddCommand(buildLoadBalancerGetTargetList())
	parent.AddCommand(buildLoadBalancerRemoveLoadBalancerListenerCertificate())
	parent.AddCommand(buildLoadBalancerRemoveTarget())
	parent.AddCommand(buildLoadBalancerSetLoadBalancerDescription())
	parent.AddCommand(buildLoadBalancerSetLoadBalancerInstanceSubnet())
	parent.AddCommand(buildLoadBalancerSetTarget())
	parent.AddCommand(buildLoadBalancerSetTargetGroupDescription())
	clicmd.RegisterServiceCmd(parent)
}

func buildLoadBalancerAddLoadBalancerListenerCertificate() *cobra.Command {
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "add-load-balancer-listener-certificate",
		Short: "로드밸런서리스너인증서추가",
		Long: "",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := load_balancer.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.AddLoadBalancerListenerCertificateWithBodyWithResponse(c.Context(), "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}

func buildLoadBalancerAddTarget() *cobra.Command {
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "add-target",
		Short: "Add target",
		Long: "",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := load_balancer.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.AddTargetWithBodyWithResponse(c.Context(), "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}

func buildLoadBalancerChangeLoadBalancerInstanceConfiguration() *cobra.Command {
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "change-load-balancer-instance-configuration",
		Short: "로드 밸런서 인스턴스의 설정을 변경합니다.",
		Long: "",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := load_balancer.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.ChangeLoadBalancerInstanceConfigurationWithBodyWithResponse(c.Context(), "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}

func buildLoadBalancerChangeLoadBalancerListenerConfiguration() *cobra.Command {
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "change-load-balancer-listener-configuration",
		Short: "로드 밸런서 리스너의 설정을 변경합니다.",
		Long: "",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := load_balancer.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.ChangeLoadBalancerListenerConfigurationWithBodyWithResponse(c.Context(), "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}

func buildLoadBalancerChangeTargetGroupConfiguration() *cobra.Command {
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "change-target-group-configuration",
		Short: "Change target group configuration",
		Long: "",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := load_balancer.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.ChangeTargetGroupConfigurationWithBodyWithResponse(c.Context(), "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}

func buildLoadBalancerChangeTargetGroupHealthCheckConfiguration() *cobra.Command {
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "change-target-group-health-check-configuration",
		Short: "Change target group health check configuration",
		Long: "",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := load_balancer.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.ChangeTargetGroupHealthCheckConfigurationWithBodyWithResponse(c.Context(), "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}

func buildLoadBalancerCreateLoadBalancerInstance() *cobra.Command {
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "create-load-balancer-instance",
		Short: "로드 밸런서 인스턴스를 생성합니다.",
		Long: "",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := load_balancer.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.CreateLoadBalancerInstanceWithBodyWithResponse(c.Context(), "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}

func buildLoadBalancerCreateLoadBalancerListener() *cobra.Command {
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "create-load-balancer-listener",
		Short: "로드 밸런서에 등록할 새로운 리스너를 생성합니다.",
		Long: "",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := load_balancer.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.CreateLoadBalancerListenerWithBodyWithResponse(c.Context(), "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}

func buildLoadBalancerCreateTargetGroup() *cobra.Command {
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "create-target-group",
		Short: "Create target group",
		Long: "",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := load_balancer.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.CreateTargetGroupWithBodyWithResponse(c.Context(), "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}

func buildLoadBalancerDeleteLoadBalancerInstances() *cobra.Command {
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "delete-load-balancer-instances",
		Short: "로드 밸런서 인스턴스를 삭제합니다.",
		Long: "",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := load_balancer.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.DeleteLoadBalancerInstancesWithBodyWithResponse(c.Context(), "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}

func buildLoadBalancerDeleteLoadBalancerListeners() *cobra.Command {
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "delete-load-balancer-listeners",
		Short: "로드 밸런서에 등록된 리스너를 삭제합니다. 삭제 후에도 로드 밸런서에 리스너가 최소 한 개 이상 존재해야 합니다.",
		Long: "",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := load_balancer.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.DeleteLoadBalancerListenersWithBodyWithResponse(c.Context(), "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}

func buildLoadBalancerDeleteTargetGroups() *cobra.Command {
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "delete-target-groups",
		Short: "Delete target groups",
		Long: "",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := load_balancer.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.DeleteTargetGroupsWithBodyWithResponse(c.Context(), "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}

func buildLoadBalancerGetLoadBalancerInstanceDetail() *cobra.Command {
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "get-load-balancer-instance-detail",
		Short: "로드 밸런서 인스턴스의 번호를 이용하여 상세 정보를 조회합니다.",
		Long: "",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := load_balancer.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.GetLoadBalancerInstanceDetailWithBodyWithResponse(c.Context(), "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}

func buildLoadBalancerGetLoadBalancerInstanceList() *cobra.Command {
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "get-load-balancer-instance-list",
		Short: "사용자가 지정한 조건에 따라 로드 밸런서 인스턴스의 목록을 조회합니다.",
		Long: "",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := load_balancer.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.GetLoadBalancerInstanceListWithBodyWithResponse(c.Context(), "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}

func buildLoadBalancerGetLoadBalancerListenerCertificateList() *cobra.Command {
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "get-load-balancer-listener-certificate-list",
		Short: "로드밸런서리스너인증서조회",
		Long: "",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := load_balancer.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.GetLoadBalancerListenerCertificateListWithBodyWithResponse(c.Context(), "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}

func buildLoadBalancerGetLoadBalancerListenerList() *cobra.Command {
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "get-load-balancer-listener-list",
		Short: "로드 밸런서에 등록된 리스너 목록을 조회합니다.",
		Long: "",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := load_balancer.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.GetLoadBalancerListenerListWithBodyWithResponse(c.Context(), "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}

func buildLoadBalancerGetLoadBalancerRuleList() *cobra.Command {
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "get-load-balancer-rule-list",
		Short: "로드 밸런서 리스너에 등록된 규칙 목록을 조회합니다.",
		Long: "",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := load_balancer.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.GetLoadBalancerRuleListWithBodyWithResponse(c.Context(), "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}

func buildLoadBalancerGetTargetGroupDetail() *cobra.Command {
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "get-target-group-detail",
		Short: "Get target group detail",
		Long: "",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := load_balancer.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.GetTargetGroupDetailWithBodyWithResponse(c.Context(), "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}

func buildLoadBalancerGetTargetGroupList() *cobra.Command {
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "get-target-group-list",
		Short: "Get target group list",
		Long: "",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := load_balancer.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.GetTargetGroupListWithBodyWithResponse(c.Context(), "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}

func buildLoadBalancerGetTargetList() *cobra.Command {
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "get-target-list",
		Short: "Get target list",
		Long: "",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := load_balancer.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.GetTargetListWithBodyWithResponse(c.Context(), "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}

func buildLoadBalancerRemoveLoadBalancerListenerCertificate() *cobra.Command {
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "remove-load-balancer-listener-certificate",
		Short: "로드밸런서리스너인증서제거",
		Long: "",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := load_balancer.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.RemoveLoadBalancerListenerCertificateWithBodyWithResponse(c.Context(), "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}

func buildLoadBalancerRemoveTarget() *cobra.Command {
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "remove-target",
		Short: "Remove target",
		Long: "",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := load_balancer.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.RemoveTargetWithBodyWithResponse(c.Context(), "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}

func buildLoadBalancerSetLoadBalancerDescription() *cobra.Command {
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "set-load-balancer-description",
		Short: "로드 밸런서의 설명을 수정합니다.",
		Long: "",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := load_balancer.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.SetLoadBalancerDescriptionWithBodyWithResponse(c.Context(), "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}

func buildLoadBalancerSetLoadBalancerInstanceSubnet() *cobra.Command {
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "set-load-balancer-instance-subnet",
		Short: "로드 밸런서의 서브넷을 설정합니다. 기존에 설정된 서브넷을 포함하여 설정하며, 기존 서브넷과 다른 존에 위치한 서브넷을 추가할 수 있습니다.",
		Long: "",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := load_balancer.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.SetLoadBalancerInstanceSubnetWithBodyWithResponse(c.Context(), "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}

func buildLoadBalancerSetTarget() *cobra.Command {
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "set-target",
		Short: "Set target",
		Long: "",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := load_balancer.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.SetTargetWithBodyWithResponse(c.Context(), "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}

func buildLoadBalancerSetTargetGroupDescription() *cobra.Command {
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "set-target-group-description",
		Short: "Set target group description",
		Long: "",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := load_balancer.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.SetTargetGroupDescriptionWithBodyWithResponse(c.Context(), "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}
