// Code generated by tools/build_cli_typed.py. DO NOT EDIT.

package services

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"

	clicmd "github.com/greedylabs/ncloud-community-sdk/cli/cmd"
	ncloud "github.com/greedylabs/ncloud-community-sdk/sdk"
	postgresql "github.com/greedylabs/ncloud-community-sdk/sdk/services/postgresql"
)

var _ = bytes.NewBuffer
var _ = json.Unmarshal
var _ = fmt.Sprintf
var _ io.Reader = nil
var _ = os.Open
var _ = ncloud.AsAPIError

func init() {
	parent := &cobra.Command{ Use: "postgresql", Short: "postgresql" }
	parent.AddCommand(buildPostgresqlAddCloudPostgresqlDatabaseList())
	parent.AddCommand(buildPostgresqlAddCloudPostgresqlUserList())
	parent.AddCommand(buildPostgresqlChangeCloudPostgresqlUserList())
	parent.AddCommand(buildPostgresqlCreateCloudPostgresqlInstance())
	parent.AddCommand(buildPostgresqlCreateCloudPostgresqlReadReplicaInstance())
	parent.AddCommand(buildPostgresqlDeleteCloudPostgresqlDatabaseList())
	parent.AddCommand(buildPostgresqlDeleteCloudPostgresqlInstance())
	parent.AddCommand(buildPostgresqlDeleteCloudPostgresqlReadReplicaInstance())
	parent.AddCommand(buildPostgresqlDeleteCloudPostgresqlUserList())
	parent.AddCommand(buildPostgresqlExportBackupToObjectStorage())
	parent.AddCommand(buildPostgresqlExportDbServerLogToObjectStorage())
	parent.AddCommand(buildPostgresqlGetCloudPostgresqlBackupDetailList())
	parent.AddCommand(buildPostgresqlGetCloudPostgresqlBackupList())
	parent.AddCommand(buildPostgresqlGetCloudPostgresqlBucketList())
	parent.AddCommand(buildPostgresqlGetCloudPostgresqlDatabaseList())
	parent.AddCommand(buildPostgresqlGetCloudPostgresqlImageProductList())
	parent.AddCommand(buildPostgresqlGetCloudPostgresqlInstanceDetail())
	parent.AddCommand(buildPostgresqlGetCloudPostgresqlInstanceList())
	parent.AddCommand(buildPostgresqlGetCloudPostgresqlProductList())
	parent.AddCommand(buildPostgresqlGetCloudPostgresqlTargetSubnetList())
	parent.AddCommand(buildPostgresqlGetCloudPostgresqlTargetVpcList())
	parent.AddCommand(buildPostgresqlGetCloudPostgresqlUserList())
	parent.AddCommand(buildPostgresqlGetDbServerLogList())
	parent.AddCommand(buildPostgresqlRebootCloudPostgresqlServerInstance())
	clicmd.RegisterServiceCmd(parent)
}

func buildPostgresqlAddCloudPostgresqlDatabaseList() *cobra.Command {
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "add-cloud-postgresql-database-list",
		Short: "Cloud DB for PostgreSQL 인스턴스에 Database를 추가합니다.",
		Long: "",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := postgresql.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.AddCloudPostgresqlDatabaseListWithBodyWithResponse(c.Context(), "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}

func buildPostgresqlAddCloudPostgresqlUserList() *cobra.Command {
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "add-cloud-postgresql-user-list",
		Short: "Cloud DB for PostgreSQL 인스턴스에 DB User를 추가합니다.",
		Long: "",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := postgresql.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.AddCloudPostgresqlUserListWithBodyWithResponse(c.Context(), "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}

func buildPostgresqlChangeCloudPostgresqlUserList() *cobra.Command {
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "change-cloud-postgresql-user-list",
		Short: "Cloud DB for PostgreSQL 인스턴스에 등록된 DB User의 정보를 수정합니다.",
		Long: "",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := postgresql.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.ChangeCloudPostgresqlUserListWithBodyWithResponse(c.Context(), "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}

func buildPostgresqlCreateCloudPostgresqlInstance() *cobra.Command {
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "create-cloud-postgresql-instance",
		Short: "Cloud DB for PostgreSQL 인스턴스를 생성합니다.",
		Long: "",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := postgresql.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.CreateCloudPostgresqlInstanceWithBodyWithResponse(c.Context(), "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}

func buildPostgresqlCreateCloudPostgresqlReadReplicaInstance() *cobra.Command {
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "create-cloud-postgresql-read-replica-instance",
		Short: "Create cloud postgre sql read replica instance",
		Long: "",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := postgresql.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.CreateCloudPostgresqlReadReplicaInstanceWithBodyWithResponse(c.Context(), "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}

func buildPostgresqlDeleteCloudPostgresqlDatabaseList() *cobra.Command {
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "delete-cloud-postgresql-database-list",
		Short: "Cloud DB for PostgreSQL 인스턴스의 Database를 삭제합니다.",
		Long: "",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := postgresql.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.DeleteCloudPostgresqlDatabaseListWithBodyWithResponse(c.Context(), "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}

func buildPostgresqlDeleteCloudPostgresqlInstance() *cobra.Command {
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "delete-cloud-postgresql-instance",
		Short: "가이드는 GET 방식 기준으로 안내합니다. POST 방식의 호출 테스트는 네이버 클라우드 플랫폼 콘솔의 API Gateway 서비스에서 Swagger를 통해서 가능합니다.",
		Long: "",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := postgresql.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.DeleteCloudPostgresqlInstanceWithBodyWithResponse(c.Context(), "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}

func buildPostgresqlDeleteCloudPostgresqlReadReplicaInstance() *cobra.Command {
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "delete-cloud-postgresql-read-replica-instance",
		Short: "Cloud DB for PostgreSQL Read Replica 서버 인스턴스를 삭제합니다.",
		Long: "",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := postgresql.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.DeleteCloudPostgresqlReadReplicaInstanceWithBodyWithResponse(c.Context(), "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}

func buildPostgresqlDeleteCloudPostgresqlUserList() *cobra.Command {
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "delete-cloud-postgresql-user-list",
		Short: "가이드는 GET 방식 기준으로 안내합니다. POST 방식의 호출 테스트는 네이버 클라우드 플랫폼 콘솔의 API Gateway 서비스에서 Swagger를 통해서 가능합니다.",
		Long: "",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := postgresql.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.DeleteCloudPostgresqlUserListWithBodyWithResponse(c.Context(), "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}

func buildPostgresqlExportBackupToObjectStorage() *cobra.Command {
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "export-backup-to-object-storage",
		Short: "Cloud DB for PostgreSQL 인스턴스의 백업 파일을 Object Storage로 전송합니다.",
		Long: "백업 파일을 Object Storage로 전송하기 전에 백업 파일을 저장하고, 검색하기 위한 Object Storage 버킷이 생성되어 있어야 합니다. 자세한 내용은 Object Storage 가이드를 참조해 주십시오.",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := postgresql.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.ExportBackupToObjectStorageWithBodyWithResponse(c.Context(), "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}

func buildPostgresqlExportDbServerLogToObjectStorage() *cobra.Command {
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "export-db-server-log-to-object-storage",
		Short: "Cloud DB for PostgreSQL 인스턴스의 DB Server 로그 파일을 Object Storage로 전송합니다.",
		Long: "DB Server 로그 파일을 Object Storage로 전송하기 전에 DB Server 로그 파일을 저장하고, 검색하기 위한 Object Storage 버킷이 생성되어 있어야 합니다. 자세한 내용은 Object Storage 가이드를 참조해 주십시오.",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := postgresql.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.ExportDbServerLogToObjectStorageWithBodyWithResponse(c.Context(), "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}

func buildPostgresqlGetCloudPostgresqlBackupDetailList() *cobra.Command {
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "get-cloud-postgresql-backup-detail-list",
		Short: "Cloud DB for PostgreSQL 인스턴스의 백업 상세 정보를 목록으로 조회합니다.",
		Long: "",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := postgresql.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.GetCloudPostgresqlBackupDetailListWithBodyWithResponse(c.Context(), "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}

func buildPostgresqlGetCloudPostgresqlBackupList() *cobra.Command {
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "get-cloud-postgresql-backup-list",
		Short: "Cloud DB for PostgreSQL 인스턴스의 백업 목록을 조회합니다.",
		Long: "",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := postgresql.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.GetCloudPostgresqlBackupListWithBodyWithResponse(c.Context(), "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}

func buildPostgresqlGetCloudPostgresqlBucketList() *cobra.Command {
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "get-cloud-postgresql-bucket-list",
		Short: "가이드는 GET 방식 기준으로 안내합니다. POST 방식의 호출 테스트는 네이버 클라우드 플랫폼 콘솔의 API Gateway 서비스에서 Swagger를 통해서 가능합니다.",
		Long: "",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := postgresql.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.GetCloudPostgresqlBucketListWithBodyWithResponse(c.Context(), "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}

func buildPostgresqlGetCloudPostgresqlDatabaseList() *cobra.Command {
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "get-cloud-postgresql-database-list",
		Short: "Cloud DB for PostgreSQL 인스턴스의 Database 목록을 조회합니다.",
		Long: "",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := postgresql.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.GetCloudPostgresqlDatabaseListWithBodyWithResponse(c.Context(), "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}

func buildPostgresqlGetCloudPostgresqlImageProductList() *cobra.Command {
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "get-cloud-postgresql-image-product-list",
		Short: "Cloud DB for PostgreSQL 이미지 상품 코드 리스트를 조회합니다.",
		Long: "",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := postgresql.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.GetCloudPostgresqlImageProductListWithBodyWithResponse(c.Context(), "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}

func buildPostgresqlGetCloudPostgresqlInstanceDetail() *cobra.Command {
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "get-cloud-postgresql-instance-detail",
		Short: "Cloud DB for PostgreSQL 인스턴스 상세 정보를 조회합니다.",
		Long: "",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := postgresql.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.GetCloudPostgresqlInstanceDetailWithBodyWithResponse(c.Context(), "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}

func buildPostgresqlGetCloudPostgresqlInstanceList() *cobra.Command {
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "get-cloud-postgresql-instance-list",
		Short: "Cloud DB for PostgreSQL 인스턴스 리스트를 조회합니다.",
		Long: "",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := postgresql.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.GetCloudPostgresqlInstanceListWithBodyWithResponse(c.Context(), "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}

func buildPostgresqlGetCloudPostgresqlProductList() *cobra.Command {
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "get-cloud-postgresql-product-list",
		Short: "사용할 수 있는 Cloud DB for PostgreSQL 서버 스펙 코드 리스트를 조회합니다.",
		Long: "",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := postgresql.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.GetCloudPostgresqlProductListWithBodyWithResponse(c.Context(), "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}

func buildPostgresqlGetCloudPostgresqlTargetSubnetList() *cobra.Command {
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "get-cloud-postgresql-target-subnet-list",
		Short: "Cloud DB for PostgreSQL에서 사용할 수 있는 Subnet 목록을 조회합니다.",
		Long: "",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := postgresql.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.GetCloudPostgresqlTargetSubnetListWithBodyWithResponse(c.Context(), "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}

func buildPostgresqlGetCloudPostgresqlTargetVpcList() *cobra.Command {
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "get-cloud-postgresql-target-vpc-list",
		Short: "Cloud DB for PostgreSQL에서 사용할 수 있는 VPC 목록을 조회합니다.",
		Long: "",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := postgresql.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.GetCloudPostgresqlTargetVpcListWithBodyWithResponse(c.Context(), "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}

func buildPostgresqlGetCloudPostgresqlUserList() *cobra.Command {
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "get-cloud-postgresql-user-list",
		Short: "Cloud DB for PostgreSQL 인스턴스의 DB User 목록을 조회합니다.",
		Long: "",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := postgresql.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.GetCloudPostgresqlUserListWithBodyWithResponse(c.Context(), "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}

func buildPostgresqlGetDbServerLogList() *cobra.Command {
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "get-db-server-log-list",
		Short: "Cloud DB for PostgreSQL 인스턴스의 DB Server 로그 목록을 조회합니다.",
		Long: "",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := postgresql.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.GetDbServerLogListWithBodyWithResponse(c.Context(), "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}

func buildPostgresqlRebootCloudPostgresqlServerInstance() *cobra.Command {
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "reboot-cloud-postgresql-server-instance",
		Short: "Cloud DB for PostgreSQL 서버 인스턴스를 재시작합니다.",
		Long: "",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := postgresql.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.RebootCloudPostgresqlServerInstanceWithBodyWithResponse(c.Context(), "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}
