// Code generated by tools/build_cli_typed.py. DO NOT EDIT.

package services

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"

	clicmd "github.com/greedylabs/ncloud-community-sdk/cli/cmd"
	ncloud "github.com/greedylabs/ncloud-community-sdk/sdk"
	vod_station "github.com/greedylabs/ncloud-community-sdk/sdk/services/vod_station"
)

var _ = bytes.NewBuffer
var _ = json.Unmarshal
var _ = fmt.Sprintf
var _ io.Reader = nil
var _ = os.Open
var _ = ncloud.AsAPIError

func init() {
	parent := &cobra.Command{ Use: "vod-station", Short: "vod-station" }
	parent.AddCommand(buildVodStationCategoryAddFileS())
	parent.AddCommand(buildVodStationCategoryCreate())
	parent.AddCommand(buildVodStationCategoryDelete())
	parent.AddCommand(buildVodStationCategoryInfo())
	parent.AddCommand(buildVodStationCategoryList())
	parent.AddCommand(buildVodStationCategoryUpdate())
	parent.AddCommand(buildVodStationChannelCreate())
	parent.AddCommand(buildVodStationChannelDelete())
	parent.AddCommand(buildVodStationChannelEvent())
	parent.AddCommand(buildVodStationChannelInfo())
	parent.AddCommand(buildVodStationChannelList())
	parent.AddCommand(buildVodStationChannelProtocolList())
	parent.AddCommand(buildVodStationChannelStart())
	parent.AddCommand(buildVodStationChannelStop())
	parent.AddCommand(buildVodStationEnCodingOptionCreate())
	parent.AddCommand(buildVodStationEnCodingOptionDelete())
	parent.AddCommand(buildVodStationEnCodingOptionInfo())
	parent.AddCommand(buildVodStationEnCodingOptionList())
	parent.AddCommand(buildVodStationEnCodingOptionTemplateList())
	parent.AddCommand(buildVodStationStatusInfoList())
	parent.AddCommand(buildVodStationStatusList())
	parent.AddCommand(buildVodStationStatusStatistic())
	clicmd.RegisterServiceCmd(parent)
}

func buildVodStationCategoryAddFileS() *cobra.Command {
	var arg_categoryId string
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "category-add-file-s",
		Short: "카테고리 파일 추가",
		Long: "Classic/VPC 환경에서 이용 가능합니다.",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := vod_station.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.CategoryAddFileSWithBodyWithResponse(c.Context(), arg_categoryId, "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&arg_categoryId, "categoryId", "", "[PATH] 카테고리 아이디 카테고리 목록 조회 참조")
	_ = c.MarkFlagRequired("categoryId")
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}

func buildVodStationCategoryCreate() *cobra.Command {
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "category-create",
		Short: "카테고리 생성",
		Long: "Classic/VPC 환경에서 이용 가능합니다.",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := vod_station.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.CategoryCreateWithBodyWithResponse(c.Context(), "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}

func buildVodStationCategoryDelete() *cobra.Command {
	var arg_categoryId string
	c := &cobra.Command{
		Use: "category-delete",
		Short: "카테고리 삭제",
		Long: "Classic/VPC 환경에서 이용 가능합니다.",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := vod_station.NewFromConfig(cfg)
			if err != nil { return err }
			resp, err := client.CategoryDeleteWithResponse(c.Context(), arg_categoryId)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&arg_categoryId, "categoryId", "", "[PATH] 카테고리 아이디 카테고리 목록 조회 참조")
	_ = c.MarkFlagRequired("categoryId")
	return c
}

func buildVodStationCategoryInfo() *cobra.Command {
	var arg_categoryId string
	c := &cobra.Command{
		Use: "category-info",
		Short: "카테고리 조회",
		Long: "Classic/VPC 환경에서 이용 가능합니다.",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := vod_station.NewFromConfig(cfg)
			if err != nil { return err }
			resp, err := client.CategoryInfoWithResponse(c.Context(), arg_categoryId)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&arg_categoryId, "categoryId", "", "[PATH] 카테고리 아이디 카테고리 목록 조회 참조")
	_ = c.MarkFlagRequired("categoryId")
	return c
}

func buildVodStationCategoryList() *cobra.Command {
	var p_PageNo string
	var p_PageSizeNo string
	c := &cobra.Command{
		Use: "category-list",
		Short: "카테고리 목록 조회",
		Long: "Classic/VPC 환경에서 이용 가능합니다.",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := vod_station.NewFromConfig(cfg)
			if err != nil { return err }
			params := &vod_station.CategoryListParams{}
			if c.Flags().Changed("pageNo") {
				v := mustAtoi(p_PageNo)
				local := v
				params.PageNo = &local
			}
			if c.Flags().Changed("pageSizeNo") {
				v := mustAtoi(p_PageSizeNo)
				local := v
				params.PageSizeNo = &local
			}
			resp, err := client.CategoryListWithResponse(c.Context(), params)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&p_PageNo, "pageNo", "", "페이지 번호 1~N (기본값: 1)")
	c.Flags().StringVar(&p_PageSizeNo, "pageSizeNo", "", "페이지당 항목 수 1~N (기본값: 20)")
	return c
}

func buildVodStationCategoryUpdate() *cobra.Command {
	var arg_categoryId string
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "category-update",
		Short: "카테고리 수정",
		Long: "Classic/VPC 환경에서 이용 가능합니다.",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := vod_station.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.CategoryUpdateWithBodyWithResponse(c.Context(), arg_categoryId, "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&arg_categoryId, "categoryId", "", "[PATH] 카테고리 아이디 카테고리 목록 조회 참조")
	_ = c.MarkFlagRequired("categoryId")
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}

func buildVodStationChannelCreate() *cobra.Command {
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "channel-create",
		Short: "송출 영상 보안 설정",
		Long: "Classic/VPC 환경에서 이용 가능합니다.",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := vod_station.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.ChannelCreateWithBodyWithResponse(c.Context(), "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}

func buildVodStationChannelDelete() *cobra.Command {
	var arg_channelId string
	c := &cobra.Command{
		Use: "channel-delete",
		Short: "채널 삭제",
		Long: "Classic/VPC 환경에서 이용 가능합니다.",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := vod_station.NewFromConfig(cfg)
			if err != nil { return err }
			resp, err := client.ChannelDeleteWithResponse(c.Context(), arg_channelId)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&arg_channelId, "channelId", "", "[PATH] 채널 아이디 채널 목록 조회 참조")
	_ = c.MarkFlagRequired("channelId")
	return c
}

func buildVodStationChannelEvent() *cobra.Command {
	var arg_channelId string
	var p_PageNo string
	var p_PageSizeNo string
	c := &cobra.Command{
		Use: "channel-event",
		Short: "채널 이벤트 조회",
		Long: "Classic/VPC 환경에서 이용 가능합니다.",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := vod_station.NewFromConfig(cfg)
			if err != nil { return err }
			params := &vod_station.ChannelEventParams{}
			if c.Flags().Changed("pageNo") {
				v := mustAtoi(p_PageNo)
				local := v
				params.PageNo = &local
			}
			if c.Flags().Changed("pageSizeNo") {
				v := mustAtoi(p_PageSizeNo)
				local := v
				params.PageSizeNo = &local
			}
			resp, err := client.ChannelEventWithResponse(c.Context(), arg_channelId, params)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&arg_channelId, "channelId", "", "[PATH] 채널 아이디 채널 목록 조회 참조")
	_ = c.MarkFlagRequired("channelId")
	c.Flags().StringVar(&p_PageNo, "pageNo", "", "페이지 번호 1~N (기본값: 1)")
	c.Flags().StringVar(&p_PageSizeNo, "pageSizeNo", "", "페이지당 항목 수 1~N (기본값: 20)")
	return c
}

func buildVodStationChannelInfo() *cobra.Command {
	var arg_channelId string
	c := &cobra.Command{
		Use: "channel-info",
		Short: "채널 조회",
		Long: "Classic/VPC 환경에서 이용 가능합니다.",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := vod_station.NewFromConfig(cfg)
			if err != nil { return err }
			resp, err := client.ChannelInfoWithResponse(c.Context(), arg_channelId)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&arg_channelId, "channelId", "", "[PATH] 채널 아이디 채널 목록 조회 참조")
	_ = c.MarkFlagRequired("channelId")
	return c
}

func buildVodStationChannelList() *cobra.Command {
	var p_PageNo string
	var p_PageSizeNo string
	c := &cobra.Command{
		Use: "channel-list",
		Short: "채널 목록 조회",
		Long: "Classic/VPC 환경에서 이용 가능합니다.",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := vod_station.NewFromConfig(cfg)
			if err != nil { return err }
			params := &vod_station.ChannelListParams{}
			if c.Flags().Changed("pageNo") {
				v := mustAtoi(p_PageNo)
				local := v
				params.PageNo = &local
			}
			if c.Flags().Changed("pageSizeNo") {
				v := mustAtoi(p_PageSizeNo)
				local := v
				params.PageSizeNo = &local
			}
			resp, err := client.ChannelListWithResponse(c.Context(), params)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&p_PageNo, "pageNo", "", "페이지 번호 1~N (기본값: 1)")
	c.Flags().StringVar(&p_PageSizeNo, "pageSizeNo", "", "페이지당 항목 수 1~N (기본값: 20)")
	return c
}

func buildVodStationChannelProtocolList() *cobra.Command {
	c := &cobra.Command{
		Use: "channel-protocol-list",
		Short: "프로토콜 목록 조회",
		Long: "Classic/VPC 환경에서 이용 가능합니다.",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := vod_station.NewFromConfig(cfg)
			if err != nil { return err }
			resp, err := client.ChannelProtocolListWithResponse(c.Context())
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	return c
}

func buildVodStationChannelStart() *cobra.Command {
	var arg_channelId string
	c := &cobra.Command{
		Use: "channel-start",
		Short: "채널 시작",
		Long: "Classic/VPC 환경에서 이용 가능합니다.",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := vod_station.NewFromConfig(cfg)
			if err != nil { return err }
			resp, err := client.ChannelStartWithResponse(c.Context(), arg_channelId)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&arg_channelId, "channelId", "", "[PATH] 채널 아이디 채널 목록 조회 참조")
	_ = c.MarkFlagRequired("channelId")
	return c
}

func buildVodStationChannelStop() *cobra.Command {
	var arg_channelId string
	c := &cobra.Command{
		Use: "channel-stop",
		Short: "채널 정지",
		Long: "Classic/VPC 환경에서 이용 가능합니다.",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := vod_station.NewFromConfig(cfg)
			if err != nil { return err }
			resp, err := client.ChannelStopWithResponse(c.Context(), arg_channelId)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&arg_channelId, "channelId", "", "[PATH] 채널 아이디 채널 목록 조회 참조")
	_ = c.MarkFlagRequired("channelId")
	return c
}

func buildVodStationEnCodingOptionCreate() *cobra.Command {
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "en-coding-option-create",
		Short: "인코딩 옵션 생성",
		Long: "Classic/VPC 환경에서 이용 가능합니다.",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := vod_station.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.EnCodingOptionCreateWithBodyWithResponse(c.Context(), "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}

func buildVodStationEnCodingOptionDelete() *cobra.Command {
	var arg_encodingOptionId string
	c := &cobra.Command{
		Use: "en-coding-option-delete",
		Short: "인코딩 옵션 삭제",
		Long: "Classic/VPC 환경에서 이용 가능합니다.",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := vod_station.NewFromConfig(cfg)
			if err != nil { return err }
			resp, err := client.EnCodingOptionDeleteWithResponse(c.Context(), arg_encodingOptionId)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&arg_encodingOptionId, "encodingOptionId", "", "[PATH] 인코딩 옵션 아이디 인코딩 옵션 목록 조회 참조")
	_ = c.MarkFlagRequired("encodingOptionId")
	return c
}

func buildVodStationEnCodingOptionInfo() *cobra.Command {
	var arg_encodingOptionId string
	c := &cobra.Command{
		Use: "en-coding-option-info",
		Short: "인코딩 옵션 조회",
		Long: "Classic/VPC 환경에서 이용 가능합니다.",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := vod_station.NewFromConfig(cfg)
			if err != nil { return err }
			resp, err := client.EnCodingOptionInfoWithResponse(c.Context(), arg_encodingOptionId)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&arg_encodingOptionId, "encodingOptionId", "", "[PATH] 인코딩 옵션 아이디 인코딩 옵션 목록 조회 참조")
	_ = c.MarkFlagRequired("encodingOptionId")
	return c
}

func buildVodStationEnCodingOptionList() *cobra.Command {
	c := &cobra.Command{
		Use: "en-coding-option-list",
		Short: "인코딩 옵션 목록 조회",
		Long: "Classic/VPC 환경에서 이용 가능합니다.",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := vod_station.NewFromConfig(cfg)
			if err != nil { return err }
			resp, err := client.EnCodingOptionListWithResponse(c.Context())
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	return c
}

func buildVodStationEnCodingOptionTemplateList() *cobra.Command {
	c := &cobra.Command{
		Use: "en-coding-option-template-list",
		Short: "인코딩 옵션 템플릿 목록 조회",
		Long: "Classic/VPC 환경에서 이용 가능합니다.",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := vod_station.NewFromConfig(cfg)
			if err != nil { return err }
			resp, err := client.EnCodingOptionTemplateListWithResponse(c.Context())
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	return c
}

func buildVodStationStatusInfoList() *cobra.Command {
	var arg_fileId string
	c := &cobra.Command{
		Use: "status-info-list",
		Short: "카테고리 상태 조회",
		Long: "Classic/VPC 환경에서 이용 가능합니다.",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := vod_station.NewFromConfig(cfg)
			if err != nil { return err }
			resp, err := client.StatusInfoListWithResponse(c.Context(), arg_fileId)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&arg_fileId, "fileId", "", "[PATH] 파일 아이디 카테고리 콜백 사용 참조 카테고리 파일 추가 참조 응답 바디의 id (파일 인코딩 작업 아이디)")
	_ = c.MarkFlagRequired("fileId")
	return c
}

func buildVodStationStatusList() *cobra.Command {
	var p_PageNo string
	var p_PageSizeNo string
	var p_WorkStartTimeFrom string
	var p_WorkStartTimeTo string
	c := &cobra.Command{
		Use: "status-list",
		Short: "카테고리 상태 목록 조회",
		Long: "Classic/VPC 환경에서 이용 가능합니다.",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := vod_station.NewFromConfig(cfg)
			if err != nil { return err }
			params := &vod_station.StatusListParams{}
			if c.Flags().Changed("pageNo") {
				v := mustAtoi(p_PageNo)
				local := v
				params.PageNo = &local
			}
			if c.Flags().Changed("pageSizeNo") {
				v := mustAtoi(p_PageSizeNo)
				local := v
				params.PageSizeNo = &local
			}
			if c.Flags().Changed("workStartTimeFrom") {
				v := mustAtoi(p_WorkStartTimeFrom)
				local := v
				params.WorkStartTimeFrom = &local
			}
			if c.Flags().Changed("workStartTimeTo") {
				v := mustAtoi(p_WorkStartTimeTo)
				local := v
				params.WorkStartTimeTo = &local
			}
			resp, err := client.StatusListWithResponse(c.Context(), params)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&p_PageNo, "pageNo", "", "페이지 번호 1~N (기본값: 1)")
	c.Flags().StringVar(&p_PageSizeNo, "pageSizeNo", "", "페이지당 항목 수 10~N (기본값: 20)")
	c.Flags().StringVar(&p_WorkStartTimeFrom, "workStartTimeFrom", "", "조회 시작 일시(밀리초) Unix Timestamp 형식")
	c.Flags().StringVar(&p_WorkStartTimeTo, "workStartTimeTo", "", "조회 종료 일시(밀리초) Unix Timestamp 형식")
	return c
}

func buildVodStationStatusStatistic() *cobra.Command {
	var p_WorkStartTimeFrom string
	var p_WorkStartTimeTo string
	c := &cobra.Command{
		Use: "status-statistic",
		Short: "카테고리 통계 조회",
		Long: "Classic/VPC 환경에서 이용 가능합니다.",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := vod_station.NewFromConfig(cfg)
			if err != nil { return err }
			params := &vod_station.StatusStatisticParams{}
			if c.Flags().Changed("workStartTimeFrom") {
				v := mustAtoi(p_WorkStartTimeFrom)
				local := v
				params.WorkStartTimeFrom = &local
			}
			if c.Flags().Changed("workStartTimeTo") {
				v := mustAtoi(p_WorkStartTimeTo)
				local := v
				params.WorkStartTimeTo = &local
			}
			resp, err := client.StatusStatisticWithResponse(c.Context(), params)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&p_WorkStartTimeFrom, "workStartTimeFrom", "", "조회 시작 일시(밀리초) Unix Timestamp 형식")
	c.Flags().StringVar(&p_WorkStartTimeTo, "workStartTimeTo", "", "조회 종료 일시(밀리초) Unix Timestamp 형식")
	return c
}
