// Code generated by tools/build_cli_typed.py. DO NOT EDIT.

package services

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"

	clicmd "github.com/greedylabs/ncloud-community-sdk/cli/cmd"
	ncloud "github.com/greedylabs/ncloud-community-sdk/sdk"
	web_security_checker "github.com/greedylabs/ncloud-community-sdk/sdk/services/web_security_checker"
)

var _ = bytes.NewBuffer
var _ = json.Unmarshal
var _ = fmt.Sprintf
var _ io.Reader = nil
var _ = os.Open
var _ = ncloud.AsAPIError

func init() {
	parent := &cobra.Command{ Use: "web-security-checker", Short: "web-security-checker" }
	parent.AddCommand(buildWebSecurityCheckerCancelJob())
	parent.AddCommand(buildWebSecurityCheckerCreateJob())
	parent.AddCommand(buildWebSecurityCheckerGetJobs())
	parent.AddCommand(buildWebSecurityCheckerGetReport())
	parent.AddCommand(buildWebSecurityCheckerSearchJobs())
	parent.AddCommand(buildWebSecurityCheckerStopJob())
	clicmd.RegisterServiceCmd(parent)
}

func buildWebSecurityCheckerCancelJob() *cobra.Command {
	var arg_instanceId string
	var p_InstanceId string
	c := &cobra.Command{
		Use: "cancel-job",
		Short: "샘플 코드",
		Long: "Classic/VPC 환경에서 이용 가능합니다.",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := web_security_checker.NewFromConfig(cfg)
			if err != nil { return err }
			params := &web_security_checker.CancelJobParams{}
			if c.Flags().Changed("InstanceId") {
				v := mustAtoi(p_InstanceId)
				params.InstanceId = v
			}
			resp, err := client.CancelJobWithResponse(c.Context(), arg_instanceId, params)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&arg_instanceId, "instanceId", "", "[PATH] (path) instanceId")
	_ = c.MarkFlagRequired("instanceId")
	c.Flags().StringVar(&p_InstanceId, "InstanceId", "", "진단 식별 번호 getJobs 또는 searchJobs 참조")
	return c
}

func buildWebSecurityCheckerCreateJob() *cobra.Command {
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "create-job",
		Short: "샘플 코드",
		Long: "Classic/VPC 환경에서 이용 가능합니다.",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := web_security_checker.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.CreateJobWithBodyWithResponse(c.Context(), "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}

func buildWebSecurityCheckerGetJobs() *cobra.Command {
	var p_Limit string
	var p_Page string
	c := &cobra.Command{
		Use: "get-jobs",
		Short: "샘플 코드",
		Long: "Classic/VPC 환경에서 이용 가능합니다.",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := web_security_checker.NewFromConfig(cfg)
			if err != nil { return err }
			params := &web_security_checker.GetJobsParams{}
			if c.Flags().Changed("limit") {
				v := mustAtoi(p_Limit)
				params.Limit = v
			}
			if c.Flags().Changed("page") {
				v := mustAtoi(p_Page)
				params.Page = v
			}
			resp, err := client.GetJobsWithResponse(c.Context(), params)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&p_Limit, "limit", "", "리스트 한 페이지당 출력 항목 수")
	c.Flags().StringVar(&p_Page, "page", "", "리스트의 페이지 번호")
	return c
}

func buildWebSecurityCheckerGetReport() *cobra.Command {
	var arg_instanceId string
	var p_InstanceId string
	c := &cobra.Command{
		Use: "get-report",
		Short: "샘플 코드",
		Long: "Classic/VPC 환경에서 이용 가능합니다.",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := web_security_checker.NewFromConfig(cfg)
			if err != nil { return err }
			params := &web_security_checker.GetReportParams{}
			if c.Flags().Changed("InstanceId") {
				v := mustAtoi(p_InstanceId)
				params.InstanceId = v
			}
			resp, err := client.GetReportWithResponse(c.Context(), arg_instanceId, params)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&arg_instanceId, "instanceId", "", "[PATH] (path) instanceId")
	_ = c.MarkFlagRequired("instanceId")
	c.Flags().StringVar(&p_InstanceId, "InstanceId", "", "진단 식별 번호 getJobs 또는 searchJobs 참조")
	return c
}

func buildWebSecurityCheckerSearchJobs() *cobra.Command {
	var bodyFile, bodyInline string
	c := &cobra.Command{
		Use: "search-jobs",
		Short: "샘플 코드",
		Long: "Classic/VPC 환경에서 이용 가능합니다.",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := web_security_checker.NewFromConfig(cfg)
			if err != nil { return err }
			var body io.Reader
			if bodyFile != "" {
				f, ferr := os.Open(bodyFile)
				if ferr != nil { return fmt.Errorf("open --body-file: %w", ferr) }
				defer f.Close()
				body = f
			} else if bodyInline != "" {
				body = bytes.NewBufferString(bodyInline)
			}
			resp, err := client.SearchJobsWithBodyWithResponse(c.Context(), "application/json", body)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&bodyFile, "body-file", "", "Path to a JSON file containing the request body.")
	c.Flags().StringVar(&bodyInline, "body", "", "Inline JSON request body (alternative to --body-file).")
	return c
}

func buildWebSecurityCheckerStopJob() *cobra.Command {
	var arg_instanceId string
	var p_InstanceId string
	c := &cobra.Command{
		Use: "stop-job",
		Short: "샘플 코드",
		Long: "Classic/VPC 환경에서 이용 가능합니다.",
		RunE: func(c *cobra.Command, _ []string) error {
			cfg, err := clicmd.ConfigFromCtx(c)
			if err != nil { return err }
			client, err := web_security_checker.NewFromConfig(cfg)
			if err != nil { return err }
			params := &web_security_checker.StopJobParams{}
			if c.Flags().Changed("InstanceId") {
				v := mustAtoi(p_InstanceId)
				params.InstanceId = v
			}
			resp, err := client.StopJobWithResponse(c.Context(), arg_instanceId, params)
			if err != nil { return err }
			if apiErr := ncloud.AsAPIError(resp.HTTPResponse, resp.Body); apiErr != nil {
				return apiErr
			}
			return clicmd.Render(c.OutOrStdout(), pickPayload(resp))
		},
	}
	c.Flags().StringVar(&arg_instanceId, "instanceId", "", "[PATH] (path) instanceId")
	_ = c.MarkFlagRequired("instanceId")
	c.Flags().StringVar(&p_InstanceId, "InstanceId", "", "진단 식별 번호 getJobs 또는 searchJobs 참조")
	return c
}
