// Package source_build provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package source_build

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

const (
	NcpAccessKeyScopes = "ncpAccessKey.Scopes"
	NcpHmacV2Scopes    = "ncpHmacV2.Scopes"
	NcpTimestampScopes = "ncpTimestamp.Scopes"
)

// CancelBuild defines model for CancelBuild.
type CancelBuild struct {
	BuildId *string `json:"buildId,omitempty"`
}

// ChangeProject defines model for ChangeProject.
type ChangeProject struct {
	Artifact    *ProjectArtifact `json:"artifact,omitempty"`
	Cache       *ProjectCache    `json:"cache,omitempty"`
	Cmd         *ProjectCmd      `json:"cmd,omitempty"`
	Description *string          `json:"description,omitempty"`
	Env         *ProjectEnv      `json:"env,omitempty"`
	Linked      *ProjectLinked   `json:"linked,omitempty"`
	Source      *ProjectSource   `json:"source,omitempty"`
}

// CreateProject defines model for CreateProject.
type CreateProject struct {
	Artifact    *ProjectArtifact `json:"artifact,omitempty"`
	Cache       *ProjectCache    `json:"cache,omitempty"`
	Cmd         *ProjectCmd      `json:"cmd,omitempty"`
	Description *string          `json:"description,omitempty"`
	Env         *ProjectEnv      `json:"env,omitempty"`
	Linked      *ProjectLinked   `json:"linked,omitempty"`
	Name        *string          `json:"name,omitempty"`
	Source      *ProjectSource   `json:"source,omitempty"`
}

// CreateProjectResponse defines model for CreateProjectResponse.
type CreateProjectResponse struct {
	Id   *int32  `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

// EnvPlatformConfigRequest defines model for EnvPlatformConfigRequest.
type EnvPlatformConfigRequest struct {
	Image    *string                          `json:"image,omitempty"`
	Os       *EnvPlatformConfigRequestOs      `json:"os,omitempty"`
	Registry *string                          `json:"registry,omitempty"`
	Runtime  *EnvPlatformConfigRequestRuntime `json:"runtime,omitempty"`
	Tag      *string                          `json:"tag,omitempty"`
}

// EnvPlatformConfigRequestOs defines model for EnvPlatformConfigRequestOs.
type EnvPlatformConfigRequestOs struct {
	Id *int32 `json:"id,omitempty"`
}

// EnvPlatformConfigRequestRuntime defines model for EnvPlatformConfigRequestRuntime.
type EnvPlatformConfigRequestRuntime struct {
	Id      *int32                                  `json:"id,omitempty"`
	Version *EnvPlatformConfigRequestRuntimeVersion `json:"version,omitempty"`
}

// EnvPlatformConfigRequestRuntimeVersion defines model for EnvPlatformConfigRequestRuntimeVersion.
type EnvPlatformConfigRequestRuntimeVersion struct {
	Id *int32 `json:"id,omitempty"`
}

// EnvPlatformConfigResponse defines model for EnvPlatformConfigResponse.
type EnvPlatformConfigResponse struct {
	Image    *string                           `json:"image,omitempty"`
	Os       *EnvPlatformConfigResponseOs      `json:"os,omitempty"`
	Registry *string                           `json:"registry,omitempty"`
	Runtime  *EnvPlatformConfigResponseRuntime `json:"runtime,omitempty"`
	Tag      *string                           `json:"tag,omitempty"`
}

// EnvPlatformConfigResponseOs defines model for EnvPlatformConfigResponseOs.
type EnvPlatformConfigResponseOs struct {
	Archi   *string `json:"archi,omitempty"`
	Id      *int32  `json:"id,omitempty"`
	Name    *string `json:"name,omitempty"`
	Version *string `json:"version,omitempty"`
}

// EnvPlatformConfigResponseRuntime defines model for EnvPlatformConfigResponseRuntime.
type EnvPlatformConfigResponseRuntime struct {
	Id      *int32                                   `json:"id,omitempty"`
	Name    *string                                  `json:"name,omitempty"`
	Version *EnvPlatformConfigResponseRuntimeVersion `json:"version,omitempty"`
}

// EnvPlatformConfigResponseRuntimeVersion defines model for EnvPlatformConfigResponseRuntimeVersion.
type EnvPlatformConfigResponseRuntimeVersion struct {
	Id   *int32  `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

// GetBuildHistoryResponse defines model for GetBuildHistoryResponse.
type GetBuildHistoryResponse struct {
	History *[]GetBuildHistoryResponseHistory `json:"history,omitempty"`
	Total   *int32                            `json:"total,omitempty"`
}

// GetBuildHistoryResponseHistory defines model for GetBuildHistoryResponseHistory.
type GetBuildHistoryResponseHistory struct {
	Begin       *int32  `json:"begin,omitempty"`
	BuildId     *string `json:"buildId,omitempty"`
	End         *int32  `json:"end,omitempty"`
	FailedPhase *string `json:"failedPhase,omitempty"`
	ProjectId   *int32  `json:"projectId,omitempty"`
	Status      *string `json:"status,omitempty"`
	UserId      *string `json:"userId,omitempty"`
}

// GetComputeEnvResponse defines model for GetComputeEnvResponse.
type GetComputeEnvResponse struct {
	Compute *[]GetComputeEnvResponseCompute `json:"compute,omitempty"`
}

// GetComputeEnvResponseCompute defines model for GetComputeEnvResponseCompute.
type GetComputeEnvResponseCompute struct {
	Cpu *int32 `json:"cpu,omitempty"`
	Id  *int32 `json:"id,omitempty"`
	Mem *int32 `json:"mem,omitempty"`
}

// GetContainerRegistryResponse defines model for GetContainerRegistryResponse.
type GetContainerRegistryResponse struct {
	Registry *[]GetContainerRegistryResponseRegistry `json:"registry,omitempty"`
}

// GetContainerRegistryResponseRegistry defines model for GetContainerRegistryResponseRegistry.
type GetContainerRegistryResponseRegistry struct {
	ActionName *string `json:"actionName,omitempty"`
	Disabled   *bool   `json:"disabled,omitempty"`
	Name       *string `json:"name,omitempty"`
	Permission *string `json:"permission,omitempty"`
	Status     *string `json:"status,omitempty"`
}

// GetDockerEnvResponse defines model for GetDockerEnvResponse.
type GetDockerEnvResponse struct {
	Docker *[]GetDockerEnvResponseDocker `json:"docker,omitempty"`
}

// GetDockerEnvResponseDocker defines model for GetDockerEnvResponseDocker.
type GetDockerEnvResponseDocker struct {
	Id   *int32  `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

// GetObjsBucketResponse defines model for GetObjsBucketResponse.
type GetObjsBucketResponse struct {
	Bucket *[]GetObjsBucketResponseBucket `json:"bucket,omitempty"`
}

// GetObjsBucketResponseBucket defines model for GetObjsBucketResponseBucket.
type GetObjsBucketResponseBucket struct {
	ActionName   *string `json:"actionName,omitempty"`
	CreationTime *int32  `json:"creationTime,omitempty"`
	Disabled     *bool   `json:"disabled,omitempty"`
	Name         *string `json:"name,omitempty"`
	Permission   *string `json:"permission,omitempty"`
}

// GetOsEnvResponse defines model for GetOsEnvResponse.
type GetOsEnvResponse struct {
	Os *[]GetOsEnvResponseOs `json:"os,omitempty"`
}

// GetOsEnvResponseOs defines model for GetOsEnvResponseOs.
type GetOsEnvResponseOs struct {
	Archi   *string `json:"archi,omitempty"`
	Id      *int32  `json:"id,omitempty"`
	Name    *string `json:"name,omitempty"`
	Version *string `json:"version,omitempty"`
}

// GetProjectDetailResponse defines model for GetProjectDetailResponse.
type GetProjectDetailResponse struct {
	Artifact    *GetProjectDetailResponseArtifact  `json:"artifact,omitempty"`
	Cache       *ProjectCache                      `json:"cache,omitempty"`
	Cmd         *ProjectCmd                        `json:"cmd,omitempty"`
	Created     *GetProjectDetailResponseCreated   `json:"created,omitempty"`
	Description *string                            `json:"description,omitempty"`
	Env         *GetProjectDetailResponseEnv       `json:"env,omitempty"`
	Id          *int32                             `json:"id,omitempty"`
	LastBuild   *GetProjectDetailResponseLastBuild `json:"lastBuild,omitempty"`
	Linked      *ProjectLinked                     `json:"linked,omitempty"`
	Name        *string                            `json:"name,omitempty"`
	Source      *GetProjectDetailResponseSource    `json:"source,omitempty"`
}

// GetProjectDetailResponseArtifact defines model for GetProjectDetailResponseArtifact.
type GetProjectDetailResponseArtifact struct {
	Backup  *bool                                    `json:"backup,omitempty"`
	Path    *[]string                                `json:"path,omitempty"`
	Storage *GetProjectDetailResponseArtifactStorage `json:"storage,omitempty"`
	Use     *bool                                    `json:"use,omitempty"`
}

// GetProjectDetailResponseArtifactStorage defines model for GetProjectDetailResponseArtifactStorage.
type GetProjectDetailResponseArtifactStorage struct {
	Bucket   *string `json:"bucket,omitempty"`
	Filename *string `json:"filename,omitempty"`
	Path     *string `json:"path,omitempty"`
}

// GetProjectDetailResponseCreated defines model for GetProjectDetailResponseCreated.
type GetProjectDetailResponseCreated struct {
	Timestamp *int64  `json:"timestamp,omitempty"`
	User      *string `json:"user,omitempty"`
}

// GetProjectDetailResponseEnv defines model for GetProjectDetailResponseEnv.
type GetProjectDetailResponseEnv struct {
	Compute  *GetProjectDetailResponseEnvCompute  `json:"compute,omitempty"`
	Docker   *GetProjectDetailResponseEnvDocker   `json:"docker,omitempty"`
	EnvVars  *[]ProjectEnvEnvVars                 `json:"envVars,omitempty"`
	Platform *GetProjectDetailResponseEnvPlatform `json:"platform,omitempty"`
	Timeout  *int32                               `json:"timeout,omitempty"`
}

// GetProjectDetailResponseEnvCompute defines model for GetProjectDetailResponseEnvCompute.
type GetProjectDetailResponseEnvCompute struct {
	Cpu *int32 `json:"cpu,omitempty"`
	Id  *int32 `json:"id,omitempty"`
	Mem *int32 `json:"mem,omitempty"`
}

// GetProjectDetailResponseEnvDocker defines model for GetProjectDetailResponseEnvDocker.
type GetProjectDetailResponseEnvDocker struct {
	Id   *int32  `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	Use  *bool   `json:"use,omitempty"`
}

// GetProjectDetailResponseEnvPlatform defines model for GetProjectDetailResponseEnvPlatform.
type GetProjectDetailResponseEnvPlatform struct {
	Config *EnvPlatformConfigResponse `json:"config,omitempty"`
	Type   *string                    `json:"type,omitempty"`
}

// GetProjectDetailResponseLastBuild defines model for GetProjectDetailResponseLastBuild.
type GetProjectDetailResponseLastBuild struct {
	Id        *string `json:"id,omitempty"`
	Status    *string `json:"status,omitempty"`
	Timestamp *int64  `json:"timestamp,omitempty"`
}

// GetProjectDetailResponseSource defines model for GetProjectDetailResponseSource.
type GetProjectDetailResponseSource struct {
	Config *GetProjectDetailResponseSourceConfig `json:"config,omitempty"`
	Type   *string                               `json:"type,omitempty"`
}

// GetProjectDetailResponseSourceConfig defines model for GetProjectDetailResponseSourceConfig.
type GetProjectDetailResponseSourceConfig struct {
	Branch     *string `json:"branch,omitempty"`
	Repository *string `json:"repository,omitempty"`
}

// GetProjectListResponse defines model for GetProjectListResponse.
type GetProjectListResponse struct {
	Project *[]GetProjectListResponseProject `json:"project,omitempty"`
	Total   *int32                           `json:"total,omitempty"`
}

// GetProjectListResponseProject defines model for GetProjectListResponseProject.
type GetProjectListResponseProject struct {
	ActionName *string `json:"actionName,omitempty"`
	Id         *int32  `json:"id,omitempty"`
	Name       *string `json:"name,omitempty"`
	Permission *string `json:"permission,omitempty"`
}

// GetRuntimeEnvResponse defines model for GetRuntimeEnvResponse.
type GetRuntimeEnvResponse struct {
	Runtime *[]GetDockerEnvResponseDocker `json:"runtime,omitempty"`
}

// GetRuntimeVersionEnvResponse defines model for GetRuntimeVersionEnvResponse.
type GetRuntimeVersionEnvResponse struct {
	Version *[]GetDockerEnvResponseDocker `json:"version,omitempty"`
}

// GetScBranchResponse defines model for GetScBranchResponse.
type GetScBranchResponse struct {
	Branch  *[]string `json:"branch,omitempty"`
	Default *string   `json:"default,omitempty"`
}

// GetScRepositoryResponse defines model for GetScRepositoryResponse.
type GetScRepositoryResponse struct {
	Repository *[]GetScRepositoryResponseRepository `json:"repository,omitempty"`
}

// GetScRepositoryResponseRepository defines model for GetScRepositoryResponseRepository.
type GetScRepositoryResponseRepository struct {
	ActionName *string `json:"actionName,omitempty"`
	Name       *string `json:"name,omitempty"`
	Permission *string `json:"permission,omitempty"`
}

// NcloudErrorEnvelope Naver Cloud Platform standard error envelope. Most products return this shape; some (Object Storage, CLOVA) wrap differently — `additionalProperties: true` keeps clients tolerant.
type NcloudErrorEnvelope struct {
	// Error Alternative error field. Type varies: object (CLOVA, NCP standard), string (cert-manager Spring Boot 404), or null.
	Error interface{} `json:"error,omitempty"`

	// ResponseError Error detail (present on most NCP product errors). Field shape varies; `additionalProperties: true` keeps clients tolerant.
	ResponseError        *NcloudErrorEnvelope_ResponseError `json:"responseError,omitempty"`
	AdditionalProperties map[string]interface{}             `json:"-"`
}

// NcloudErrorEnvelope_ResponseError Error detail (present on most NCP product errors). Field shape varies; `additionalProperties: true` keeps clients tolerant.
type NcloudErrorEnvelope_ResponseError struct {
	// ReturnCode NCP error code.
	ReturnCode *string `json:"returnCode,omitempty"`

	// ReturnMessage Human-readable error message.
	ReturnMessage        *string                `json:"returnMessage,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ProjectArtifact defines model for ProjectArtifact.
type ProjectArtifact struct {
	Backup  *bool                   `json:"backup,omitempty"`
	Path    *[]string               `json:"path,omitempty"`
	Storage *ProjectArtifactStorage `json:"storage,omitempty"`
	Use     *bool                   `json:"use,omitempty"`
}

// ProjectArtifactStorage defines model for ProjectArtifactStorage.
type ProjectArtifactStorage struct {
	Bucket   *string `json:"bucket,omitempty"`
	Filename *string `json:"filename,omitempty"`
	Path     *string `json:"path,omitempty"`
}

// ProjectCache defines model for ProjectCache.
type ProjectCache struct {
	Image    *string `json:"image,omitempty"`
	Latest   *bool   `json:"latest,omitempty"`
	Registry *string `json:"registry,omitempty"`
	Tag      *string `json:"tag,omitempty"`
	Use      *bool   `json:"use,omitempty"`
}

// ProjectCmd defines model for ProjectCmd.
type ProjectCmd struct {
	Build       []string               `json:"build"`
	Dockerbuild *ProjectCmdDockerbuild `json:"dockerbuild,omitempty"`
	Post        []string               `json:"post"`
	Pre         []string               `json:"pre"`
}

// ProjectCmdDockerbuild defines model for ProjectCmdDockerbuild.
type ProjectCmdDockerbuild struct {
	Dockerfile *string `json:"dockerfile,omitempty"`
	Image      *string `json:"image,omitempty"`
	Latest     *bool   `json:"latest,omitempty"`
	Registry   *string `json:"registry,omitempty"`
	Tag        *string `json:"tag,omitempty"`
	Use        *bool   `json:"use,omitempty"`
}

// ProjectEnv defines model for ProjectEnv.
type ProjectEnv struct {
	Compute  *ProjectEnvCompute   `json:"compute,omitempty"`
	Docker   *ProjectEnvDocker    `json:"docker,omitempty"`
	EnvVars  *[]ProjectEnvEnvVars `json:"envVars,omitempty"`
	Platform *ProjectEnvPlatform  `json:"platform,omitempty"`
	Timeout  *int32               `json:"timeout,omitempty"`
}

// ProjectEnvCompute defines model for ProjectEnvCompute.
type ProjectEnvCompute struct {
	Id *int32 `json:"id,omitempty"`
}

// ProjectEnvDocker defines model for ProjectEnvDocker.
type ProjectEnvDocker struct {
	Id  *int32 `json:"id,omitempty"`
	Use *bool  `json:"use,omitempty"`
}

// ProjectEnvEnvVars defines model for ProjectEnvEnvVars.
type ProjectEnvEnvVars struct {
	Key   *string `json:"key,omitempty"`
	Value *string `json:"value,omitempty"`
}

// ProjectEnvPlatform defines model for ProjectEnvPlatform.
type ProjectEnvPlatform struct {
	Config *EnvPlatformConfigRequest `json:"config,omitempty"`
	Type   *string                   `json:"type,omitempty"`
}

// ProjectLinked defines model for ProjectLinked.
type ProjectLinked struct {
	CloudLogAnalytics *bool `json:"CloudLogAnalytics,omitempty"`
	FileSafer         *bool `json:"FileSafer,omitempty"`
}

// ProjectSource defines model for ProjectSource.
type ProjectSource struct {
	Config *ProjectSourceConfig `json:"config,omitempty"`
	Type   *string              `json:"type,omitempty"`
}

// ProjectSourceConfig defines model for ProjectSourceConfig.
type ProjectSourceConfig struct {
	Branch     *string `json:"branch,omitempty"`
	Repository *string `json:"repository,omitempty"`
}

// StartBuildResponse defines model for StartBuildResponse.
type StartBuildResponse struct {
	BuildId *string `json:"buildId,omitempty"`
	Id      *int32  `json:"id,omitempty"`
}

// NcloudClientError Naver Cloud Platform standard error envelope. Most products return this shape; some (Object Storage, CLOVA) wrap differently — `additionalProperties: true` keeps clients tolerant.
type NcloudClientError = NcloudErrorEnvelope

// NcloudServerError Naver Cloud Platform standard error envelope. Most products return this shape; some (Object Storage, CLOVA) wrap differently — `additionalProperties: true` keeps clients tolerant.
type NcloudServerError = NcloudErrorEnvelope

// GetProjectsParams defines parameters for GetProjects.
type GetProjectsParams struct {
	LocalVarOptionals *map[string]interface{} `form:"localVarOptionals,omitempty" json:"localVarOptionals,omitempty"`
}

// CreateProjectJSONRequestBody defines body for CreateProject for application/json ContentType.
type CreateProjectJSONRequestBody = CreateProject

// ChangeProjectJSONRequestBody defines body for ChangeProject for application/json ContentType.
type ChangeProjectJSONRequestBody = ChangeProject

// CancelBuildJSONRequestBody defines body for CancelBuild for application/json ContentType.
type CancelBuildJSONRequestBody = CancelBuild

// Getter for additional properties for NcloudErrorEnvelope. Returns the specified
// element and whether it was found
func (a NcloudErrorEnvelope) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for NcloudErrorEnvelope
func (a *NcloudErrorEnvelope) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for NcloudErrorEnvelope to handle AdditionalProperties
func (a *NcloudErrorEnvelope) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["error"]; found {
		err = json.Unmarshal(raw, &a.Error)
		if err != nil {
			return fmt.Errorf("error reading 'error': %w", err)
		}
		delete(object, "error")
	}

	if raw, found := object["responseError"]; found {
		err = json.Unmarshal(raw, &a.ResponseError)
		if err != nil {
			return fmt.Errorf("error reading 'responseError': %w", err)
		}
		delete(object, "responseError")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for NcloudErrorEnvelope to handle AdditionalProperties
func (a NcloudErrorEnvelope) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["error"], err = json.Marshal(a.Error)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'error': %w", err)
	}

	if a.ResponseError != nil {
		object["responseError"], err = json.Marshal(a.ResponseError)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'responseError': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for NcloudErrorEnvelope_ResponseError. Returns the specified
// element and whether it was found
func (a NcloudErrorEnvelope_ResponseError) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for NcloudErrorEnvelope_ResponseError
func (a *NcloudErrorEnvelope_ResponseError) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for NcloudErrorEnvelope_ResponseError to handle AdditionalProperties
func (a *NcloudErrorEnvelope_ResponseError) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["returnCode"]; found {
		err = json.Unmarshal(raw, &a.ReturnCode)
		if err != nil {
			return fmt.Errorf("error reading 'returnCode': %w", err)
		}
		delete(object, "returnCode")
	}

	if raw, found := object["returnMessage"]; found {
		err = json.Unmarshal(raw, &a.ReturnMessage)
		if err != nil {
			return fmt.Errorf("error reading 'returnMessage': %w", err)
		}
		delete(object, "returnMessage")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for NcloudErrorEnvelope_ResponseError to handle AdditionalProperties
func (a NcloudErrorEnvelope_ResponseError) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.ReturnCode != nil {
		object["returnCode"], err = json.Marshal(a.ReturnCode)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'returnCode': %w", err)
		}
	}

	if a.ReturnMessage != nil {
		object["returnMessage"], err = json.Marshal(a.ReturnMessage)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'returnMessage': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetContainerRegistry request
	GetContainerRegistry(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetComputeEnv request
	GetComputeEnv(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetDockerEnv request
	GetDockerEnv(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetOsEnv request
	GetOsEnv(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetRuntimeEnv request
	GetRuntimeEnv(ctx context.Context, osId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetRuntimeVersionEnv request
	GetRuntimeVersionEnv(ctx context.Context, osId string, runtimeId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetObjectstorageBucket request
	GetObjectstorageBucket(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetProjects request
	GetProjects(ctx context.Context, params *GetProjectsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateProjectWithBody request with any body
	CreateProjectWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateProject(ctx context.Context, body CreateProjectJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteProject request
	DeleteProject(ctx context.Context, projectId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetProject request
	GetProject(ctx context.Context, projectId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ChangeProjectWithBody request with any body
	ChangeProjectWithBody(ctx context.Context, projectId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ChangeProject(ctx context.Context, projectId string, body ChangeProjectJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CancelBuildWithBody request with any body
	CancelBuildWithBody(ctx context.Context, projectId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CancelBuild(ctx context.Context, projectId string, body CancelBuildJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// StartBuild request
	StartBuild(ctx context.Context, projectId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetBuildHistory request
	GetBuildHistory(ctx context.Context, projectId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetSourcecommitRepositories request
	GetSourcecommitRepositories(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetSourcecommitRepositoryBranches request
	GetSourcecommitRepositoryBranches(ctx context.Context, repositoryName string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetContainerRegistry(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetContainerRegistryRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetComputeEnv(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetComputeEnvRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetDockerEnv(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetDockerEnvRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetOsEnv(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetOsEnvRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetRuntimeEnv(ctx context.Context, osId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetRuntimeEnvRequest(c.Server, osId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetRuntimeVersionEnv(ctx context.Context, osId string, runtimeId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetRuntimeVersionEnvRequest(c.Server, osId, runtimeId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetObjectstorageBucket(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetObjectstorageBucketRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetProjects(ctx context.Context, params *GetProjectsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetProjectsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateProjectWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateProjectRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateProject(ctx context.Context, body CreateProjectJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateProjectRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteProject(ctx context.Context, projectId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteProjectRequest(c.Server, projectId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetProject(ctx context.Context, projectId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetProjectRequest(c.Server, projectId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ChangeProjectWithBody(ctx context.Context, projectId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewChangeProjectRequestWithBody(c.Server, projectId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ChangeProject(ctx context.Context, projectId string, body ChangeProjectJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewChangeProjectRequest(c.Server, projectId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CancelBuildWithBody(ctx context.Context, projectId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCancelBuildRequestWithBody(c.Server, projectId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CancelBuild(ctx context.Context, projectId string, body CancelBuildJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCancelBuildRequest(c.Server, projectId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) StartBuild(ctx context.Context, projectId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewStartBuildRequest(c.Server, projectId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetBuildHistory(ctx context.Context, projectId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetBuildHistoryRequest(c.Server, projectId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetSourcecommitRepositories(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSourcecommitRepositoriesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetSourcecommitRepositoryBranches(ctx context.Context, repositoryName string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSourcecommitRepositoryBranchesRequest(c.Server, repositoryName)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetContainerRegistryRequest generates requests for GetContainerRegistry
func NewGetContainerRegistryRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/containerregistry/registry")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetComputeEnvRequest generates requests for GetComputeEnv
func NewGetComputeEnvRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/env/compute")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetDockerEnvRequest generates requests for GetDockerEnv
func NewGetDockerEnvRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/env/docker")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetOsEnvRequest generates requests for GetOsEnv
func NewGetOsEnvRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/env/os")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetRuntimeEnvRequest generates requests for GetRuntimeEnv
func NewGetRuntimeEnvRequest(server string, osId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "osId", osId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/env/os/%s/runtime", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetRuntimeVersionEnvRequest generates requests for GetRuntimeVersionEnv
func NewGetRuntimeVersionEnvRequest(server string, osId string, runtimeId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "osId", osId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "runtimeId", runtimeId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/env/os/%s/runtime/%s/version", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetObjectstorageBucketRequest generates requests for GetObjectstorageBucket
func NewGetObjectstorageBucketRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/objectstorage/bucket")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetProjectsRequest generates requests for GetProjects
func NewGetProjectsRequest(server string, params *GetProjectsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/project")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.LocalVarOptionals != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "localVarOptionals", *params.LocalVarOptionals, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "object", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateProjectRequest calls the generic CreateProject builder with application/json body
func NewCreateProjectRequest(server string, body CreateProjectJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateProjectRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateProjectRequestWithBody generates requests for CreateProject with any type of body
func NewCreateProjectRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/project")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteProjectRequest generates requests for DeleteProject
func NewDeleteProjectRequest(server string, projectId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "projectId", projectId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/project/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetProjectRequest generates requests for GetProject
func NewGetProjectRequest(server string, projectId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "projectId", projectId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/project/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewChangeProjectRequest calls the generic ChangeProject builder with application/json body
func NewChangeProjectRequest(server string, projectId string, body ChangeProjectJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewChangeProjectRequestWithBody(server, projectId, "application/json", bodyReader)
}

// NewChangeProjectRequestWithBody generates requests for ChangeProject with any type of body
func NewChangeProjectRequestWithBody(server string, projectId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "projectId", projectId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/project/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCancelBuildRequest calls the generic CancelBuild builder with application/json body
func NewCancelBuildRequest(server string, projectId string, body CancelBuildJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCancelBuildRequestWithBody(server, projectId, "application/json", bodyReader)
}

// NewCancelBuildRequestWithBody generates requests for CancelBuild with any type of body
func NewCancelBuildRequestWithBody(server string, projectId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "projectId", projectId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/project/%s/build", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewStartBuildRequest generates requests for StartBuild
func NewStartBuildRequest(server string, projectId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "projectId", projectId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/project/%s/build", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetBuildHistoryRequest generates requests for GetBuildHistory
func NewGetBuildHistoryRequest(server string, projectId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "projectId", projectId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/project/%s/history", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetSourcecommitRepositoriesRequest generates requests for GetSourcecommitRepositories
func NewGetSourcecommitRepositoriesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sourcecommit/repository")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetSourcecommitRepositoryBranchesRequest generates requests for GetSourcecommitRepositoryBranches
func NewGetSourcecommitRepositoryBranchesRequest(server string, repositoryName string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "repositoryName", repositoryName, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sourcecommit/repository/%s/branch", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetContainerRegistryWithResponse request
	GetContainerRegistryWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetContainerRegistryHTTPResp, error)

	// GetComputeEnvWithResponse request
	GetComputeEnvWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetComputeEnvHTTPResp, error)

	// GetDockerEnvWithResponse request
	GetDockerEnvWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetDockerEnvHTTPResp, error)

	// GetOsEnvWithResponse request
	GetOsEnvWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetOsEnvHTTPResp, error)

	// GetRuntimeEnvWithResponse request
	GetRuntimeEnvWithResponse(ctx context.Context, osId string, reqEditors ...RequestEditorFn) (*GetRuntimeEnvHTTPResp, error)

	// GetRuntimeVersionEnvWithResponse request
	GetRuntimeVersionEnvWithResponse(ctx context.Context, osId string, runtimeId string, reqEditors ...RequestEditorFn) (*GetRuntimeVersionEnvHTTPResp, error)

	// GetObjectstorageBucketWithResponse request
	GetObjectstorageBucketWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetObjectstorageBucketHTTPResp, error)

	// GetProjectsWithResponse request
	GetProjectsWithResponse(ctx context.Context, params *GetProjectsParams, reqEditors ...RequestEditorFn) (*GetProjectsHTTPResp, error)

	// CreateProjectWithBodyWithResponse request with any body
	CreateProjectWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateProjectHTTPResp, error)

	CreateProjectWithResponse(ctx context.Context, body CreateProjectJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateProjectHTTPResp, error)

	// DeleteProjectWithResponse request
	DeleteProjectWithResponse(ctx context.Context, projectId string, reqEditors ...RequestEditorFn) (*DeleteProjectHTTPResp, error)

	// GetProjectWithResponse request
	GetProjectWithResponse(ctx context.Context, projectId string, reqEditors ...RequestEditorFn) (*GetProjectHTTPResp, error)

	// ChangeProjectWithBodyWithResponse request with any body
	ChangeProjectWithBodyWithResponse(ctx context.Context, projectId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ChangeProjectHTTPResp, error)

	ChangeProjectWithResponse(ctx context.Context, projectId string, body ChangeProjectJSONRequestBody, reqEditors ...RequestEditorFn) (*ChangeProjectHTTPResp, error)

	// CancelBuildWithBodyWithResponse request with any body
	CancelBuildWithBodyWithResponse(ctx context.Context, projectId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CancelBuildHTTPResp, error)

	CancelBuildWithResponse(ctx context.Context, projectId string, body CancelBuildJSONRequestBody, reqEditors ...RequestEditorFn) (*CancelBuildHTTPResp, error)

	// StartBuildWithResponse request
	StartBuildWithResponse(ctx context.Context, projectId string, reqEditors ...RequestEditorFn) (*StartBuildHTTPResp, error)

	// GetBuildHistoryWithResponse request
	GetBuildHistoryWithResponse(ctx context.Context, projectId string, reqEditors ...RequestEditorFn) (*GetBuildHistoryHTTPResp, error)

	// GetSourcecommitRepositoriesWithResponse request
	GetSourcecommitRepositoriesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetSourcecommitRepositoriesHTTPResp, error)

	// GetSourcecommitRepositoryBranchesWithResponse request
	GetSourcecommitRepositoryBranchesWithResponse(ctx context.Context, repositoryName string, reqEditors ...RequestEditorFn) (*GetSourcecommitRepositoryBranchesHTTPResp, error)
}

type GetContainerRegistryHTTPResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GetContainerRegistryResponse
	JSON4XX      *NcloudClientError
	JSON5XX      *NcloudServerError
}

// Status returns HTTPResponse.Status
func (r GetContainerRegistryHTTPResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetContainerRegistryHTTPResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetComputeEnvHTTPResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GetComputeEnvResponse
	JSON4XX      *NcloudClientError
	JSON5XX      *NcloudServerError
}

// Status returns HTTPResponse.Status
func (r GetComputeEnvHTTPResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetComputeEnvHTTPResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetDockerEnvHTTPResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GetDockerEnvResponse
	JSON4XX      *NcloudClientError
	JSON5XX      *NcloudServerError
}

// Status returns HTTPResponse.Status
func (r GetDockerEnvHTTPResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetDockerEnvHTTPResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetOsEnvHTTPResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GetOsEnvResponse
	JSON4XX      *NcloudClientError
	JSON5XX      *NcloudServerError
}

// Status returns HTTPResponse.Status
func (r GetOsEnvHTTPResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetOsEnvHTTPResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetRuntimeEnvHTTPResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GetRuntimeEnvResponse
	JSON4XX      *NcloudClientError
	JSON5XX      *NcloudServerError
}

// Status returns HTTPResponse.Status
func (r GetRuntimeEnvHTTPResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetRuntimeEnvHTTPResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetRuntimeVersionEnvHTTPResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GetRuntimeVersionEnvResponse
	JSON4XX      *NcloudClientError
	JSON5XX      *NcloudServerError
}

// Status returns HTTPResponse.Status
func (r GetRuntimeVersionEnvHTTPResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetRuntimeVersionEnvHTTPResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetObjectstorageBucketHTTPResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GetObjsBucketResponse
	JSON4XX      *NcloudClientError
	JSON5XX      *NcloudServerError
}

// Status returns HTTPResponse.Status
func (r GetObjectstorageBucketHTTPResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetObjectstorageBucketHTTPResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetProjectsHTTPResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GetProjectListResponse
	JSON4XX      *NcloudClientError
	JSON5XX      *NcloudServerError
}

// Status returns HTTPResponse.Status
func (r GetProjectsHTTPResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetProjectsHTTPResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateProjectHTTPResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CreateProjectResponse
	JSON4XX      *NcloudClientError
	JSON5XX      *NcloudServerError
}

// Status returns HTTPResponse.Status
func (r CreateProjectHTTPResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateProjectHTTPResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteProjectHTTPResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON4XX      *NcloudClientError
	JSON5XX      *NcloudServerError
}

// Status returns HTTPResponse.Status
func (r DeleteProjectHTTPResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteProjectHTTPResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetProjectHTTPResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GetProjectDetailResponse
	JSON4XX      *NcloudClientError
	JSON5XX      *NcloudServerError
}

// Status returns HTTPResponse.Status
func (r GetProjectHTTPResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetProjectHTTPResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ChangeProjectHTTPResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CreateProjectResponse
	JSON4XX      *NcloudClientError
	JSON5XX      *NcloudServerError
}

// Status returns HTTPResponse.Status
func (r ChangeProjectHTTPResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ChangeProjectHTTPResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CancelBuildHTTPResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON4XX      *NcloudClientError
	JSON5XX      *NcloudServerError
}

// Status returns HTTPResponse.Status
func (r CancelBuildHTTPResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CancelBuildHTTPResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type StartBuildHTTPResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *StartBuildResponse
	JSON4XX      *NcloudClientError
	JSON5XX      *NcloudServerError
}

// Status returns HTTPResponse.Status
func (r StartBuildHTTPResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r StartBuildHTTPResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetBuildHistoryHTTPResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GetBuildHistoryResponse
	JSON4XX      *NcloudClientError
	JSON5XX      *NcloudServerError
}

// Status returns HTTPResponse.Status
func (r GetBuildHistoryHTTPResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetBuildHistoryHTTPResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetSourcecommitRepositoriesHTTPResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GetScRepositoryResponse
	JSON4XX      *NcloudClientError
	JSON5XX      *NcloudServerError
}

// Status returns HTTPResponse.Status
func (r GetSourcecommitRepositoriesHTTPResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetSourcecommitRepositoriesHTTPResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetSourcecommitRepositoryBranchesHTTPResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GetScBranchResponse
	JSON4XX      *NcloudClientError
	JSON5XX      *NcloudServerError
}

// Status returns HTTPResponse.Status
func (r GetSourcecommitRepositoryBranchesHTTPResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetSourcecommitRepositoryBranchesHTTPResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetContainerRegistryWithResponse request returning *GetContainerRegistryHTTPResp
func (c *ClientWithResponses) GetContainerRegistryWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetContainerRegistryHTTPResp, error) {
	rsp, err := c.GetContainerRegistry(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetContainerRegistryHTTPResp(rsp)
}

// GetComputeEnvWithResponse request returning *GetComputeEnvHTTPResp
func (c *ClientWithResponses) GetComputeEnvWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetComputeEnvHTTPResp, error) {
	rsp, err := c.GetComputeEnv(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetComputeEnvHTTPResp(rsp)
}

// GetDockerEnvWithResponse request returning *GetDockerEnvHTTPResp
func (c *ClientWithResponses) GetDockerEnvWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetDockerEnvHTTPResp, error) {
	rsp, err := c.GetDockerEnv(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetDockerEnvHTTPResp(rsp)
}

// GetOsEnvWithResponse request returning *GetOsEnvHTTPResp
func (c *ClientWithResponses) GetOsEnvWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetOsEnvHTTPResp, error) {
	rsp, err := c.GetOsEnv(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetOsEnvHTTPResp(rsp)
}

// GetRuntimeEnvWithResponse request returning *GetRuntimeEnvHTTPResp
func (c *ClientWithResponses) GetRuntimeEnvWithResponse(ctx context.Context, osId string, reqEditors ...RequestEditorFn) (*GetRuntimeEnvHTTPResp, error) {
	rsp, err := c.GetRuntimeEnv(ctx, osId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetRuntimeEnvHTTPResp(rsp)
}

// GetRuntimeVersionEnvWithResponse request returning *GetRuntimeVersionEnvHTTPResp
func (c *ClientWithResponses) GetRuntimeVersionEnvWithResponse(ctx context.Context, osId string, runtimeId string, reqEditors ...RequestEditorFn) (*GetRuntimeVersionEnvHTTPResp, error) {
	rsp, err := c.GetRuntimeVersionEnv(ctx, osId, runtimeId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetRuntimeVersionEnvHTTPResp(rsp)
}

// GetObjectstorageBucketWithResponse request returning *GetObjectstorageBucketHTTPResp
func (c *ClientWithResponses) GetObjectstorageBucketWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetObjectstorageBucketHTTPResp, error) {
	rsp, err := c.GetObjectstorageBucket(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetObjectstorageBucketHTTPResp(rsp)
}

// GetProjectsWithResponse request returning *GetProjectsHTTPResp
func (c *ClientWithResponses) GetProjectsWithResponse(ctx context.Context, params *GetProjectsParams, reqEditors ...RequestEditorFn) (*GetProjectsHTTPResp, error) {
	rsp, err := c.GetProjects(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetProjectsHTTPResp(rsp)
}

// CreateProjectWithBodyWithResponse request with arbitrary body returning *CreateProjectHTTPResp
func (c *ClientWithResponses) CreateProjectWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateProjectHTTPResp, error) {
	rsp, err := c.CreateProjectWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateProjectHTTPResp(rsp)
}

func (c *ClientWithResponses) CreateProjectWithResponse(ctx context.Context, body CreateProjectJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateProjectHTTPResp, error) {
	rsp, err := c.CreateProject(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateProjectHTTPResp(rsp)
}

// DeleteProjectWithResponse request returning *DeleteProjectHTTPResp
func (c *ClientWithResponses) DeleteProjectWithResponse(ctx context.Context, projectId string, reqEditors ...RequestEditorFn) (*DeleteProjectHTTPResp, error) {
	rsp, err := c.DeleteProject(ctx, projectId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteProjectHTTPResp(rsp)
}

// GetProjectWithResponse request returning *GetProjectHTTPResp
func (c *ClientWithResponses) GetProjectWithResponse(ctx context.Context, projectId string, reqEditors ...RequestEditorFn) (*GetProjectHTTPResp, error) {
	rsp, err := c.GetProject(ctx, projectId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetProjectHTTPResp(rsp)
}

// ChangeProjectWithBodyWithResponse request with arbitrary body returning *ChangeProjectHTTPResp
func (c *ClientWithResponses) ChangeProjectWithBodyWithResponse(ctx context.Context, projectId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ChangeProjectHTTPResp, error) {
	rsp, err := c.ChangeProjectWithBody(ctx, projectId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseChangeProjectHTTPResp(rsp)
}

func (c *ClientWithResponses) ChangeProjectWithResponse(ctx context.Context, projectId string, body ChangeProjectJSONRequestBody, reqEditors ...RequestEditorFn) (*ChangeProjectHTTPResp, error) {
	rsp, err := c.ChangeProject(ctx, projectId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseChangeProjectHTTPResp(rsp)
}

// CancelBuildWithBodyWithResponse request with arbitrary body returning *CancelBuildHTTPResp
func (c *ClientWithResponses) CancelBuildWithBodyWithResponse(ctx context.Context, projectId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CancelBuildHTTPResp, error) {
	rsp, err := c.CancelBuildWithBody(ctx, projectId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCancelBuildHTTPResp(rsp)
}

func (c *ClientWithResponses) CancelBuildWithResponse(ctx context.Context, projectId string, body CancelBuildJSONRequestBody, reqEditors ...RequestEditorFn) (*CancelBuildHTTPResp, error) {
	rsp, err := c.CancelBuild(ctx, projectId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCancelBuildHTTPResp(rsp)
}

// StartBuildWithResponse request returning *StartBuildHTTPResp
func (c *ClientWithResponses) StartBuildWithResponse(ctx context.Context, projectId string, reqEditors ...RequestEditorFn) (*StartBuildHTTPResp, error) {
	rsp, err := c.StartBuild(ctx, projectId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseStartBuildHTTPResp(rsp)
}

// GetBuildHistoryWithResponse request returning *GetBuildHistoryHTTPResp
func (c *ClientWithResponses) GetBuildHistoryWithResponse(ctx context.Context, projectId string, reqEditors ...RequestEditorFn) (*GetBuildHistoryHTTPResp, error) {
	rsp, err := c.GetBuildHistory(ctx, projectId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetBuildHistoryHTTPResp(rsp)
}

// GetSourcecommitRepositoriesWithResponse request returning *GetSourcecommitRepositoriesHTTPResp
func (c *ClientWithResponses) GetSourcecommitRepositoriesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetSourcecommitRepositoriesHTTPResp, error) {
	rsp, err := c.GetSourcecommitRepositories(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetSourcecommitRepositoriesHTTPResp(rsp)
}

// GetSourcecommitRepositoryBranchesWithResponse request returning *GetSourcecommitRepositoryBranchesHTTPResp
func (c *ClientWithResponses) GetSourcecommitRepositoryBranchesWithResponse(ctx context.Context, repositoryName string, reqEditors ...RequestEditorFn) (*GetSourcecommitRepositoryBranchesHTTPResp, error) {
	rsp, err := c.GetSourcecommitRepositoryBranches(ctx, repositoryName, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetSourcecommitRepositoryBranchesHTTPResp(rsp)
}

// ParseGetContainerRegistryHTTPResp parses an HTTP response from a GetContainerRegistryWithResponse call
func ParseGetContainerRegistryHTTPResp(rsp *http.Response) (*GetContainerRegistryHTTPResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetContainerRegistryHTTPResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetContainerRegistryResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest NcloudClientError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest NcloudServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParseGetComputeEnvHTTPResp parses an HTTP response from a GetComputeEnvWithResponse call
func ParseGetComputeEnvHTTPResp(rsp *http.Response) (*GetComputeEnvHTTPResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetComputeEnvHTTPResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetComputeEnvResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest NcloudClientError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest NcloudServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParseGetDockerEnvHTTPResp parses an HTTP response from a GetDockerEnvWithResponse call
func ParseGetDockerEnvHTTPResp(rsp *http.Response) (*GetDockerEnvHTTPResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetDockerEnvHTTPResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetDockerEnvResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest NcloudClientError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest NcloudServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParseGetOsEnvHTTPResp parses an HTTP response from a GetOsEnvWithResponse call
func ParseGetOsEnvHTTPResp(rsp *http.Response) (*GetOsEnvHTTPResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetOsEnvHTTPResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetOsEnvResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest NcloudClientError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest NcloudServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParseGetRuntimeEnvHTTPResp parses an HTTP response from a GetRuntimeEnvWithResponse call
func ParseGetRuntimeEnvHTTPResp(rsp *http.Response) (*GetRuntimeEnvHTTPResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetRuntimeEnvHTTPResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetRuntimeEnvResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest NcloudClientError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest NcloudServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParseGetRuntimeVersionEnvHTTPResp parses an HTTP response from a GetRuntimeVersionEnvWithResponse call
func ParseGetRuntimeVersionEnvHTTPResp(rsp *http.Response) (*GetRuntimeVersionEnvHTTPResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetRuntimeVersionEnvHTTPResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetRuntimeVersionEnvResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest NcloudClientError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest NcloudServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParseGetObjectstorageBucketHTTPResp parses an HTTP response from a GetObjectstorageBucketWithResponse call
func ParseGetObjectstorageBucketHTTPResp(rsp *http.Response) (*GetObjectstorageBucketHTTPResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetObjectstorageBucketHTTPResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetObjsBucketResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest NcloudClientError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest NcloudServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParseGetProjectsHTTPResp parses an HTTP response from a GetProjectsWithResponse call
func ParseGetProjectsHTTPResp(rsp *http.Response) (*GetProjectsHTTPResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetProjectsHTTPResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetProjectListResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest NcloudClientError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest NcloudServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParseCreateProjectHTTPResp parses an HTTP response from a CreateProjectWithResponse call
func ParseCreateProjectHTTPResp(rsp *http.Response) (*CreateProjectHTTPResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateProjectHTTPResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CreateProjectResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest NcloudClientError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest NcloudServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParseDeleteProjectHTTPResp parses an HTTP response from a DeleteProjectWithResponse call
func ParseDeleteProjectHTTPResp(rsp *http.Response) (*DeleteProjectHTTPResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteProjectHTTPResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest NcloudClientError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest NcloudServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParseGetProjectHTTPResp parses an HTTP response from a GetProjectWithResponse call
func ParseGetProjectHTTPResp(rsp *http.Response) (*GetProjectHTTPResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetProjectHTTPResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetProjectDetailResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest NcloudClientError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest NcloudServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParseChangeProjectHTTPResp parses an HTTP response from a ChangeProjectWithResponse call
func ParseChangeProjectHTTPResp(rsp *http.Response) (*ChangeProjectHTTPResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ChangeProjectHTTPResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CreateProjectResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest NcloudClientError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest NcloudServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParseCancelBuildHTTPResp parses an HTTP response from a CancelBuildWithResponse call
func ParseCancelBuildHTTPResp(rsp *http.Response) (*CancelBuildHTTPResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CancelBuildHTTPResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest NcloudClientError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest NcloudServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParseStartBuildHTTPResp parses an HTTP response from a StartBuildWithResponse call
func ParseStartBuildHTTPResp(rsp *http.Response) (*StartBuildHTTPResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &StartBuildHTTPResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest StartBuildResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest NcloudClientError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest NcloudServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParseGetBuildHistoryHTTPResp parses an HTTP response from a GetBuildHistoryWithResponse call
func ParseGetBuildHistoryHTTPResp(rsp *http.Response) (*GetBuildHistoryHTTPResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetBuildHistoryHTTPResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetBuildHistoryResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest NcloudClientError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest NcloudServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParseGetSourcecommitRepositoriesHTTPResp parses an HTTP response from a GetSourcecommitRepositoriesWithResponse call
func ParseGetSourcecommitRepositoriesHTTPResp(rsp *http.Response) (*GetSourcecommitRepositoriesHTTPResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetSourcecommitRepositoriesHTTPResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetScRepositoryResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest NcloudClientError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest NcloudServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParseGetSourcecommitRepositoryBranchesHTTPResp parses an HTTP response from a GetSourcecommitRepositoryBranchesWithResponse call
func ParseGetSourcecommitRepositoryBranchesHTTPResp(rsp *http.Response) (*GetSourcecommitRepositoryBranchesHTTPResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetSourcecommitRepositoryBranchesHTTPResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetScBranchResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest NcloudClientError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest NcloudServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}
