// Package cloud_advisor provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package cloud_advisor

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

const (
	NcpAccessKeyScopes = "ncpAccessKey.Scopes"
	NcpHmacV2Scopes    = "ncpHmacV2.Scopes"
	NcpTimestampScopes = "ncpTimestamp.Scopes"
)

// NcloudErrorEnvelope Naver Cloud Platform standard error envelope. Most products return this shape; some (Object Storage, CLOVA) wrap differently — `additionalProperties: true` keeps clients tolerant.
type NcloudErrorEnvelope struct {
	// Error Alternative error field. Type varies: object (CLOVA, NCP standard), string (cert-manager Spring Boot 404), or null.
	Error interface{} `json:"error,omitempty"`

	// ResponseError Error detail (present on most NCP product errors). Field shape varies; `additionalProperties: true` keeps clients tolerant.
	ResponseError        *NcloudErrorEnvelope_ResponseError `json:"responseError,omitempty"`
	AdditionalProperties map[string]interface{}             `json:"-"`
}

// NcloudErrorEnvelope_ResponseError Error detail (present on most NCP product errors). Field shape varies; `additionalProperties: true` keeps clients tolerant.
type NcloudErrorEnvelope_ResponseError struct {
	// ReturnCode NCP error code.
	ReturnCode *string `json:"returnCode,omitempty"`

	// ReturnMessage Human-readable error message.
	ReturnMessage        *string                `json:"returnMessage,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// NcloudClientError Naver Cloud Platform standard error envelope. Most products return this shape; some (Object Storage, CLOVA) wrap differently — `additionalProperties: true` keeps clients tolerant.
type NcloudClientError = NcloudErrorEnvelope

// NcloudServerError Naver Cloud Platform standard error envelope. Most products return this shape; some (Object Storage, CLOVA) wrap differently — `additionalProperties: true` keeps clients tolerant.
type NcloudServerError = NcloudErrorEnvelope

// ResultDetailParams defines parameters for ResultDetail.
type ResultDetailParams struct {
	// Display 조회 대상 인스턴스 all | included (기본값)| excluded all : 전체 인스턴스 included : 포함 설정 인스턴스 excluded : 제외 설정 인스턴스
	Display *string `form:"display,omitempty" json:"display,omitempty"`

	// Page 페이지 번호 1~N
	Page int `form:"page" json:"page"`

	// Size 페이지당 항목 수 1~N
	Size int `form:"size" json:"size"`
}

// ResultDetailExcludeJSONBody defines parameters for ResultDetailExclude.
type ResultDetailExcludeJSONBody struct {
	// InstanceKeys 조회 가능한 인스턴스의 instanceKey 목록 점검 항목 점검 결과 상세 조회 참조
	InstanceKeys []map[string]interface{} `json:"instanceKeys"`
}

// ResultDetailIncludeJSONBody defines parameters for ResultDetailInclude.
type ResultDetailIncludeJSONBody struct {
	// Root 조회 가능한 인스턴스의 instanceKey 점검 항목 점검 결과 상세 조회 참조
	Root []map[string]interface{} `json:"root"`
}

// ResultDetailExcludeJSONRequestBody defines body for ResultDetailExclude for application/json ContentType.
type ResultDetailExcludeJSONRequestBody ResultDetailExcludeJSONBody

// ResultDetailIncludeJSONRequestBody defines body for ResultDetailInclude for application/json ContentType.
type ResultDetailIncludeJSONRequestBody ResultDetailIncludeJSONBody

// Getter for additional properties for NcloudErrorEnvelope. Returns the specified
// element and whether it was found
func (a NcloudErrorEnvelope) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for NcloudErrorEnvelope
func (a *NcloudErrorEnvelope) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for NcloudErrorEnvelope to handle AdditionalProperties
func (a *NcloudErrorEnvelope) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["error"]; found {
		err = json.Unmarshal(raw, &a.Error)
		if err != nil {
			return fmt.Errorf("error reading 'error': %w", err)
		}
		delete(object, "error")
	}

	if raw, found := object["responseError"]; found {
		err = json.Unmarshal(raw, &a.ResponseError)
		if err != nil {
			return fmt.Errorf("error reading 'responseError': %w", err)
		}
		delete(object, "responseError")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for NcloudErrorEnvelope to handle AdditionalProperties
func (a NcloudErrorEnvelope) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["error"], err = json.Marshal(a.Error)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'error': %w", err)
	}

	if a.ResponseError != nil {
		object["responseError"], err = json.Marshal(a.ResponseError)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'responseError': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for NcloudErrorEnvelope_ResponseError. Returns the specified
// element and whether it was found
func (a NcloudErrorEnvelope_ResponseError) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for NcloudErrorEnvelope_ResponseError
func (a *NcloudErrorEnvelope_ResponseError) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for NcloudErrorEnvelope_ResponseError to handle AdditionalProperties
func (a *NcloudErrorEnvelope_ResponseError) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["returnCode"]; found {
		err = json.Unmarshal(raw, &a.ReturnCode)
		if err != nil {
			return fmt.Errorf("error reading 'returnCode': %w", err)
		}
		delete(object, "returnCode")
	}

	if raw, found := object["returnMessage"]; found {
		err = json.Unmarshal(raw, &a.ReturnMessage)
		if err != nil {
			return fmt.Errorf("error reading 'returnMessage': %w", err)
		}
		delete(object, "returnMessage")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for NcloudErrorEnvelope_ResponseError to handle AdditionalProperties
func (a NcloudErrorEnvelope_ResponseError) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.ReturnCode != nil {
		object["returnCode"], err = json.Marshal(a.ReturnCode)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'returnCode': %w", err)
		}
	}

	if a.ReturnMessage != nil {
		object["returnMessage"], err = json.Marshal(a.ReturnMessage)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'returnMessage': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// Categories request
	Categories(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ExcelAll request
	ExcelAll(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CheckItems request
	CheckItems(ctx context.Context, categoryCode string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ExcelCategories request
	ExcelCategories(ctx context.Context, categoryCode string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RefreshCategories request
	RefreshCategories(ctx context.Context, categoryCode string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ResultSummaryCategories request
	ResultSummaryCategories(ctx context.Context, categoryCode string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// StatusCategories request
	StatusCategories(ctx context.Context, categoryCode string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// Excel request
	Excel(ctx context.Context, categoryCode string, itemCode string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// Refresh request
	Refresh(ctx context.Context, categoryCode string, itemCode string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ResultDetail request
	ResultDetail(ctx context.Context, categoryCode string, itemCode string, params *ResultDetailParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ResultDetailExcludeWithBody request with any body
	ResultDetailExcludeWithBody(ctx context.Context, categoryCode string, itemCode string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ResultDetailExclude(ctx context.Context, categoryCode string, itemCode string, body ResultDetailExcludeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ResultDetailIncludeWithBody request with any body
	ResultDetailIncludeWithBody(ctx context.Context, categoryCode string, itemCode string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ResultDetailInclude(ctx context.Context, categoryCode string, itemCode string, body ResultDetailIncludeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// Status request
	Status(ctx context.Context, categoryCode string, itemCode string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// Dashboard request
	Dashboard(ctx context.Context, categoryCode string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) Categories(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCategoriesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ExcelAll(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewExcelAllRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CheckItems(ctx context.Context, categoryCode string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCheckItemsRequest(c.Server, categoryCode)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ExcelCategories(ctx context.Context, categoryCode string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewExcelCategoriesRequest(c.Server, categoryCode)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RefreshCategories(ctx context.Context, categoryCode string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRefreshCategoriesRequest(c.Server, categoryCode)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ResultSummaryCategories(ctx context.Context, categoryCode string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewResultSummaryCategoriesRequest(c.Server, categoryCode)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) StatusCategories(ctx context.Context, categoryCode string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewStatusCategoriesRequest(c.Server, categoryCode)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) Excel(ctx context.Context, categoryCode string, itemCode string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewExcelRequest(c.Server, categoryCode, itemCode)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) Refresh(ctx context.Context, categoryCode string, itemCode string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRefreshRequest(c.Server, categoryCode, itemCode)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ResultDetail(ctx context.Context, categoryCode string, itemCode string, params *ResultDetailParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewResultDetailRequest(c.Server, categoryCode, itemCode, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ResultDetailExcludeWithBody(ctx context.Context, categoryCode string, itemCode string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewResultDetailExcludeRequestWithBody(c.Server, categoryCode, itemCode, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ResultDetailExclude(ctx context.Context, categoryCode string, itemCode string, body ResultDetailExcludeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewResultDetailExcludeRequest(c.Server, categoryCode, itemCode, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ResultDetailIncludeWithBody(ctx context.Context, categoryCode string, itemCode string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewResultDetailIncludeRequestWithBody(c.Server, categoryCode, itemCode, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ResultDetailInclude(ctx context.Context, categoryCode string, itemCode string, body ResultDetailIncludeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewResultDetailIncludeRequest(c.Server, categoryCode, itemCode, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) Status(ctx context.Context, categoryCode string, itemCode string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewStatusRequest(c.Server, categoryCode, itemCode)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) Dashboard(ctx context.Context, categoryCode string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDashboardRequest(c.Server, categoryCode)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewCategoriesRequest generates requests for Categories
func NewCategoriesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/categories")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewExcelAllRequest generates requests for ExcelAll
func NewExcelAllRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/categories/checkitems/excel")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCheckItemsRequest generates requests for CheckItems
func NewCheckItemsRequest(server string, categoryCode string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "categoryCode", categoryCode, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/categories/%s/checkitems", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewExcelCategoriesRequest generates requests for ExcelCategories
func NewExcelCategoriesRequest(server string, categoryCode string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "categoryCode", categoryCode, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/categories/%s/checkitems/excel", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRefreshCategoriesRequest generates requests for RefreshCategories
func NewRefreshCategoriesRequest(server string, categoryCode string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "categoryCode", categoryCode, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/categories/%s/checkitems/refresh", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewResultSummaryCategoriesRequest generates requests for ResultSummaryCategories
func NewResultSummaryCategoriesRequest(server string, categoryCode string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "categoryCode", categoryCode, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/categories/%s/checkitems/result-summary", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewStatusCategoriesRequest generates requests for StatusCategories
func NewStatusCategoriesRequest(server string, categoryCode string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "categoryCode", categoryCode, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/categories/%s/checkitems/status", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewExcelRequest generates requests for Excel
func NewExcelRequest(server string, categoryCode string, itemCode string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "categoryCode", categoryCode, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "itemCode", itemCode, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/categories/%s/checkitems/%s/excel", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRefreshRequest generates requests for Refresh
func NewRefreshRequest(server string, categoryCode string, itemCode string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "categoryCode", categoryCode, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "itemCode", itemCode, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/categories/%s/checkitems/%s/refresh", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewResultDetailRequest generates requests for ResultDetail
func NewResultDetailRequest(server string, categoryCode string, itemCode string, params *ResultDetailParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "categoryCode", categoryCode, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "itemCode", itemCode, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/categories/%s/checkitems/%s/result-detail", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Display != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "display", *params.Display, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page", params.Page, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "size", params.Size, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewResultDetailExcludeRequest calls the generic ResultDetailExclude builder with application/json body
func NewResultDetailExcludeRequest(server string, categoryCode string, itemCode string, body ResultDetailExcludeJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewResultDetailExcludeRequestWithBody(server, categoryCode, itemCode, "application/json", bodyReader)
}

// NewResultDetailExcludeRequestWithBody generates requests for ResultDetailExclude with any type of body
func NewResultDetailExcludeRequestWithBody(server string, categoryCode string, itemCode string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "categoryCode", categoryCode, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "itemCode", itemCode, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/categories/%s/checkitems/%s/result-detail/exclude", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewResultDetailIncludeRequest calls the generic ResultDetailInclude builder with application/json body
func NewResultDetailIncludeRequest(server string, categoryCode string, itemCode string, body ResultDetailIncludeJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewResultDetailIncludeRequestWithBody(server, categoryCode, itemCode, "application/json", bodyReader)
}

// NewResultDetailIncludeRequestWithBody generates requests for ResultDetailInclude with any type of body
func NewResultDetailIncludeRequestWithBody(server string, categoryCode string, itemCode string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "categoryCode", categoryCode, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "itemCode", itemCode, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/categories/%s/checkitems/%s/result-detail/include", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewStatusRequest generates requests for Status
func NewStatusRequest(server string, categoryCode string, itemCode string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "categoryCode", categoryCode, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "itemCode", itemCode, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/categories/%s/checkitems/%s/status", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDashboardRequest generates requests for Dashboard
func NewDashboardRequest(server string, categoryCode string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "categoryCode", categoryCode, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/categories/%s/dashboard", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// CategoriesWithResponse request
	CategoriesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*CategoriesHTTPResp, error)

	// ExcelAllWithResponse request
	ExcelAllWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ExcelAllHTTPResp, error)

	// CheckItemsWithResponse request
	CheckItemsWithResponse(ctx context.Context, categoryCode string, reqEditors ...RequestEditorFn) (*CheckItemsHTTPResp, error)

	// ExcelCategoriesWithResponse request
	ExcelCategoriesWithResponse(ctx context.Context, categoryCode string, reqEditors ...RequestEditorFn) (*ExcelCategoriesHTTPResp, error)

	// RefreshCategoriesWithResponse request
	RefreshCategoriesWithResponse(ctx context.Context, categoryCode string, reqEditors ...RequestEditorFn) (*RefreshCategoriesHTTPResp, error)

	// ResultSummaryCategoriesWithResponse request
	ResultSummaryCategoriesWithResponse(ctx context.Context, categoryCode string, reqEditors ...RequestEditorFn) (*ResultSummaryCategoriesHTTPResp, error)

	// StatusCategoriesWithResponse request
	StatusCategoriesWithResponse(ctx context.Context, categoryCode string, reqEditors ...RequestEditorFn) (*StatusCategoriesHTTPResp, error)

	// ExcelWithResponse request
	ExcelWithResponse(ctx context.Context, categoryCode string, itemCode string, reqEditors ...RequestEditorFn) (*ExcelHTTPResp, error)

	// RefreshWithResponse request
	RefreshWithResponse(ctx context.Context, categoryCode string, itemCode string, reqEditors ...RequestEditorFn) (*RefreshHTTPResp, error)

	// ResultDetailWithResponse request
	ResultDetailWithResponse(ctx context.Context, categoryCode string, itemCode string, params *ResultDetailParams, reqEditors ...RequestEditorFn) (*ResultDetailHTTPResp, error)

	// ResultDetailExcludeWithBodyWithResponse request with any body
	ResultDetailExcludeWithBodyWithResponse(ctx context.Context, categoryCode string, itemCode string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ResultDetailExcludeHTTPResp, error)

	ResultDetailExcludeWithResponse(ctx context.Context, categoryCode string, itemCode string, body ResultDetailExcludeJSONRequestBody, reqEditors ...RequestEditorFn) (*ResultDetailExcludeHTTPResp, error)

	// ResultDetailIncludeWithBodyWithResponse request with any body
	ResultDetailIncludeWithBodyWithResponse(ctx context.Context, categoryCode string, itemCode string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ResultDetailIncludeHTTPResp, error)

	ResultDetailIncludeWithResponse(ctx context.Context, categoryCode string, itemCode string, body ResultDetailIncludeJSONRequestBody, reqEditors ...RequestEditorFn) (*ResultDetailIncludeHTTPResp, error)

	// StatusWithResponse request
	StatusWithResponse(ctx context.Context, categoryCode string, itemCode string, reqEditors ...RequestEditorFn) (*StatusHTTPResp, error)

	// DashboardWithResponse request
	DashboardWithResponse(ctx context.Context, categoryCode string, reqEditors ...RequestEditorFn) (*DashboardHTTPResp, error)
}

type CategoriesHTTPResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		// Contents 점검 카테고리 목록: contents
		Contents *[]map[string]interface{} `json:"contents,omitempty"`

		// Result API 처리 결과 SUCCESS | FAIL SUCCESS : 성공 FAIL : 실패
		Result *string `json:"result,omitempty"`
	}
	JSON4XX *NcloudClientError
	JSON5XX *NcloudServerError
}

// Status returns HTTPResponse.Status
func (r CategoriesHTTPResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CategoriesHTTPResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ExcelAllHTTPResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *map[string]interface{}
	JSON4XX      *NcloudClientError
	JSON5XX      *NcloudServerError
}

// Status returns HTTPResponse.Status
func (r ExcelAllHTTPResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ExcelAllHTTPResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CheckItemsHTTPResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		// Contents 점검 항목 목록: content
		Contents *[]map[string]interface{} `json:"contents,omitempty"`

		// Result API 처리 결과 SUCCESS | FAIL SUCCESS : 성공 FAIL : 실패
		Result *string `json:"result,omitempty"`
	}
	JSON4XX *NcloudClientError
	JSON5XX *NcloudServerError
}

// Status returns HTTPResponse.Status
func (r CheckItemsHTTPResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CheckItemsHTTPResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ExcelCategoriesHTTPResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *map[string]interface{}
	JSON4XX      *NcloudClientError
	JSON5XX      *NcloudServerError
}

// Status returns HTTPResponse.Status
func (r ExcelCategoriesHTTPResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ExcelCategoriesHTTPResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type RefreshCategoriesHTTPResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		// Contents 점검 항목 목록: content
		Contents *[]map[string]interface{} `json:"contents,omitempty"`

		// Result API 처리 결과 SUCCESS | FAIL SUCCESS : 성공 FAIL : 실패
		Result *string `json:"result,omitempty"`
	}
	JSON4XX *NcloudClientError
	JSON5XX *NcloudServerError
}

// Status returns HTTPResponse.Status
func (r RefreshCategoriesHTTPResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RefreshCategoriesHTTPResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ResultSummaryCategoriesHTTPResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		// Contents 점검 항목 목록: content
		Contents *[]map[string]interface{} `json:"contents,omitempty"`

		// Result API 처리 결과 SUCCESS | FAIL SUCCESS : 성공 FAIL : 실패
		Result *string `json:"result,omitempty"`
	}
	JSON4XX *NcloudClientError
	JSON5XX *NcloudServerError
}

// Status returns HTTPResponse.Status
func (r ResultSummaryCategoriesHTTPResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ResultSummaryCategoriesHTTPResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type StatusCategoriesHTTPResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		// Contents 점검 항목 목록: content
		Contents *[]map[string]interface{} `json:"contents,omitempty"`

		// Result API 처리 결과 SUCCESS | FAIL SUCCESS : 성공 FAIL : 실패
		Result *string `json:"result,omitempty"`
	}
	JSON4XX *NcloudClientError
	JSON5XX *NcloudServerError
}

// Status returns HTTPResponse.Status
func (r StatusCategoriesHTTPResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r StatusCategoriesHTTPResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ExcelHTTPResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *map[string]interface{}
	JSON4XX      *NcloudClientError
	JSON5XX      *NcloudServerError
}

// Status returns HTTPResponse.Status
func (r ExcelHTTPResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ExcelHTTPResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type RefreshHTTPResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		// Contents 점검 항목
		Contents *map[string]interface{} `json:"contents,omitempty"`

		// Result API 처리 결과 SUCCESS | FAIL SUCCESS : 성공 FAIL : 실패
		Result *string `json:"result,omitempty"`
	}
	JSON4XX *NcloudClientError
	JSON5XX *NcloudServerError
}

// Status returns HTTPResponse.Status
func (r RefreshHTTPResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RefreshHTTPResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ResultDetailHTTPResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		// Contents 점검 항목
		Contents *map[string]interface{} `json:"contents,omitempty"`

		// Data 점검 항목의 인스턴스별 상세 점검 결과: ResultTableRow
		Data *[]map[string]interface{} `json:"data,omitempty"`

		// Meta 페이지 처리를 위한 메타 데이터
		Meta *map[string]interface{} `json:"meta,omitempty"`

		// Result API 처리 결과 SUCCESS | FAIL SUCCESS : 성공 FAIL : 실패
		Result *string `json:"result,omitempty"`
	}
	JSON4XX *NcloudClientError
	JSON5XX *NcloudServerError
}

// Status returns HTTPResponse.Status
func (r ResultDetailHTTPResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ResultDetailHTTPResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ResultDetailExcludeHTTPResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		// Contents 설정 결과
		Contents *string `json:"contents,omitempty"`

		// Result API 처리 결과 SUCCESS | FAIL SUCCESS : 성공 FAIL : 실패
		Result *string `json:"result,omitempty"`
	}
	JSON4XX *NcloudClientError
	JSON5XX *NcloudServerError
}

// Status returns HTTPResponse.Status
func (r ResultDetailExcludeHTTPResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ResultDetailExcludeHTTPResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ResultDetailIncludeHTTPResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		// Contents 설정 결과
		Contents *string `json:"contents,omitempty"`

		// Result API 처리 결과 SUCCESS | FAIL SUCCESS : 성공 FAIL : 실패
		Result *string `json:"result,omitempty"`
	}
	JSON4XX *NcloudClientError
	JSON5XX *NcloudServerError
}

// Status returns HTTPResponse.Status
func (r ResultDetailIncludeHTTPResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ResultDetailIncludeHTTPResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type StatusHTTPResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		// Contents 점검 항목
		Contents *map[string]interface{} `json:"contents,omitempty"`

		// Result API 처리 결과 SUCCESS | FAIL SUCCESS : 성공 FAIL : 실패
		Result *string `json:"result,omitempty"`
	}
	JSON4XX *NcloudClientError
	JSON5XX *NcloudServerError
}

// Status returns HTTPResponse.Status
func (r StatusHTTPResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r StatusHTTPResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DashboardHTTPResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		// Contents 점검 카테고리 목록: content
		Contents *[]map[string]interface{} `json:"contents,omitempty"`

		// Result API 처리 결과 SUCCESS | FAIL SUCCESS : 성공 FAIL : 실패
		Result *string `json:"result,omitempty"`
	}
	JSON4XX *NcloudClientError
	JSON5XX *NcloudServerError
}

// Status returns HTTPResponse.Status
func (r DashboardHTTPResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DashboardHTTPResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// CategoriesWithResponse request returning *CategoriesHTTPResp
func (c *ClientWithResponses) CategoriesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*CategoriesHTTPResp, error) {
	rsp, err := c.Categories(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCategoriesHTTPResp(rsp)
}

// ExcelAllWithResponse request returning *ExcelAllHTTPResp
func (c *ClientWithResponses) ExcelAllWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ExcelAllHTTPResp, error) {
	rsp, err := c.ExcelAll(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseExcelAllHTTPResp(rsp)
}

// CheckItemsWithResponse request returning *CheckItemsHTTPResp
func (c *ClientWithResponses) CheckItemsWithResponse(ctx context.Context, categoryCode string, reqEditors ...RequestEditorFn) (*CheckItemsHTTPResp, error) {
	rsp, err := c.CheckItems(ctx, categoryCode, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCheckItemsHTTPResp(rsp)
}

// ExcelCategoriesWithResponse request returning *ExcelCategoriesHTTPResp
func (c *ClientWithResponses) ExcelCategoriesWithResponse(ctx context.Context, categoryCode string, reqEditors ...RequestEditorFn) (*ExcelCategoriesHTTPResp, error) {
	rsp, err := c.ExcelCategories(ctx, categoryCode, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseExcelCategoriesHTTPResp(rsp)
}

// RefreshCategoriesWithResponse request returning *RefreshCategoriesHTTPResp
func (c *ClientWithResponses) RefreshCategoriesWithResponse(ctx context.Context, categoryCode string, reqEditors ...RequestEditorFn) (*RefreshCategoriesHTTPResp, error) {
	rsp, err := c.RefreshCategories(ctx, categoryCode, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRefreshCategoriesHTTPResp(rsp)
}

// ResultSummaryCategoriesWithResponse request returning *ResultSummaryCategoriesHTTPResp
func (c *ClientWithResponses) ResultSummaryCategoriesWithResponse(ctx context.Context, categoryCode string, reqEditors ...RequestEditorFn) (*ResultSummaryCategoriesHTTPResp, error) {
	rsp, err := c.ResultSummaryCategories(ctx, categoryCode, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseResultSummaryCategoriesHTTPResp(rsp)
}

// StatusCategoriesWithResponse request returning *StatusCategoriesHTTPResp
func (c *ClientWithResponses) StatusCategoriesWithResponse(ctx context.Context, categoryCode string, reqEditors ...RequestEditorFn) (*StatusCategoriesHTTPResp, error) {
	rsp, err := c.StatusCategories(ctx, categoryCode, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseStatusCategoriesHTTPResp(rsp)
}

// ExcelWithResponse request returning *ExcelHTTPResp
func (c *ClientWithResponses) ExcelWithResponse(ctx context.Context, categoryCode string, itemCode string, reqEditors ...RequestEditorFn) (*ExcelHTTPResp, error) {
	rsp, err := c.Excel(ctx, categoryCode, itemCode, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseExcelHTTPResp(rsp)
}

// RefreshWithResponse request returning *RefreshHTTPResp
func (c *ClientWithResponses) RefreshWithResponse(ctx context.Context, categoryCode string, itemCode string, reqEditors ...RequestEditorFn) (*RefreshHTTPResp, error) {
	rsp, err := c.Refresh(ctx, categoryCode, itemCode, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRefreshHTTPResp(rsp)
}

// ResultDetailWithResponse request returning *ResultDetailHTTPResp
func (c *ClientWithResponses) ResultDetailWithResponse(ctx context.Context, categoryCode string, itemCode string, params *ResultDetailParams, reqEditors ...RequestEditorFn) (*ResultDetailHTTPResp, error) {
	rsp, err := c.ResultDetail(ctx, categoryCode, itemCode, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseResultDetailHTTPResp(rsp)
}

// ResultDetailExcludeWithBodyWithResponse request with arbitrary body returning *ResultDetailExcludeHTTPResp
func (c *ClientWithResponses) ResultDetailExcludeWithBodyWithResponse(ctx context.Context, categoryCode string, itemCode string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ResultDetailExcludeHTTPResp, error) {
	rsp, err := c.ResultDetailExcludeWithBody(ctx, categoryCode, itemCode, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseResultDetailExcludeHTTPResp(rsp)
}

func (c *ClientWithResponses) ResultDetailExcludeWithResponse(ctx context.Context, categoryCode string, itemCode string, body ResultDetailExcludeJSONRequestBody, reqEditors ...RequestEditorFn) (*ResultDetailExcludeHTTPResp, error) {
	rsp, err := c.ResultDetailExclude(ctx, categoryCode, itemCode, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseResultDetailExcludeHTTPResp(rsp)
}

// ResultDetailIncludeWithBodyWithResponse request with arbitrary body returning *ResultDetailIncludeHTTPResp
func (c *ClientWithResponses) ResultDetailIncludeWithBodyWithResponse(ctx context.Context, categoryCode string, itemCode string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ResultDetailIncludeHTTPResp, error) {
	rsp, err := c.ResultDetailIncludeWithBody(ctx, categoryCode, itemCode, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseResultDetailIncludeHTTPResp(rsp)
}

func (c *ClientWithResponses) ResultDetailIncludeWithResponse(ctx context.Context, categoryCode string, itemCode string, body ResultDetailIncludeJSONRequestBody, reqEditors ...RequestEditorFn) (*ResultDetailIncludeHTTPResp, error) {
	rsp, err := c.ResultDetailInclude(ctx, categoryCode, itemCode, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseResultDetailIncludeHTTPResp(rsp)
}

// StatusWithResponse request returning *StatusHTTPResp
func (c *ClientWithResponses) StatusWithResponse(ctx context.Context, categoryCode string, itemCode string, reqEditors ...RequestEditorFn) (*StatusHTTPResp, error) {
	rsp, err := c.Status(ctx, categoryCode, itemCode, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseStatusHTTPResp(rsp)
}

// DashboardWithResponse request returning *DashboardHTTPResp
func (c *ClientWithResponses) DashboardWithResponse(ctx context.Context, categoryCode string, reqEditors ...RequestEditorFn) (*DashboardHTTPResp, error) {
	rsp, err := c.Dashboard(ctx, categoryCode, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDashboardHTTPResp(rsp)
}

// ParseCategoriesHTTPResp parses an HTTP response from a CategoriesWithResponse call
func ParseCategoriesHTTPResp(rsp *http.Response) (*CategoriesHTTPResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CategoriesHTTPResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Contents 점검 카테고리 목록: contents
			Contents *[]map[string]interface{} `json:"contents,omitempty"`

			// Result API 처리 결과 SUCCESS | FAIL SUCCESS : 성공 FAIL : 실패
			Result *string `json:"result,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest NcloudClientError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest NcloudServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParseExcelAllHTTPResp parses an HTTP response from a ExcelAllWithResponse call
func ParseExcelAllHTTPResp(rsp *http.Response) (*ExcelAllHTTPResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ExcelAllHTTPResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest map[string]interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest NcloudClientError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest NcloudServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParseCheckItemsHTTPResp parses an HTTP response from a CheckItemsWithResponse call
func ParseCheckItemsHTTPResp(rsp *http.Response) (*CheckItemsHTTPResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CheckItemsHTTPResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Contents 점검 항목 목록: content
			Contents *[]map[string]interface{} `json:"contents,omitempty"`

			// Result API 처리 결과 SUCCESS | FAIL SUCCESS : 성공 FAIL : 실패
			Result *string `json:"result,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest NcloudClientError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest NcloudServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParseExcelCategoriesHTTPResp parses an HTTP response from a ExcelCategoriesWithResponse call
func ParseExcelCategoriesHTTPResp(rsp *http.Response) (*ExcelCategoriesHTTPResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ExcelCategoriesHTTPResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest map[string]interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest NcloudClientError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest NcloudServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParseRefreshCategoriesHTTPResp parses an HTTP response from a RefreshCategoriesWithResponse call
func ParseRefreshCategoriesHTTPResp(rsp *http.Response) (*RefreshCategoriesHTTPResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RefreshCategoriesHTTPResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Contents 점검 항목 목록: content
			Contents *[]map[string]interface{} `json:"contents,omitempty"`

			// Result API 처리 결과 SUCCESS | FAIL SUCCESS : 성공 FAIL : 실패
			Result *string `json:"result,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest NcloudClientError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest NcloudServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParseResultSummaryCategoriesHTTPResp parses an HTTP response from a ResultSummaryCategoriesWithResponse call
func ParseResultSummaryCategoriesHTTPResp(rsp *http.Response) (*ResultSummaryCategoriesHTTPResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ResultSummaryCategoriesHTTPResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Contents 점검 항목 목록: content
			Contents *[]map[string]interface{} `json:"contents,omitempty"`

			// Result API 처리 결과 SUCCESS | FAIL SUCCESS : 성공 FAIL : 실패
			Result *string `json:"result,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest NcloudClientError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest NcloudServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParseStatusCategoriesHTTPResp parses an HTTP response from a StatusCategoriesWithResponse call
func ParseStatusCategoriesHTTPResp(rsp *http.Response) (*StatusCategoriesHTTPResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &StatusCategoriesHTTPResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Contents 점검 항목 목록: content
			Contents *[]map[string]interface{} `json:"contents,omitempty"`

			// Result API 처리 결과 SUCCESS | FAIL SUCCESS : 성공 FAIL : 실패
			Result *string `json:"result,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest NcloudClientError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest NcloudServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParseExcelHTTPResp parses an HTTP response from a ExcelWithResponse call
func ParseExcelHTTPResp(rsp *http.Response) (*ExcelHTTPResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ExcelHTTPResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest map[string]interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest NcloudClientError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest NcloudServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParseRefreshHTTPResp parses an HTTP response from a RefreshWithResponse call
func ParseRefreshHTTPResp(rsp *http.Response) (*RefreshHTTPResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RefreshHTTPResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Contents 점검 항목
			Contents *map[string]interface{} `json:"contents,omitempty"`

			// Result API 처리 결과 SUCCESS | FAIL SUCCESS : 성공 FAIL : 실패
			Result *string `json:"result,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest NcloudClientError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest NcloudServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParseResultDetailHTTPResp parses an HTTP response from a ResultDetailWithResponse call
func ParseResultDetailHTTPResp(rsp *http.Response) (*ResultDetailHTTPResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ResultDetailHTTPResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Contents 점검 항목
			Contents *map[string]interface{} `json:"contents,omitempty"`

			// Data 점검 항목의 인스턴스별 상세 점검 결과: ResultTableRow
			Data *[]map[string]interface{} `json:"data,omitempty"`

			// Meta 페이지 처리를 위한 메타 데이터
			Meta *map[string]interface{} `json:"meta,omitempty"`

			// Result API 처리 결과 SUCCESS | FAIL SUCCESS : 성공 FAIL : 실패
			Result *string `json:"result,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest NcloudClientError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest NcloudServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParseResultDetailExcludeHTTPResp parses an HTTP response from a ResultDetailExcludeWithResponse call
func ParseResultDetailExcludeHTTPResp(rsp *http.Response) (*ResultDetailExcludeHTTPResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ResultDetailExcludeHTTPResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Contents 설정 결과
			Contents *string `json:"contents,omitempty"`

			// Result API 처리 결과 SUCCESS | FAIL SUCCESS : 성공 FAIL : 실패
			Result *string `json:"result,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest NcloudClientError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest NcloudServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParseResultDetailIncludeHTTPResp parses an HTTP response from a ResultDetailIncludeWithResponse call
func ParseResultDetailIncludeHTTPResp(rsp *http.Response) (*ResultDetailIncludeHTTPResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ResultDetailIncludeHTTPResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Contents 설정 결과
			Contents *string `json:"contents,omitempty"`

			// Result API 처리 결과 SUCCESS | FAIL SUCCESS : 성공 FAIL : 실패
			Result *string `json:"result,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest NcloudClientError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest NcloudServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParseStatusHTTPResp parses an HTTP response from a StatusWithResponse call
func ParseStatusHTTPResp(rsp *http.Response) (*StatusHTTPResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &StatusHTTPResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Contents 점검 항목
			Contents *map[string]interface{} `json:"contents,omitempty"`

			// Result API 처리 결과 SUCCESS | FAIL SUCCESS : 성공 FAIL : 실패
			Result *string `json:"result,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest NcloudClientError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest NcloudServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParseDashboardHTTPResp parses an HTTP response from a DashboardWithResponse call
func ParseDashboardHTTPResp(rsp *http.Response) (*DashboardHTTPResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DashboardHTTPResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Contents 점검 카테고리 목록: content
			Contents *[]map[string]interface{} `json:"contents,omitempty"`

			// Result API 처리 결과 SUCCESS | FAIL SUCCESS : 성공 FAIL : 실패
			Result *string `json:"result,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest NcloudClientError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest NcloudServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}
