// Package source_commit provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package source_commit

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

const (
	NcpAccessKeyScopes = "ncpAccessKey.Scopes"
	NcpHmacV2Scopes    = "ncpHmacV2.Scopes"
	NcpTimestampScopes = "ncpTimestamp.Scopes"
)

// ChangeRepository defines model for ChangeRepository.
type ChangeRepository struct {
	Description *string                 `json:"description,omitempty"`
	Linked      *CreateRepositoryLinked `json:"linked,omitempty"`
}

// CreateRepository defines model for CreateRepository.
type CreateRepository struct {
	Description *string                 `json:"description,omitempty"`
	Linked      *CreateRepositoryLinked `json:"linked,omitempty"`
	Name        *string                 `json:"name,omitempty"`
}

// CreateRepositoryLinked defines model for CreateRepositoryLinked.
type CreateRepositoryLinked struct {
	FileSafer *bool `json:"FileSafer,omitempty"`
}

// GetRepositoryDetailResponse defines model for GetRepositoryDetailResponse.
type GetRepositoryDetailResponse struct {
	Created *GetRepositoryDetailResponseCreated `json:"created,omitempty"`

	// Description repository description
	Description *string                         `json:"description,omitempty"`
	Git         *GetRepositoryDetailResponseGit `json:"git,omitempty"`

	// Id repository id
	Id     *int32                             `json:"id,omitempty"`
	Linked *GetRepositoryDetailResponseLinked `json:"linked,omitempty"`

	// Name repository name
	Name *string `json:"name,omitempty"`
}

// GetRepositoryDetailResponseCreated defines model for GetRepositoryDetailResponseCreated.
type GetRepositoryDetailResponseCreated struct {
	// Timestamp repository created timestamp
	Timestamp *float32 `json:"timestamp,omitempty"`

	// User repository created user
	User *string `json:"user,omitempty"`
}

// GetRepositoryDetailResponseGit defines model for GetRepositoryDetailResponseGit.
type GetRepositoryDetailResponseGit struct {
	// Https git repository https url
	Https *string `json:"https,omitempty"`

	// Ssh git repository ssh url
	Ssh *string `json:"ssh,omitempty"`
}

// GetRepositoryDetailResponseLinked defines model for GetRepositoryDetailResponseLinked.
type GetRepositoryDetailResponseLinked struct {
	// FileSafer FileSafer use
	FileSafer *bool `json:"FileSafer,omitempty"`
}

// GetRepositoryListResponse defines model for GetRepositoryListResponse.
type GetRepositoryListResponse struct {
	Repository *[]GetRepositoryListResponseRepository `json:"repository,omitempty"`

	// Total total repository count
	Total *int32 `json:"total,omitempty"`
}

// GetRepositoryListResponseRepository defines model for GetRepositoryListResponseRepository.
type GetRepositoryListResponseRepository struct {
	// ActionName repository detail action name
	ActionName *string `json:"actionName,omitempty"`

	// Id repository id
	Id *int32 `json:"id,omitempty"`

	// Name repository name
	Name *string `json:"name,omitempty"`

	// Permission repository permission
	Permission *string `json:"permission,omitempty"`
}

// NcloudErrorEnvelope Naver Cloud Platform standard error envelope. Most products return this shape; some (Object Storage, CLOVA) wrap differently — `additionalProperties: true` keeps clients tolerant.
type NcloudErrorEnvelope struct {
	// Error Alternative error field. Type varies: object (CLOVA, NCP standard), string (cert-manager Spring Boot 404), or null.
	Error interface{} `json:"error,omitempty"`

	// ResponseError Error detail (present on most NCP product errors). Field shape varies; `additionalProperties: true` keeps clients tolerant.
	ResponseError        *NcloudErrorEnvelope_ResponseError `json:"responseError,omitempty"`
	AdditionalProperties map[string]interface{}             `json:"-"`
}

// NcloudErrorEnvelope_ResponseError Error detail (present on most NCP product errors). Field shape varies; `additionalProperties: true` keeps clients tolerant.
type NcloudErrorEnvelope_ResponseError struct {
	// ReturnCode NCP error code.
	ReturnCode *string `json:"returnCode,omitempty"`

	// ReturnMessage Human-readable error message.
	ReturnMessage        *string                `json:"returnMessage,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// NcloudClientError Naver Cloud Platform standard error envelope. Most products return this shape; some (Object Storage, CLOVA) wrap differently — `additionalProperties: true` keeps clients tolerant.
type NcloudClientError = NcloudErrorEnvelope

// NcloudServerError Naver Cloud Platform standard error envelope. Most products return this shape; some (Object Storage, CLOVA) wrap differently — `additionalProperties: true` keeps clients tolerant.
type NcloudServerError = NcloudErrorEnvelope

// CreateRepositoryJSONRequestBody defines body for CreateRepository for application/json ContentType.
type CreateRepositoryJSONRequestBody = CreateRepository

// ChangeRepositoryJSONRequestBody defines body for ChangeRepository for application/json ContentType.
type ChangeRepositoryJSONRequestBody = ChangeRepository

// Getter for additional properties for NcloudErrorEnvelope. Returns the specified
// element and whether it was found
func (a NcloudErrorEnvelope) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for NcloudErrorEnvelope
func (a *NcloudErrorEnvelope) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for NcloudErrorEnvelope to handle AdditionalProperties
func (a *NcloudErrorEnvelope) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["error"]; found {
		err = json.Unmarshal(raw, &a.Error)
		if err != nil {
			return fmt.Errorf("error reading 'error': %w", err)
		}
		delete(object, "error")
	}

	if raw, found := object["responseError"]; found {
		err = json.Unmarshal(raw, &a.ResponseError)
		if err != nil {
			return fmt.Errorf("error reading 'responseError': %w", err)
		}
		delete(object, "responseError")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for NcloudErrorEnvelope to handle AdditionalProperties
func (a NcloudErrorEnvelope) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["error"], err = json.Marshal(a.Error)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'error': %w", err)
	}

	if a.ResponseError != nil {
		object["responseError"], err = json.Marshal(a.ResponseError)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'responseError': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for NcloudErrorEnvelope_ResponseError. Returns the specified
// element and whether it was found
func (a NcloudErrorEnvelope_ResponseError) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for NcloudErrorEnvelope_ResponseError
func (a *NcloudErrorEnvelope_ResponseError) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for NcloudErrorEnvelope_ResponseError to handle AdditionalProperties
func (a *NcloudErrorEnvelope_ResponseError) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["returnCode"]; found {
		err = json.Unmarshal(raw, &a.ReturnCode)
		if err != nil {
			return fmt.Errorf("error reading 'returnCode': %w", err)
		}
		delete(object, "returnCode")
	}

	if raw, found := object["returnMessage"]; found {
		err = json.Unmarshal(raw, &a.ReturnMessage)
		if err != nil {
			return fmt.Errorf("error reading 'returnMessage': %w", err)
		}
		delete(object, "returnMessage")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for NcloudErrorEnvelope_ResponseError to handle AdditionalProperties
func (a NcloudErrorEnvelope_ResponseError) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.ReturnCode != nil {
		object["returnCode"], err = json.Marshal(a.ReturnCode)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'returnCode': %w", err)
		}
	}

	if a.ReturnMessage != nil {
		object["returnMessage"], err = json.Marshal(a.ReturnMessage)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'returnMessage': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetRepositories request
	GetRepositories(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateRepositoryWithBody request with any body
	CreateRepositoryWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateRepository(ctx context.Context, body CreateRepositoryJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteRepository request
	DeleteRepository(ctx context.Context, repositoryId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetRepositoryById request
	GetRepositoryById(ctx context.Context, repositoryId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ChangeRepositoryWithBody request with any body
	ChangeRepositoryWithBody(ctx context.Context, repositoryId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ChangeRepository(ctx context.Context, repositoryId string, body ChangeRepositoryJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetRepository request
	GetRepository(ctx context.Context, repositoryName string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetRepositories(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetRepositoriesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateRepositoryWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateRepositoryRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateRepository(ctx context.Context, body CreateRepositoryJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateRepositoryRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteRepository(ctx context.Context, repositoryId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteRepositoryRequest(c.Server, repositoryId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetRepositoryById(ctx context.Context, repositoryId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetRepositoryByIdRequest(c.Server, repositoryId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ChangeRepositoryWithBody(ctx context.Context, repositoryId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewChangeRepositoryRequestWithBody(c.Server, repositoryId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ChangeRepository(ctx context.Context, repositoryId string, body ChangeRepositoryJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewChangeRepositoryRequest(c.Server, repositoryId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetRepository(ctx context.Context, repositoryName string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetRepositoryRequest(c.Server, repositoryName)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetRepositoriesRequest generates requests for GetRepositories
func NewGetRepositoriesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/repository")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateRepositoryRequest calls the generic CreateRepository builder with application/json body
func NewCreateRepositoryRequest(server string, body CreateRepositoryJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateRepositoryRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateRepositoryRequestWithBody generates requests for CreateRepository with any type of body
func NewCreateRepositoryRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/repository")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteRepositoryRequest generates requests for DeleteRepository
func NewDeleteRepositoryRequest(server string, repositoryId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "repositoryId", repositoryId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/repository/id/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetRepositoryByIdRequest generates requests for GetRepositoryById
func NewGetRepositoryByIdRequest(server string, repositoryId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "repositoryId", repositoryId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/repository/id/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewChangeRepositoryRequest calls the generic ChangeRepository builder with application/json body
func NewChangeRepositoryRequest(server string, repositoryId string, body ChangeRepositoryJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewChangeRepositoryRequestWithBody(server, repositoryId, "application/json", bodyReader)
}

// NewChangeRepositoryRequestWithBody generates requests for ChangeRepository with any type of body
func NewChangeRepositoryRequestWithBody(server string, repositoryId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "repositoryId", repositoryId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/repository/id/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetRepositoryRequest generates requests for GetRepository
func NewGetRepositoryRequest(server string, repositoryName string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "repositoryName", repositoryName, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/repository/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetRepositoriesWithResponse request
	GetRepositoriesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetRepositoriesHTTPResp, error)

	// CreateRepositoryWithBodyWithResponse request with any body
	CreateRepositoryWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateRepositoryHTTPResp, error)

	CreateRepositoryWithResponse(ctx context.Context, body CreateRepositoryJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateRepositoryHTTPResp, error)

	// DeleteRepositoryWithResponse request
	DeleteRepositoryWithResponse(ctx context.Context, repositoryId string, reqEditors ...RequestEditorFn) (*DeleteRepositoryHTTPResp, error)

	// GetRepositoryByIdWithResponse request
	GetRepositoryByIdWithResponse(ctx context.Context, repositoryId string, reqEditors ...RequestEditorFn) (*GetRepositoryByIdHTTPResp, error)

	// ChangeRepositoryWithBodyWithResponse request with any body
	ChangeRepositoryWithBodyWithResponse(ctx context.Context, repositoryId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ChangeRepositoryHTTPResp, error)

	ChangeRepositoryWithResponse(ctx context.Context, repositoryId string, body ChangeRepositoryJSONRequestBody, reqEditors ...RequestEditorFn) (*ChangeRepositoryHTTPResp, error)

	// GetRepositoryWithResponse request
	GetRepositoryWithResponse(ctx context.Context, repositoryName string, reqEditors ...RequestEditorFn) (*GetRepositoryHTTPResp, error)
}

type GetRepositoriesHTTPResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GetRepositoryListResponse
	JSON4XX      *NcloudClientError
	JSON5XX      *NcloudServerError
}

// Status returns HTTPResponse.Status
func (r GetRepositoriesHTTPResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetRepositoriesHTTPResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateRepositoryHTTPResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *bool
	JSON4XX      *NcloudClientError
	JSON5XX      *NcloudServerError
}

// Status returns HTTPResponse.Status
func (r CreateRepositoryHTTPResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateRepositoryHTTPResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteRepositoryHTTPResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *bool
	JSON4XX      *NcloudClientError
	JSON5XX      *NcloudServerError
}

// Status returns HTTPResponse.Status
func (r DeleteRepositoryHTTPResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteRepositoryHTTPResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetRepositoryByIdHTTPResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GetRepositoryDetailResponse
	JSON4XX      *NcloudClientError
	JSON5XX      *NcloudServerError
}

// Status returns HTTPResponse.Status
func (r GetRepositoryByIdHTTPResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetRepositoryByIdHTTPResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ChangeRepositoryHTTPResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *bool
	JSON4XX      *NcloudClientError
	JSON5XX      *NcloudServerError
}

// Status returns HTTPResponse.Status
func (r ChangeRepositoryHTTPResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ChangeRepositoryHTTPResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetRepositoryHTTPResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GetRepositoryDetailResponse
	JSON4XX      *NcloudClientError
	JSON5XX      *NcloudServerError
}

// Status returns HTTPResponse.Status
func (r GetRepositoryHTTPResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetRepositoryHTTPResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetRepositoriesWithResponse request returning *GetRepositoriesHTTPResp
func (c *ClientWithResponses) GetRepositoriesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetRepositoriesHTTPResp, error) {
	rsp, err := c.GetRepositories(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetRepositoriesHTTPResp(rsp)
}

// CreateRepositoryWithBodyWithResponse request with arbitrary body returning *CreateRepositoryHTTPResp
func (c *ClientWithResponses) CreateRepositoryWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateRepositoryHTTPResp, error) {
	rsp, err := c.CreateRepositoryWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateRepositoryHTTPResp(rsp)
}

func (c *ClientWithResponses) CreateRepositoryWithResponse(ctx context.Context, body CreateRepositoryJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateRepositoryHTTPResp, error) {
	rsp, err := c.CreateRepository(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateRepositoryHTTPResp(rsp)
}

// DeleteRepositoryWithResponse request returning *DeleteRepositoryHTTPResp
func (c *ClientWithResponses) DeleteRepositoryWithResponse(ctx context.Context, repositoryId string, reqEditors ...RequestEditorFn) (*DeleteRepositoryHTTPResp, error) {
	rsp, err := c.DeleteRepository(ctx, repositoryId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteRepositoryHTTPResp(rsp)
}

// GetRepositoryByIdWithResponse request returning *GetRepositoryByIdHTTPResp
func (c *ClientWithResponses) GetRepositoryByIdWithResponse(ctx context.Context, repositoryId string, reqEditors ...RequestEditorFn) (*GetRepositoryByIdHTTPResp, error) {
	rsp, err := c.GetRepositoryById(ctx, repositoryId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetRepositoryByIdHTTPResp(rsp)
}

// ChangeRepositoryWithBodyWithResponse request with arbitrary body returning *ChangeRepositoryHTTPResp
func (c *ClientWithResponses) ChangeRepositoryWithBodyWithResponse(ctx context.Context, repositoryId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ChangeRepositoryHTTPResp, error) {
	rsp, err := c.ChangeRepositoryWithBody(ctx, repositoryId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseChangeRepositoryHTTPResp(rsp)
}

func (c *ClientWithResponses) ChangeRepositoryWithResponse(ctx context.Context, repositoryId string, body ChangeRepositoryJSONRequestBody, reqEditors ...RequestEditorFn) (*ChangeRepositoryHTTPResp, error) {
	rsp, err := c.ChangeRepository(ctx, repositoryId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseChangeRepositoryHTTPResp(rsp)
}

// GetRepositoryWithResponse request returning *GetRepositoryHTTPResp
func (c *ClientWithResponses) GetRepositoryWithResponse(ctx context.Context, repositoryName string, reqEditors ...RequestEditorFn) (*GetRepositoryHTTPResp, error) {
	rsp, err := c.GetRepository(ctx, repositoryName, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetRepositoryHTTPResp(rsp)
}

// ParseGetRepositoriesHTTPResp parses an HTTP response from a GetRepositoriesWithResponse call
func ParseGetRepositoriesHTTPResp(rsp *http.Response) (*GetRepositoriesHTTPResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetRepositoriesHTTPResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetRepositoryListResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest NcloudClientError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest NcloudServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParseCreateRepositoryHTTPResp parses an HTTP response from a CreateRepositoryWithResponse call
func ParseCreateRepositoryHTTPResp(rsp *http.Response) (*CreateRepositoryHTTPResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateRepositoryHTTPResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest bool
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest NcloudClientError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest NcloudServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParseDeleteRepositoryHTTPResp parses an HTTP response from a DeleteRepositoryWithResponse call
func ParseDeleteRepositoryHTTPResp(rsp *http.Response) (*DeleteRepositoryHTTPResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteRepositoryHTTPResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest bool
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest NcloudClientError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest NcloudServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParseGetRepositoryByIdHTTPResp parses an HTTP response from a GetRepositoryByIdWithResponse call
func ParseGetRepositoryByIdHTTPResp(rsp *http.Response) (*GetRepositoryByIdHTTPResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetRepositoryByIdHTTPResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetRepositoryDetailResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest NcloudClientError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest NcloudServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParseChangeRepositoryHTTPResp parses an HTTP response from a ChangeRepositoryWithResponse call
func ParseChangeRepositoryHTTPResp(rsp *http.Response) (*ChangeRepositoryHTTPResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ChangeRepositoryHTTPResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest bool
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest NcloudClientError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest NcloudServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParseGetRepositoryHTTPResp parses an HTTP response from a GetRepositoryWithResponse call
func ParseGetRepositoryHTTPResp(rsp *http.Response) (*GetRepositoryHTTPResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetRepositoryHTTPResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetRepositoryDetailResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest NcloudClientError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest NcloudServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}
