// Package sts provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package sts

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"
)

const (
	NcpAccessKeyScopes = "ncpAccessKey.Scopes"
	NcpHmacV2Scopes    = "ncpHmacV2.Scopes"
	NcpTimestampScopes = "ncpTimestamp.Scopes"
)

// CreateStsRequest defines model for CreateStsRequest.
type CreateStsRequest struct {
	// DurationSec Access Key 유효 시간(초). 600~43200.
	DurationSec *int `json:"durationSec,omitempty"`

	// SerialNumber OTP 디바이스 NRN 또는 MFA 시리얼 번호 (MFA 활성 계정)
	SerialNumber *string `json:"serialNumber,omitempty"`

	// TokenCode OTP 인증 번호 (MFA 활성 계정)
	TokenCode *int `json:"tokenCode,omitempty"`
}

// Credentials defines model for Credentials.
type Credentials struct {
	// AccessKey Access Key (ncp_iam_* 형식)
	AccessKey string `json:"accessKey"`

	// CreateTime 생성 일자 (ISO 8601)
	CreateTime time.Time `json:"createTime"`

	// ExpireTime 만료 일자 (ISO 8601)
	ExpireTime time.Time `json:"expireTime"`

	// KeySecret Secret Key
	KeySecret string `json:"keySecret"`

	// UseMfa MFA 인증 여부
	UseMfa bool `json:"useMfa"`
}

// NcloudErrorEnvelope Naver Cloud Platform standard error envelope. Most products return this shape; some (Object Storage, CLOVA) wrap differently — `additionalProperties: true` keeps clients tolerant.
type NcloudErrorEnvelope struct {
	// Error Alternative error field. Type varies: object (CLOVA, NCP standard), string (cert-manager Spring Boot 404), or null.
	Error interface{} `json:"error,omitempty"`

	// ResponseError Error detail (present on most NCP product errors). Field shape varies; `additionalProperties: true` keeps clients tolerant.
	ResponseError        *NcloudErrorEnvelope_ResponseError `json:"responseError,omitempty"`
	AdditionalProperties map[string]interface{}             `json:"-"`
}

// NcloudErrorEnvelope_ResponseError Error detail (present on most NCP product errors). Field shape varies; `additionalProperties: true` keeps clients tolerant.
type NcloudErrorEnvelope_ResponseError struct {
	// ReturnCode NCP error code.
	ReturnCode *string `json:"returnCode,omitempty"`

	// ReturnMessage Human-readable error message.
	ReturnMessage        *string                `json:"returnMessage,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// NcloudClientError Naver Cloud Platform standard error envelope. Most products return this shape; some (Object Storage, CLOVA) wrap differently — `additionalProperties: true` keeps clients tolerant.
type NcloudClientError = NcloudErrorEnvelope

// NcloudServerError Naver Cloud Platform standard error envelope. Most products return this shape; some (Object Storage, CLOVA) wrap differently — `additionalProperties: true` keeps clients tolerant.
type NcloudServerError = NcloudErrorEnvelope

// CreateStsJSONRequestBody defines body for CreateSts for application/json ContentType.
type CreateStsJSONRequestBody = CreateStsRequest

// Getter for additional properties for NcloudErrorEnvelope. Returns the specified
// element and whether it was found
func (a NcloudErrorEnvelope) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for NcloudErrorEnvelope
func (a *NcloudErrorEnvelope) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for NcloudErrorEnvelope to handle AdditionalProperties
func (a *NcloudErrorEnvelope) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["error"]; found {
		err = json.Unmarshal(raw, &a.Error)
		if err != nil {
			return fmt.Errorf("error reading 'error': %w", err)
		}
		delete(object, "error")
	}

	if raw, found := object["responseError"]; found {
		err = json.Unmarshal(raw, &a.ResponseError)
		if err != nil {
			return fmt.Errorf("error reading 'responseError': %w", err)
		}
		delete(object, "responseError")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for NcloudErrorEnvelope to handle AdditionalProperties
func (a NcloudErrorEnvelope) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["error"], err = json.Marshal(a.Error)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'error': %w", err)
	}

	if a.ResponseError != nil {
		object["responseError"], err = json.Marshal(a.ResponseError)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'responseError': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for NcloudErrorEnvelope_ResponseError. Returns the specified
// element and whether it was found
func (a NcloudErrorEnvelope_ResponseError) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for NcloudErrorEnvelope_ResponseError
func (a *NcloudErrorEnvelope_ResponseError) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for NcloudErrorEnvelope_ResponseError to handle AdditionalProperties
func (a *NcloudErrorEnvelope_ResponseError) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["returnCode"]; found {
		err = json.Unmarshal(raw, &a.ReturnCode)
		if err != nil {
			return fmt.Errorf("error reading 'returnCode': %w", err)
		}
		delete(object, "returnCode")
	}

	if raw, found := object["returnMessage"]; found {
		err = json.Unmarshal(raw, &a.ReturnMessage)
		if err != nil {
			return fmt.Errorf("error reading 'returnMessage': %w", err)
		}
		delete(object, "returnMessage")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for NcloudErrorEnvelope_ResponseError to handle AdditionalProperties
func (a NcloudErrorEnvelope_ResponseError) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.ReturnCode != nil {
		object["returnCode"], err = json.Marshal(a.ReturnCode)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'returnCode': %w", err)
		}
	}

	if a.ReturnMessage != nil {
		object["returnMessage"], err = json.Marshal(a.ReturnMessage)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'returnMessage': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetSts request
	GetSts(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateStsWithBody request with any body
	CreateStsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateSts(ctx context.Context, body CreateStsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetSts(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetStsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateStsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateStsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateSts(ctx context.Context, body CreateStsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateStsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetStsRequest generates requests for GetSts
func NewGetStsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/credentials")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateStsRequest calls the generic CreateSts builder with application/json body
func NewCreateStsRequest(server string, body CreateStsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateStsRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateStsRequestWithBody generates requests for CreateSts with any type of body
func NewCreateStsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/credentials")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetStsWithResponse request
	GetStsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetStsHTTPResp, error)

	// CreateStsWithBodyWithResponse request with any body
	CreateStsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateStsHTTPResp, error)

	CreateStsWithResponse(ctx context.Context, body CreateStsJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateStsHTTPResp, error)
}

type GetStsHTTPResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Credentials
	JSON4XX      *NcloudClientError
	JSON5XX      *NcloudServerError
}

// Status returns HTTPResponse.Status
func (r GetStsHTTPResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetStsHTTPResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateStsHTTPResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Credentials
	JSON4XX      *NcloudClientError
	JSON5XX      *NcloudServerError
}

// Status returns HTTPResponse.Status
func (r CreateStsHTTPResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateStsHTTPResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetStsWithResponse request returning *GetStsHTTPResp
func (c *ClientWithResponses) GetStsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetStsHTTPResp, error) {
	rsp, err := c.GetSts(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetStsHTTPResp(rsp)
}

// CreateStsWithBodyWithResponse request with arbitrary body returning *CreateStsHTTPResp
func (c *ClientWithResponses) CreateStsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateStsHTTPResp, error) {
	rsp, err := c.CreateStsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateStsHTTPResp(rsp)
}

func (c *ClientWithResponses) CreateStsWithResponse(ctx context.Context, body CreateStsJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateStsHTTPResp, error) {
	rsp, err := c.CreateSts(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateStsHTTPResp(rsp)
}

// ParseGetStsHTTPResp parses an HTTP response from a GetStsWithResponse call
func ParseGetStsHTTPResp(rsp *http.Response) (*GetStsHTTPResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetStsHTTPResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Credentials
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest NcloudClientError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest NcloudServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParseCreateStsHTTPResp parses an HTTP response from a CreateStsWithResponse call
func ParseCreateStsHTTPResp(rsp *http.Response) (*CreateStsHTTPResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateStsHTTPResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Credentials
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest NcloudClientError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest NcloudServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}
